#ifndef RODIN_MPI_VARIATIONAL_FINITEELEMENTSPACE_H
#define RODIN_MPI_VARIATIONAL_FINITEELEMENTSPACE_H

/**
 * @file
 * @brief Base CRTP finite element space interface for MPI meshes.
 */

#include "Rodin/Variational/FiniteElementSpace.h"

#include "Rodin/MPI/Geometry/Mesh.h"

namespace Rodin::Variational
{
  /**
   * @brief Represents a finite element space defined on a distributed mesh.
   *
   * This CRTP base specializes @ref Rodin::Variational::FiniteElementSpace for
   * @ref Rodin::Geometry::Mesh<Rodin::Context::MPI>. Concrete distributed spaces
   * (such as MPI @ref Rodin::Variational::P1) provide the implementation for
   * local-to-global index translation, local finite elements, and geometric
   * mappings.
   *
   * @tparam Derived Concrete finite element space type.
   */
  template <class Derived>
  class FiniteElementSpace<Geometry::Mesh<Context::MPI>, Derived>
    : public FiniteElementSpaceBase
  {
    public:
      /**
       * @brief Distributed mesh type attached to this finite-element space.
       */
      using MeshType = Geometry::Mesh<Context::MPI>;

      /**
       * @brief Base finite-element-space interface.
       */
      using Parent = FiniteElementSpaceBase;

      using Parent::getGlobalIndex;

      /**
       * @brief Returns the global distributed index associated with local dof @p i.
       * @param[in] i Local shard degree-of-freedom index.
       * @return Global distributed index.
       */
      Index getGlobalIndex(Index i) const
      {
        return static_cast<const Derived&>(*this).getGlobalIndex(i);
      }

      /**
       * @brief Returns the distributed mesh on which the space is defined.
       * @return Reference to the distributed mesh.
       */
      const MeshType& getMesh() const override
      {
        return static_cast<const Derived&>(*this).getMesh();
      }

      /**
       * @brief Returns the finite element attached to local polytope @f$(d, i)@f$.
       * @param[in] d Topological dimension.
       * @param[in] i Local polytope index in the shard.
       * @return Finite element bound to the local polytope.
       * @note CRTP function to be overridden in the derived class.
       */
      const auto& getFiniteElement(size_t d, Index i) const
      {
        return static_cast<const Derived&>(*this).getFiniteElement(d, i);
      }

      /**
       * @brief Returns the pullback of a function from physical to reference coordinates.
       * @tparam T Callable type
       * @param[in] p Local polytope pair @f$(d, i)@f$.
       * @param[in] v Function defined on the physical mesh element.
       * @return Pullback/mapping object produced by the derived space.
       *
       * For all @f$ \tau \in \mathcal{T}_h @f$ in the mesh, the finite
       * element space is generated by the bijective mapping:
       * @f[
       *  \psi_\tau : V(\tau) \rightarrow V(R)
       * @f]
       * taking a function @f$ v \in V(\tau) @f$ from the global element @f$
       * \tau @f$ to the reference element @f$ R @f$. Here the notation @f$
       * V(S) @f$ represents a Banach space of functions on the set @f$ S @f$.
       *
       * The callable type T must be a function on the mesh, i.e. the call
       * operator must have the following signature:
       *
       * @code{.cpp}
       *  auto operator()(const Geometry::Point&);
       * @endcode
       *
       * @note CRTP function to be overridden in the derived class.
       */
      template <class T>
      auto getMapping(const std::pair<size_t, Index>& p, const T& v) const
      {
        return static_cast<const Derived&>(*this).getMapping(p, v);
      }

      /**
       * @brief Returns the inverse mapping (pushforward) back to physical coordinates.
       * @param[in] idx Local polytope pair @f$(d, i)@f$.
       * @param[in] v Callable defined on reference coordinates.
       * @return Pushforward object produced by the derived space.
       * @note CRTP function to be overridden in the derived class.
       */
      template <class CallableType>
      auto getInverseMapping(const std::pair<size_t, Index>& idx, const CallableType& v) const
      {
        return static_cast<const Derived&>(*this).geInverseMapping(idx, v);
      }
  };
}

#endif
