#ifndef RODIN_MPI_VARIATIONAL_FINITEELEMENTSPACE_H
#define RODIN_MPI_VARIATIONAL_FINITEELEMENTSPACE_H

#include "Rodin/Variational/FiniteElementSpace.h"

#include "Rodin/MPI/MPIMesh.h"

namespace Rodin::Variational
{
  /**
   * @brief Represernts a finite element space.
   */
  template <class Derived>
  class FiniteElementSpace<Geometry::Mesh<Context::MPI>, Derived>
    : public FiniteElementSpaceBase
  {
    public:
      /// Parent class
      using Parent = FiniteElementSpaceBase;

      using MeshType = Geometry::Mesh<Context::MPI>;

      Index getGlobalIndex(Index i) const
      {
        return static_cast<const Derived&>(*this).getGlobalIndex(i);
      }

      const MeshType& getMesh() const override
      {
        return static_cast<const Derived&>(*this).getMesh();
      }

      /**
       * @note CRTP function to be overriden in Derived class.
       */
      const auto& getFiniteElement(size_t d, Index i) const
      {
        return static_cast<const Derived&>(*this).getFiniteElement(d, i);
      }

      /**
       * @brief Returns the mapping of the function from the physical element
       * to the reference element.
       * @tparam T Callable type
       * @param[in] p Index of the element in the mesh
       * @param[in] v Function defined on an element of the mesh
       *
       * For all @f$ \tau \in \mathcal{T}_h @f$ in the mesh, the finite
       * element space is generated by the bijective mapping:
       * @f[
       *  \psi_\tau : V(\tau) \rightarrow V(R)
       * @f]
       * taking a function @f$ v \in V(\tau) @f$ from the global element @f$
       * \tau @f$ to the reference element @f$ R @f$. Here the notation @f$
       * V(S) @f$ represents a Banach space of functions on the set @f$ S @f$.
       *
       * The callable type T must be a function on the mesh, i.e. the call
       * operator must have the following signature:
       *
       * @code{cpp}
       *  auto operator()(const Geometry::Point&);
       * @endcode
       *
       * @note CRTP function to be overriden in Derived class.
       */
      template <class T>
      auto getMapping(const std::pair<size_t, Index>& p, const T& v) const
      {
        return static_cast<const Derived&>(*this).getMapping(p, v);
      }

      /**
       * @note CRTP function to be overriden in Derived class.
       */
      template <class CallableType>
      auto getInverseMapping(const std::pair<size_t, Index>& idx, const CallableType& v) const
      {
        return static_cast<const Derived&>(*this).geInverseMapping(idx, v);
      }
  };
}

#endif
