docs:
- any: ['doc/**/*']

examples:
- any: ['examples/**/*']

benchmarks:
- any: ['tests/benchmarks/**/*']

unit-tests:
- any: ['tests/unit/**/*']

cmake:
- any: ['cmake/**/*']
- any: ['src/CMakeLists.txt']
- any: ['src/Rodin/**/CMakeLists.txt']

advection:
- any: ['src/Rodin/Advection/**/*']

alerts:
- any: ['src/Rodin/Alert/**/*']
- any: ['src/Rodin/Alert.h']

assembly:
- any: ['src/Rodin/Assembly/**/*']
- any: ['src/Rodin/Assembly.h']

context:
- any: ['src/Rodin/Context/**/*']
- any: ['src/Rodin/Context.h']

distance:
- any: ['src/Rodin/Distance/**/*']

eikonal:
- any: ['src/Rodin/Eikonal/**/*']

form-language:
- any: ['src/Rodin/FormLanguage/**/*']
- any: ['src/Rodin/FormLanguage.h']

geometry:
- any: ['src/Rodin/Geometry/**/*']
- any: ['src/Rodin/Geometry.h']

hilbert:
- any: ['src/Rodin/Hilbert/**/*']

io:
- any: ['src/Rodin/IO/**/*']
- any: ['src/Rodin/IO.h']

linear-elasticity:
- any: ['src/Rodin/LinearElasticity/**/*']
- any: ['src/Rodin/LinearElasticity.h']

math:
- any: ['src/Rodin/Math/**/*']
- any: ['src/Rodin/Math.h']

mfem:
- any: ['src/Rodin/MFEM/**/*']

mmg:
- any: ['src/Rodin/MMG/**/*']
- any: ['src/Rodin/MMG.h']

mpi:
- any: ['src/Rodin/MPI/**/*']
- any: ['src/Rodin/MPI.h']

petsc:
- any: ['src/Rodin/PETSc/**/*']
- any: ['src/Rodin/PETSc.h']

qf:
- any: ['src/Rodin/QF/**/*']
- any: ['src/Rodin/QF.h']

scotch:
- any: ['src/Rodin/Scotch/**/*']

serialization:
- any: ['src/Rodin/Serialization/**/*']

solver:
- any: ['src/Rodin/Solver/**/*']
- any: ['src/Rodin/Solver.h']

test:
- any: ['src/Rodin/Test/**/*']
- any: ['src/Rodin/Test.h']

utility:
- any: ['src/Rodin/Utility/**/*']
- any: ['src/Rodin/Utility.h']

variational:
- any: ['src/Rodin/Variational/**/*']
- any: ['src/Rodin/Variational.h']
