/*
 *          Copyright Carlos BRITO PACHECO 2021 - 2026.
 * Distributed under the Boost Software License, Version 1.0.
 *       (See accompanying file LICENSE or copy at
 *          https://www.boost.org/LICENSE_1_0.txt)
 */
/**
 * @file ProteinTest.cpp
 * @brief Minimal testbed for the coagulation kinetics on a simplified
 *        coronary-like geometry: one inlet, one outlet, one wall, and a
 *        traction-free outlet.
 *
 * Why this geometry. A straight conduit is the wrong test. Its residence time
 * is of order 0.1 s, and the closed-reactor estimate below shows that the
 * kinetics then convert about 1e-5 of the available fibrinogen -- indistinguishable
 * from zero. The mesh generated by ProteinTest/make_test_mesh.py is therefore a
 * straight tube carrying an ectatic segment (radius 1.5 mm widening to 4.5 mm,
 * expansion ratio 3), which produces a recirculation bubble. The point of the
 * test is that both regimes are present in one run: the conduit shows nothing
 * and the pouch does, which is what tells you the model discriminates rather
 * than merely producing a number.
 *
 * How much residence time is needed. Treating the pouch as a closed reactor fed
 * by a wall flux, Th(t) = R_th S t with S = A/V the surface-to-volume ratio, and
 *
 *     Fg(t) = Fg0 exp( -k_eff R_th S t^2 / 2 ),   Fn = Fg0 - Fg,
 *
 * so a one per cent conversion needs t_res = sqrt( 0.02 / (k_eff R_th S) ).
 * With S ~ 1e3 1/m this is about 5 s, i.e. six cycles; a fully formed clot
 * needs of order a minute. Those are the numbers to check the run against, and
 * they are printed at startup.
 *
 * A washout field is solved alongside the species so that this can be verified
 * rather than assumed:
 *
 *     dc/dt + u.grad c = 0,   c = 1 at t0,   c = 0 at the inlet,
 *
 * with c the surviving fraction of the original bolus. The reported number is
 * the volume-weighted residual R(t) = (1/V) int c dV and its decay constant.
 * This replaces the Eulerian age field dT/dt + u.grad T = 1, which is not
 * reportable: on closed streamlines T grows without bound, so what you read off
 * is how long you ran rather than a property of the flow. c is bounded in
 * [0, 1] and R converges, so it is comparable between geometries.
 *
 * The outlet carries no Windkessel and no R_mu closure: p_out = 0. That is
 * deliberate. The quantity the whole test hinges on is how long blood is held,
 * and a rheology-dependent nonlinear outlet would sit between the geometry and
 * that quantity, so a washout that came out too fast could no longer be
 * attributed to the geometry alone.
 *
 * One loop, flow solved every step. The coupling is one-way, so the flow could
 * be solved for a few cycles, recorded, and replayed while only the species
 * advance -- and an earlier version did exactly that. It is dropped here: it
 * bought speed with an array of PETSc Vecs and a VecDuplicate/VecCopy/
 * VecDestroy layer that appears nowhere else in this tree, and it turned the
 * velocity from a solution into a recording. The flow is about three quarters
 * of a step, so solving it throughout costs
 * (flowCycles + speciesCycles)/flowCycles times more -- and it holds one
 * velocity field rather than one per step of a cycle, so it is the smaller
 * memory footprint too. -pt_flow_cycles is the warm-up before the species
 * switch on, -pt_species_cycles how long they then run.
 *
 * @see CoronaryArtery/ThrombosisModel.h for the kinetics and the scope of the
 *      model.
 */
#include <algorithm>
#include <cassert>
#include <cmath>
#include <chrono>
#include <cstddef>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <numbers>
#include <sstream>
#include <vector>
#include <stdexcept>

#include <Rodin/Geometry.h>
#include <Rodin/IO/XDMF.h>
#include <Rodin/Math.h>
#include <Rodin/PETSc.h>
#include <Rodin/Solver.h>
#include <Rodin/Types.h>
#include <Rodin/Variational.h>

#include "CoronaryArtery/ThrombosisModel.h"
#include "CoronaryArtery/VMSConvectionIntegrator.h"

using namespace Rodin;
using namespace Rodin::Geometry;
using namespace Rodin::Math;
using namespace Rodin::Solver;
using namespace Rodin::Variational;
using namespace Rodin::Examples::Heart;

namespace
{
  using Real = Rodin::Real;
  using MeshType = Geometry::Mesh<Context::Local>;

  // ---- Boundary attributes, matching make_test_mesh.py --------------------
  constexpr Attribute WALL = 2;
  constexpr Attribute INLET = 4;
  constexpr Attribute OUTLET = 7;

  /// @brief Carreau-Yasuda parameters, kept local so the test does not depend
  ///        on the coronary example's header.
  struct CarreauYasudaParameters
  {
      Real mu0 = 0.0720;
      Real muInf = 0.0049;
      Real lambda = 6.1529;
      Real n = 0.2081;
      Real yasuda = 1.4173;
      Real gammaRegularization = 1.0e-3;
  };

  struct Config
  {
      std::string meshPath = "../resources/examples/Heart/ProteinTest.mesh";
      std::string xdmfBasename = "ProteinTest";
      std::string csvPath = "ProteinTest.csv";

      // ---- Fluid -----------------------------------------------------------
      Real rho = 1060.0;
      /// @brief Pressure stabilisation for the equal-order penalty term.
      Real pressurePenalty = 1.0e-12;
      CarreauYasudaParameters viscosity;

      // ---- Driving ---------------------------------------------------------
      /// @brief Mean inlet pressure (Pa) and pulse amplitude (Pa).
      Real inletPressureMean = 100.0;
      Real inletPressureAmplitude = 50.0;
      Real period = 0.85;

      Real dt = 1.0e-3;
      int flowCycles = 3;
      int speciesCycles = 12;

      // ---- Thrombosis ------------------------------------------------------
      ThrombosisParameters thrombosis;

      bool solveKinetics = true;
      bool solveWashout = true;

      Real maxVelocity = 5.0;

      /// @brief Boundary impedance, as a fraction of the conduit's own
      ///        Poiseuille resistance. Z = fraction * R_pois * A [Pa s/m].
      ///
      /// @details A pressure-driven inlet with no impedance has no energy
      ///          bound. With the Temam correction the convective operator is
      ///          skew-symmetric inside the domain, so the only convective
      ///          energy term left is the boundary flux
      ///          (rho/2) \int_Gamma |u|^2 (u.n). At the inlet u.n < 0, so
      ///          that is an energy INFLUX growing like |u|^3, while the only
      ///          thing opposing it -- viscous dissipation -- grows like
      ///          |u|^2. Nothing restores equilibrium and the flow runs away:
      ///          exactly the 0.09 -> 0.43 -> 0.55 -> 6.5 m/s growth observed.
      ///
      ///          A prescribed-velocity inlet does not have this problem
      ///          because u is fixed there. Both working examples in this tree
      ///          drive their inlet with a pressure and therefore both add a
      ///          positive-definite normal impedance Z (u.n)(v.n) --
      ///          CoupledLV0DCoronary3D::inletImpedance = 5e2, and the P1/P1
      ///          FSI's per-outlet Z = scale * R_pois * A. This example was the
      ///          only one without it.
      ///
      ///          It is also the physical statement: a pressure source with
      ///          zero source impedance is not realisable. Unlike a Windkessel
      ///          this adds no state and no rheology dependence -- one number
      ///          per boundary -- so the outlet stays clean.
      Real boundaryImpedanceFraction = 0.5;

      /// @brief Tangential damping at the pressure-driven inlet [Pa s/m].
      /// @details A pure traction inlet leaves u_tau completely unconstrained.
      ///          Same value and role as CoupledLV0DCoronary3D's
      ///          inletTangentialDamping.
      Real inletTangentialDamping = 1.0e3;

      /// @brief Codina crosswind (discontinuity-capturing) constant. 0 disables.
      ///
      /// @details SUPG controls the streamline direction only; it leaves the
      ///          crosswind direction free, which is why thrombin and fibrin
      ///          came out NEGATIVE (-31% and -54% of their own maxima) in
      ///          bands across the ectatic shoulder. Codina (CMAME 110, 1993,
      ///          325-342) adds a nonlinear dissipation acting only on the
      ///          crosswind component, designed from the discrete maximum
      ///          principle, and less overdiffusive than earlier
      ///          discontinuity-capturing schemes. C ~ 0.7 for linear elements.
      ///
      ///          This damps the oscillation; it does NOT resolve the 25 um
      ///          concentration layer, which is 9x below the element size.
      Real crosswindC = 0.7;
  };

  /// @brief Closed-reactor estimate of the conversion attainable in a pocket of
  ///        surface-to-volume ratio S held for a residence time t.
  Real fibrinFraction(const ThrombosisParameters& p, Real S, Real t)
  {
    const Real e = p.reactionRate * p.thrombinWallFlux * S * t * t / 2.0;
    return 1.0 - std::exp(-e);
  }

  /// @brief Residence time needed for a prescribed conversion.
  Real residenceTimeFor(const ThrombosisParameters& p, Real S, Real fraction)
  {
    const Real e = -std::log(1.0 - fraction);
    return std::sqrt(2.0 * e / (p.reactionRate * p.thrombinWallFlux * S));
  }
}

namespace
{
  /// @brief Default a KSP to Jacobi-preconditioned CG under its own options
  ///        prefix.
  void configureMassSolver(Rodin::Solver::KSP& ksp, const std::string& prefix)
  {
    const auto setDefault = [&](const char* suffix, const char* value) {
      const std::string name = "-" + prefix + suffix;
      PetscBool set = PETSC_FALSE;
      PetscOptionsHasName(PETSC_NULLPTR, PETSC_NULLPTR, name.c_str(), &set);
      if (!set)
        PetscOptionsSetValue(PETSC_NULLPTR, name.c_str(), value);
    };
    setDefault("ksp_type", "cg");
    setDefault("pc_type", "jacobi");
    ksp.setPrefix(prefix);
  }
}

int main(int argc, char** argv)
{
  PetscInitialize(&argc, &argv, PETSC_NULLPTR, PETSC_NULLPTR);

  const auto setPETScDefault = [](const char* name, const char* value) {
    PetscBool set = PETSC_FALSE;
    PetscOptionsHasName(PETSC_NULLPTR, PETSC_NULLPTR, name, &set);
    if (!set)
      PetscOptionsSetValue(PETSC_NULLPTR, name, value);
  };

  setPETScDefault("-ksp_type", "preonly");
  setPETScDefault("-pc_type", "lu");
  setPETScDefault("-pc_factor_mat_solver_type", "mumps");
  setPETScDefault("-mat_mumps_icntl_20", "0");
  setPETScDefault("-mat_mumps_icntl_21", "0");

  Config cfg;

  {
    PetscInt fcyc = cfg.flowCycles;
    PetscInt scyc = cfg.speciesCycles;
    PetscReal dtv = cfg.dt;
    PetscBool got = PETSC_FALSE;
    PetscOptionsGetInt(PETSC_NULLPTR, PETSC_NULLPTR, "-pt_flow_cycles", &fcyc, &got);
    if (got)
      cfg.flowCycles = static_cast<int>(fcyc);
    got = PETSC_FALSE;
    PetscOptionsGetInt(PETSC_NULLPTR, PETSC_NULLPTR, "-pt_species_cycles", &scyc, &got);
    if (got)
      cfg.speciesCycles = static_cast<int>(scyc);
    got = PETSC_FALSE;
    PetscOptionsGetReal(PETSC_NULLPTR, PETSC_NULLPTR, "-pt_dt", &dtv, &got);
    if (got)
      cfg.dt = dtv;

    PetscReal pm = cfg.inletPressureMean;
    got = PETSC_FALSE;
    PetscOptionsGetReal(PETSC_NULLPTR, PETSC_NULLPTR, "-pt_pmean", &pm, &got);
    if (got)
    {
      const Real ratio = cfg.inletPressureAmplitude / cfg.inletPressureMean;
      cfg.inletPressureMean = pm;
      cfg.inletPressureAmplitude = ratio * pm;
    }
    PetscReal pa = cfg.inletPressureAmplitude;
    got = PETSC_FALSE;
    PetscOptionsGetReal(PETSC_NULLPTR, PETSC_NULLPTR, "-pt_pamp", &pa, &got);
    if (got)
      cfg.inletPressureAmplitude = pa;

    char meshBuf[512];
    got = PETSC_FALSE;
    PetscOptionsGetString(
      PETSC_NULLPTR, PETSC_NULLPTR, "-pt_mesh", meshBuf, sizeof(meshBuf), &got);
    if (got)
      cfg.meshPath = meshBuf;
  }

  // -------------------------------------------------------------------------
  // Mesh
  // -------------------------------------------------------------------------
  MeshType mesh;
  mesh.load(cfg.meshPath, IO::FileFormat::MEDIT);

  const size_t dim = mesh.getSpaceDimension();
  const size_t D = mesh.getDimension();

  if (dim != 3 || D != 3)
    throw std::runtime_error("ProteinTest expects a 3D tetrahedral mesh.");

  mesh.getConnectivity().compute(D, D);
  mesh.getConnectivity().compute(D, 0);
  mesh.getConnectivity().compute(D, D - 1);
  mesh.getConnectivity().compute(D - 1, D);
  mesh.getConnectivity().compute(D - 1, 0);
  mesh.getConnectivity().compute(D - 1, 1);
  mesh.getConnectivity().compute(1, 0);

  Alert::Info() << "[mesh] vertices=" << mesh.getVertexCount()
                << " cells=" << mesh.getCellCount() << " dim=" << dim << Alert::Raise;

  using VelocityFES = H1<1, Math::SpatialVector<Real>, MeshType>;
  using ScalarFES = H1<1, Real, MeshType>;

  VelocityFES vh(std::integral_constant<size_t, 1>{}, mesh, dim);
  ScalarFES ph(std::integral_constant<size_t, 1>{}, mesh);
  ScalarFES sh(std::integral_constant<size_t, 1>{}, mesh);

  PETSc::Variational::TrialFunction u(vh);
  PETSc::Variational::TrialFunction p(ph);
  PETSc::Variational::TestFunction v(vh);
  PETSc::Variational::TestFunction q(ph);

  PETSc::Variational::GridFunction uOld(vh);
  uOld = Math::SpatialVector<Real>{{0.0, 0.0, 0.0}};

  // Species and washout
  PETSc::Variational::TrialFunction th(sh);
  PETSc::Variational::TrialFunction fg(sh);
  PETSc::Variational::TrialFunction fn(sh);
  PETSc::Variational::TrialFunction wash(sh);

  PETSc::Variational::TestFunction vth(sh);
  PETSc::Variational::TestFunction vfg(sh);
  PETSc::Variational::TestFunction vfn(sh);
  PETSc::Variational::TestFunction vwash(sh);

  // One extra history level per species. The crosswind coefficient is sized
  // from the residual, whose transient part needs c^{n-1} as well as c^n.
  PETSc::Variational::GridFunction thPrev(sh);
  PETSc::Variational::GridFunction fgPrev(sh);
  PETSc::Variational::GridFunction fnPrev(sh);

  PETSc::Variational::GridFunction thCur(sh);
  PETSc::Variational::GridFunction fgCur(sh);
  PETSc::Variational::GridFunction fnCur(sh);
  PETSc::Variational::GridFunction washCur(sh);
  PETSc::Variational::GridFunction washPrev(sh);

  thCur = Real(0);
  fnCur = Real(0);
  thPrev = Real(0);
  fnPrev = Real(0);
  // Washout starts fully "old": every point holds the original bolus.
  washCur = Real(1);
  washPrev = Real(1);
  fgCur = Real(cfg.thrombosis.fibrinogenSinusRhythm / cfg.thrombosis.fibrinogenMolarMass);
  fgPrev =
    Real(cfg.thrombosis.fibrinogenSinusRhythm / cfg.thrombosis.fibrinogenMolarMass);

  // Wall-shear indices and the activation weight they produce
  PETSc::Variational::GridFunction wss(vh);
  PETSc::Variational::GridFunction activation(sh);
  activation = Real(0);

  WallShearAccumulator<PETSc::Variational::GridFunction<VelocityFES>,
    PETSc::Variational::GridFunction<ScalarFES>>
    indices(vh, sh);

  const auto normal = BoundaryNormal(mesh);

  // -------------------------------------------------------------------------
  // VMS stabilisation fields (Codina), following the P1/P1 coronary example
  // -------------------------------------------------------------------------
  ScalarFES tauFes(std::integral_constant<size_t, 1>{}, mesh);

  PETSc::Variational::TrialFunction vmsTau(tauFes);
  PETSc::Variational::TestFunction vmsTauTest(tauFes);
  PETSc::Variational::TrialFunction vmsTauC(tauFes);
  PETSc::Variational::TestFunction vmsTauCTest(tauFes);
  PETSc::Variational::TrialFunction vmsSqrtTauC(tauFes);
  PETSc::Variational::GridFunction vmsSqrtTauCOld(tauFes);
  PETSc::Variational::TrialFunction vmsPiTilde(tauFes);
  PETSc::Variational::TrialFunction vmsTauP(tauFes);
  vmsSqrtTauCOld = Real(0);

  VelocityFES vmsFes(std::integral_constant<size_t, 1>{}, mesh, dim);
  PETSc::Variational::TrialFunction vmsUp(vmsFes);
  PETSc::Variational::TrialFunction vmsSub(vmsFes);
  PETSc::Variational::TestFunction vmsVp(vmsFes);
  PETSc::Variational::GridFunction vmsSubOld(vmsFes);
  vmsSubOld = Math::SpatialVector<Real>{{0.0, 0.0, 0.0}};

  const Real vmsScale = 1.0;
  const Real gradDivScale = 1.0;
  const Real pgpScale = 1.0;

  // Codina tau1 with c1 = 4, c2 = 2, k = 1 (P1), h_K = |K|^{1/d}.
  auto tau1At = [&](const Point& pp) -> Real {
    const auto uc = uOld.getValue(pp);
    const Real nu = cfg.viscosity.mu0 / cfg.rho;
    const Real hK =
      std::pow(pp.getPolytope().getMeasure(), 1.0 / pp.getPolytope().getDimension());
    const Real speed = std::sqrt(Math::dot(uc, uc));
    return 1.0 / (4.0 * nu / (hK * hK) + 2.0 * speed / hK);
  };

  const auto vmsConvectionTarget = Mult(Jacobian(uOld), uOld);

  RealFunction vmsTauFn = [&, tau1At](const Point& pp) -> Real {
    return vmsScale / (cfg.rho / cfg.dt + cfg.rho / tau1At(pp));
  };

  auto vmsSubUpdate =
    VectorFunction(dim, [&](const Point& pp) -> Math::SpatialVector<Real> {
      const auto conv = vmsConvectionTarget.getValue(pp);
      const auto proj = vmsUp.getSolution().getValue(pp);
      const auto old = vmsSubOld.getValue(pp);
      const Real tau = vmsTau.getSolution().getValue(pp);

      Math::SpatialVector<Real> out(dim);
      for (Index c = 0; c < static_cast<Index>(dim); ++c)
        out(c) = tau * cfg.rho * (old(c) / cfg.dt - (conv(c) - proj(c)));
      return out;
    });

  auto rhoTau2At = [&, tau1At](const Point& pp) -> Real {
    const Real hK =
      std::pow(pp.getPolytope().getMeasure(), 1.0 / pp.getPolytope().getDimension());
    return gradDivScale * cfg.rho * (hK * hK) / (4.0 * tau1At(pp));
  };

  RealFunction sqrtRhoTau2Fn = [rhoTau2At](const Point& pp) -> Real {
    return std::sqrt(std::max<Real>(0.0, rhoTau2At(pp)));
  };

  RealFunction vmsTauPFn = [&, tau1At](const Point& pp) -> Real {
    return pgpScale * tau1At(pp) / cfg.rho;
  };

  Problem vmsL2Conv(vmsUp, vmsVp);
  vmsL2Conv = Integral(vmsUp, vmsVp) - Integral(vmsConvectionTarget, vmsVp);

  Problem vmsTauProj(vmsTau, vmsTauTest);
  vmsTauProj = Integral(vmsTau, vmsTauTest) - Integral(vmsTauFn, vmsTauTest);

  Problem vmsSubProj(vmsSub, vmsVp);
  vmsSubProj = Integral(vmsSub, vmsVp) - Integral(vmsSubUpdate, vmsVp);

  Problem vmsSqrtTauCProj(vmsSqrtTauC, vmsTauCTest);
  vmsSqrtTauCProj =
    Integral(vmsSqrtTauC, vmsTauCTest) - Integral(sqrtRhoTau2Fn, vmsTauCTest);

  Problem vmsPiTildeProj(vmsPiTilde, vmsTauCTest);
  vmsPiTildeProj =
    Integral(vmsPiTilde, vmsTauCTest) - Integral(vmsSqrtTauCOld * Div(uOld), vmsTauCTest);

  Problem vmsTauPProj(vmsTauP, vmsTauCTest);
  vmsTauPProj = Integral(vmsTauP, vmsTauCTest) - Integral(vmsTauPFn, vmsTauCTest);

  // Persistent KSPs. Constructing a KSP per solve rebuilds the preconditioner
  // from scratch every time; hoisting them lets PETSc keep it across steps.
  Solver::KSP vmsL2ConvKSP(vmsL2Conv);
  Solver::KSP vmsTauKSP(vmsTauProj);
  Solver::KSP vmsSubKSP(vmsSubProj);
  Solver::KSP vmsSqrtTauCKSP(vmsSqrtTauCProj);
  Solver::KSP vmsPiTildeKSP(vmsPiTildeProj);
  Solver::KSP vmsTauPKSP(vmsTauPProj);
  configureMassSolver(vmsL2ConvKSP, "pt_vms_conv_");
  configureMassSolver(vmsTauKSP, "pt_vms_tau_");
  configureMassSolver(vmsSubKSP, "pt_vms_sub_");
  configureMassSolver(vmsSqrtTauCKSP, "pt_vms_sqrttauc_");
  configureMassSolver(vmsPiTildeKSP, "pt_vms_pitilde_");
  configureMassSolver(vmsTauPKSP, "pt_vms_taup_");

  PETSc::Variational::TrialFunction gradRecTrial0(vh);
  PETSc::Variational::TrialFunction gradRecTrial1(vh);
  PETSc::Variational::TrialFunction gradRecTrial2(vh);
  PETSc::Variational::TestFunction gradRecTest(vh);
  Problem gradRecProj0(gradRecTrial0, gradRecTest);
  Problem gradRecProj1(gradRecTrial1, gradRecTest);
  Problem gradRecProj2(gradRecTrial2, gradRecTest);

  PETSc::Variational::TrialFunction wssTrial(vh);
  PETSc::Variational::TestFunction wssTest(vh);
  Problem wssProj(wssTrial, wssTest);

  Solver::KSP gradRecKSP0(gradRecProj0);
  Solver::KSP gradRecKSP1(gradRecProj1);
  Solver::KSP gradRecKSP2(gradRecProj2);
  Solver::KSP wssKSP(wssProj);
  configureMassSolver(gradRecKSP0, "pt_gradrec0_");
  configureMassSolver(gradRecKSP1, "pt_gradrec1_");
  configureMassSolver(gradRecKSP2, "pt_gradrec2_");
  configureMassSolver(wssKSP, "pt_wss_");

  // -------------------------------------------------------------------------
  // A priori budget: print what the run can possibly show
  // -------------------------------------------------------------------------
  {
    const Real Sconduit = 2.0 / 1.5e-3;   // 2/r for a cylinder
    const Real Spouch = 2.0 / 4.5e-3;
    const Real Ttot = cfg.speciesCycles * cfg.period;

    Alert::Info() << "[budget] simulated time = " << Ttot << " s (" << cfg.speciesCycles
                  << " species cycles)" << Alert::Raise;
    for (auto [S, name] : {std::pair<Real, const char*>{Sconduit, "conduit r=1.5mm"},
           std::pair<Real, const char*>{Spouch, "pouch r=4.5mm"}})
    {
      Alert::Info() << "  S=" << S << " 1/m (" << name << "):"
                    << "  t_res for 1% conversion = "
                    << residenceTimeFor(cfg.thrombosis, S, 0.01) << " s"
                    << "  |  conversion at t=" << Ttot
                    << " s if fully trapped = " << fibrinFraction(cfg.thrombosis, S, Ttot)
                    << Alert::Raise;
    }
    Alert::Info() << "[budget] compare those against the washout: if the "
                  << "residual fraction R decays to zero within a cycle or two, "
                  << "nothing is held long enough and the fibrin field will be "
                  << "numerically zero -- which means the geometry has no "
                  << "stasis, not that the model is wrong." << Alert::Raise;
  }

  // -------------------------------------------------------------------------
  // Output
  // -------------------------------------------------------------------------
  // Every field written to XDMF must be named first.
  u.setName("velocity");
  p.setName("pressure");
  thCur.setName("thrombin");
  fgCur.setName("fibrinogen");
  fnCur.setName("fibrin");
  washCur.setName("washout");
  activation.setName("activation");
  indices.tawss().setName("TAWSS");
  indices.osi().setName("OSI");
  indices.ecap().setName("ECAP");

  IO::XDMF xdmf(cfg.xdmfBasename);
  xdmf.setMesh(mesh);
  xdmf.add("velocity", u.getSolution());
  xdmf.add("pressure", p.getSolution());
  xdmf.add("thrombin", thCur);
  xdmf.add("fibrinogen", fgCur);
  xdmf.add("fibrin", fnCur);
  xdmf.add("washout", washCur);
  xdmf.add("TAWSS", indices.tawss());
  xdmf.add("OSI", indices.osi());
  xdmf.add("ECAP", indices.ecap());
  xdmf.add("activation", activation);

  Alert::Info() << "[chk] XDMF fields registered" << Alert::Raise;

  std::ofstream csv(cfg.csvPath);
  csv << "t,cycle,inletPressure,"
      << "washoutResidualFraction,clearanceTau,"
      << "maxTAWSS,maxOSI,maxECAP,"
      << "maxThrombin,minFibrinogen,maxFibrin,fibrinFraction\n";

  // The three time-stepped problems are declared once and their expressions
  // reassigned each step, so their KSPs -- and the preconditioners -- persist.
  // The flow is a saddle-point system and keeps the global (direct) solver;
  // setFieldSplits is a one-off setup and must not be repeated every step.
  Problem flow(u, p, v, q);
  Solver::KSP flowKSP(flow);
  bool flowSplitsSet = false;

  Problem washout(wash, vwash);
  Solver::KSP washoutKSP(washout);

  // Volume integral of a P1 field. Contracting its load vector with the all-ones
  // vector gives int f dV exactly, because the P1 basis is a partition of unity
  // (sum_i phi_i = 1). Same idiom as the flux forms in the coronary examples.
  PETSc::Variational::TestFunction qWash(sh);
  PETSc::Variational::GridFunction oneGf(sh);
  oneGf = Real(1);
  LinearForm<ScalarFES, ::Vec> washIntegral(qWash);

  Problem protein(th, fg, fn, vth, vfg, vfn);
  Solver::KSP proteinKSP(protein);

  Real pInValue = cfg.inletPressureMean;
  auto pIn = RealFunction([&](const Point&) { return pInValue; });

  const auto& cy = cfg.viscosity;
  const Real deltaMu = cy.mu0 - cy.muInf;

  const auto symU = 0.5 * (Jacobian(u) + Transpose(Jacobian(u)));
  const auto symV = 0.5 * (Jacobian(v) + Transpose(Jacobian(v)));
  const auto symLag = 0.5 * (Jacobian(uOld) + Transpose(Jacobian(uOld)));

  const auto shearLag =
    Sqrt(cy.gammaRegularization * cy.gammaRegularization + 2.0 * Dot(symLag, symLag));
  const auto muLag = cy.muInf +
    deltaMu * Pow(1.0 + Pow(cy.lambda * shearLag, cy.yasuda), (cy.n - 1.0) / cy.yasuda);

  const auto convU = Mult(Jacobian(u), uOld);
  const auto temam = Div(uOld) * Dot(u, v);

  // Impedance sized from the conduit's own Poiseuille resistance, so it is
  // one physical number rather than a tuned constant:
  //   R_pois = 8 mu L / (pi r^4),   A = pi r^2,   Z = fraction * R_pois * A.
  // In lumped terms each boundary then adds Z/A = fraction * R_pois to the
  // circuit, so the steady velocity is
  //   v = dp / ((1 + 2 fraction) R_pois A).
  const Real condR = 1.5e-3, condL = 40.0e-3;
  const Real condA = std::numbers::pi_v<Real> * condR * condR;
  const Real condRpois =
    8.0 * cfg.viscosity.muInf * condL / (std::numbers::pi_v<Real> * std::pow(condR, 4.0));
  const Real boundaryZ = cfg.boundaryImpedanceFraction * condRpois * condA;
  const Real vPredicted = cfg.inletPressureMean /
    ((1.0 + 2.0 * cfg.boundaryImpedanceFraction) * condRpois * condA);

  Alert::Info() << "[inlet] Z=" << boundaryZ << " Pa s/m at each end ("
                << cfg.boundaryImpedanceFraction << " x R_pois A); predicted "
                << "steady v=" << vPredicted << " m/s at p_mean=" << cfg.inletPressureMean
                << " Pa. Raise -pt_pmean to "
                << (0.2 / std::max(vPredicted, 1e-12) * cfg.inletPressureMean)
                << " Pa for v=0.2 m/s." << Alert::Raise;
  if (0.5 * cfg.rho * vPredicted > boundaryZ)
    Alert::Warning() << "[inlet] Z is below the inflow kinetic flux scale "
                     << "(rho v / 2 = " << (0.5 * cfg.rho * vPredicted)
                     << "); the run may still diverge. Raise "
                     << "boundaryImpedanceFraction." << Alert::Raise;

  const auto uNormal = Dot(u, normal) * normal;
  const auto uTangential = u - uNormal;

  const auto inletBeta = Max(Dot(uOld, normal), 0.0);
  const auto outletBeta = Max(-Dot(uOld, normal), 0.0);
  const auto inletBackflow = 0.5 * cfg.rho * inletBeta;
  const auto outletBackflow = 0.5 * cfg.rho * outletBeta;

  flow = (cfg.rho / cfg.dt) * Integral(u, v) - (cfg.rho / cfg.dt) * Integral(uOld, v)

    + cfg.rho * Integral(Dot(convU, v)) + 0.5 * cfg.rho * Integral(temam)

    + VMSConvectionBilinearIntegrator(u, v, uOld, vmsTau.getSolution(), cfg.rho) -
    VMSConvectionLinearIntegrator(v, vmsSub.getSolution(), uOld, vmsUp.getSolution(),
      vmsTau.getSolution(), cfg.rho, cfg.dt)

    + VMSGradDivBilinearIntegrator(u, v, vmsTauC.getSolution()) -
    VMSGradDivLinearIntegrator(v, vmsPiTilde.getSolution(), vmsSqrtTauC.getSolution())

    + 2.0 * Integral(muLag * symU, symV) - Integral(p, Div(v)) + Integral(Div(u), q) +
    cfg.pressurePenalty * Integral(p, q)

       // PSPG / grad-p. REQUIRED for the equal-order P1/P1 pair.
    + Integral(vmsTauP.getSolution() * Grad(p), Grad(q))

    + BoundaryIntegral(pIn * Dot(v, normal)).over(INLET)
       // No outlet traction term: p_out = 0 is still the free condition.

       // Normal impedance at BOTH ends: the O(|u|^2) restoring term that the
       // pressure-driven boundary needs. Positive semidefinite, so it can only
       // help conditioning.
    + boundaryZ * BoundaryIntegral(Dot(uNormal, v)).over(INLET) +
    boundaryZ * BoundaryIntegral(Dot(uNormal, v)).over(OUTLET)

       // A pure traction boundary says nothing about u_tau; without this the
       // inlet plane can develop an unopposed swirl.
    + cfg.inletTangentialDamping * BoundaryIntegral(Dot(uTangential, v)).over(INLET)

    + BoundaryIntegral(inletBackflow * Dot(u, v)).over(INLET) +
    BoundaryIntegral(outletBackflow * Dot(u, v)).over(OUTLET)

    + DirichletBC(u, Zero(dim)).on(WALL);

  // ---- Transport stabilisation ---------------------------------------------
  // These transport problems must NOT reuse the flow's tau1. tau1 is built from
  // the kinematic viscosity nu = mu0/rho = 6.8e-5 m^2/s, whereas the species
  // diffuse at D ~ 2e-11 to 5e-11 m^2/s -- six orders of magnitude smaller. The
  // cell Peclet number is 1.9e6, not 1.3, so these are essentially pure
  // advection problems and their tau is set by the advective and transient
  // scales alone. Feeding them the flow's tau made every stabilisation term
  // 2.6x too small on this mesh.
  //
  // supgTau (ThrombosisModel.h) is the standard Shakib/Codina form
  //   tau = [ (2/dt)^2 + (2|u|/h)^2 + (4D/h^2)^2 + s^2 ]^{-1/2},
  // with s the reactive rate. Evaluated pointwise on the local element rather
  // than from a global h_min, so the coarse ectatic cells and the fine conduit
  // cells each get their own value.
  const Real Dth = cfg.thrombosis.diffusivityThrombin;
  const Real Dfg = cfg.thrombosis.diffusivityFibrinogen;
  const Real Dfn = cfg.thrombosis.diffusivityFibrin;
  const Real keff = cfg.thrombosis.reactionRate;
  const Real stabScale = cfg.thrombosis.stabilizationScale;

  auto hAt = [](const Point& pp) -> Real {
    return std::pow(pp.getPolytope().getMeasure(), 1.0 / pp.getPolytope().getDimension());
  };
  auto speedAt = [&](const Point& pp) -> Real {
    const auto uc = uOld.getValue(pp);
    return std::sqrt(Math::dot(uc, uc));
  };

  // Only Fg carries a reactive rate: it is the only species whose sink is
  // proportional to its own unknown (k Th fg). Th and Fn are fed by a wall flux
  // and by that same product, neither of which involves their own value.
  RealFunction tauThFn = [&, hAt, speedAt](const Point& pp) -> Real {
    return stabScale * supgTau(hAt(pp), speedAt(pp), Dth, 0.0, cfg.dt);
  };
  RealFunction tauFgFn = [&, hAt, speedAt](const Point& pp) -> Real {
    const Real react = keff * std::abs(thCur.getValue(pp));
    return stabScale * supgTau(hAt(pp), speedAt(pp), Dfg, react, cfg.dt);
  };
  RealFunction tauFnFn = [&, hAt, speedAt](const Point& pp) -> Real {
    return stabScale * supgTau(hAt(pp), speedAt(pp), Dfn, 0.0, cfg.dt);
  };
  // The washout equation has no diffusion and no reaction: dc/dt + u.grad c = 0.
  RealFunction tauWashFn = [&, hAt, speedAt](const Point& pp) -> Real {
    return stabScale * supgTau(hAt(pp), speedAt(pp), 0.0, 0.0, cfg.dt);
  };

  // ---- Codina crosswind (discontinuity capturing) ----------------------------
  //
  //   k_dc = max{ 0, C |R(c)| h / (2 |grad c|) - D }
  //
  // added as  k_dc * (P_perp grad c).(P_perp grad v)  with
  // P_perp = I - (u @ u)/|u|^2. Expanded, that is
  //
  //   k_dc [ grad c . grad v - (u.grad c)(u.grad v)/|u|^2 ],
  //
  // so no custom integrator is needed for a scalar field. k_dc is evaluated
  // pointwise rather than L2-projected: it is element-wise constant by design,
  // and projecting it onto a continuous P1 field would smear exactly the local
  // character the method relies on. Lagged on c^n, so the term stays bilinear.
  const Real gradFloorCW = 1.0e-14;

  RealFunction invSpeedSqFn = [&](const Point& pp) -> Real {
    const auto uc = uOld.getValue(pp);
    const Real u2 = Math::dot(uc, uc);
    return (u2 > 1.0e-20) ? 1.0 / u2 : 0.0;
  };

  const auto gradThCur = Grad(thCur);
  const auto gradFgCur = Grad(fgCur);
  const auto gradFnCur = Grad(fnCur);
  const auto gradWashCur = Grad(washCur);

  // react - source, i.e. everything in the residual that is not transient or
  // convective. The thrombin wall flux is a BOUNDARY term, so it contributes
  // nothing to the volumetric residual.
  auto crosswindK = [&, hAt](const Point& pp, Real cCur, Real cPrev,
                      const Math::SpatialVector<Real>& g, Real D,
                      Real reactMinusSource) -> Real {
    const Real gn = std::sqrt(Math::dot(g, g));
    if (gn < gradFloorCW)
      return 0.0;
    const auto uc = uOld.getValue(pp);
    const Real R = (cCur - cPrev) / cfg.dt + Math::dot(uc, g) + reactMinusSource;
    return std::max<Real>(0.0, cfg.crosswindC * std::abs(R) * hAt(pp) / (2.0 * gn) - D);
  };

  RealFunction kdcThFn = [&](const Point& pp) -> Real {
    return crosswindK(
      pp, thCur.getValue(pp), thPrev.getValue(pp), gradThCur.getValue(pp), Dth, 0.0);
  };
  RealFunction kdcFgFn = [&](const Point& pp) -> Real {
    const Real r = keff * thCur.getValue(pp) * fgCur.getValue(pp);
    return crosswindK(
      pp, fgCur.getValue(pp), fgPrev.getValue(pp), gradFgCur.getValue(pp), Dfg, r);
  };
  RealFunction kdcFnFn = [&](const Point& pp) -> Real {
    const Real r = -keff * thCur.getValue(pp) * fgCur.getValue(pp);
    return crosswindK(
      pp, fnCur.getValue(pp), fnPrev.getValue(pp), gradFnCur.getValue(pp), Dfn, r);
  };
  RealFunction kdcWashFn = [&](const Point& pp) -> Real {
    return crosswindK(pp, washCur.getValue(pp), washPrev.getValue(pp),
      gradWashCur.getValue(pp), 0.0, 0.0);
  };

  // ---- Washout ---------------------------------------------------------------
  //
  // Replaces the Eulerian age equation dT/dt + u.grad T = 1, T = 0 at the inlet,
  // which is not a reportable quantity: on closed streamlines T grows without
  // bound, so a recirculation zone never reaches a steady state and the number
  // you read off is a property of how long you ran, not of the flow. This run
  // measured exactly that -- <T> climbing 0.11 s per cycle with no sign of a
  // plateau. Its initial condition T = 0 is fictional too, since real blood has
  // been flowing forever.
  //
  // The washout is the same machinery with a bounded answer:
  //
  //     dc/dt + u.grad c = 0,   c = 1 at t0,   c = 0 at the inlet.
  //
  // c is the surviving fraction of the original bolus. It obeys a maximum
  // principle -- 0 <= c <= 1 -- so it cannot run away, and what is reported is
  // the volume-weighted residual fraction R(t) = (1/V) int c dV and its decay
  // constant. Those converge and are comparable between geometries, which the
  // age field is not. Note the residence time never entered the source anyway:
  // the kinetics are armed by the wall-shear indices alone, as in Qureshi et al.
  // (2022), where the location of maximum ECAP is what nucleates coagulation.
  // It is a diagnostic, and this is a diagnostic that answers.
  const RealFunction zeroFunction = 0;

  // Plasma fibrinogen entering with fresh blood, in mol/m^3.
  const RealFunction fibrinogenInlet =
    cfg.thrombosis.fibrinogenSinusRhythm / cfg.thrombosis.fibrinogenMolarMass;

  const auto pW = Dot(uOld, Grad(vwash));

  washout = (1.0 / cfg.dt) * Integral(wash, vwash) -
    (1.0 / cfg.dt) * Integral(washCur, vwash) + Integral(Dot(uOld, Grad(wash)), vwash)

    + (1.0 / cfg.dt) * Integral(tauWashFn * wash, pW) -
    (1.0 / cfg.dt) * Integral(tauWashFn * washCur, pW) +
    Integral(tauWashFn * Dot(uOld, Grad(wash)), pW)

    // Codina crosswind
    + Integral(kdcWashFn * Grad(wash), Grad(vwash)) -
    Integral(kdcWashFn * invSpeedSqFn * Dot(uOld, Grad(wash)), Dot(uOld, Grad(vwash)))

    + DirichletBC(wash, zeroFunction).on(INLET);

  // ---- Coagulation kinetics ------------------------------------------------
  const auto pTh = Dot(uOld, Grad(vth));
  const auto pFg = Dot(uOld, Grad(vfg));
  const auto pFn = Dot(uOld, Grad(vfn));

  protein = (1.0 / cfg.dt) * Integral(th, vth) - (1.0 / cfg.dt) * Integral(thCur, vth) +
    Dth * Integral(Grad(th), Grad(vth)) + Integral(Dot(uOld, Grad(th)), vth)

    + (1.0 / cfg.dt) * Integral(fg, vfg) - (1.0 / cfg.dt) * Integral(fgCur, vfg) +
    Dfg * Integral(Grad(fg), Grad(vfg)) + Integral(Dot(uOld, Grad(fg)), vfg) +
    keff * Integral(thCur * fg, vfg)

    + (1.0 / cfg.dt) * Integral(fn, vfn) - (1.0 / cfg.dt) * Integral(fnCur, vfn) +
    Dfn * Integral(Grad(fn), Grad(vfn)) + Integral(Dot(uOld, Grad(fn)), vfn) -
    keff * Integral(thCur * fg, vfn)

    // Endothelial thrombin flux: a wall flux weighted by the activation field.
    - cfg.thrombosis.thrombinWallFlux * BoundaryIntegral(activation * vth).over(WALL)

    // SUPG/VMS, expanded. Only Fg has a reaction proportional to its own
    // unknown, so only Fg carries a reactive adjoint.
    + (1.0 / cfg.dt) * Integral(tauThFn * th, pTh) -
    (1.0 / cfg.dt) * Integral(tauThFn * thCur, pTh) +
    Integral(tauThFn * Dot(uOld, Grad(th)), pTh)

    + (1.0 / cfg.dt) * Integral(tauFgFn * fg, pFg) -
    (1.0 / cfg.dt) * Integral(tauFgFn * fgCur, pFg) +
    Integral(tauFgFn * Dot(uOld, Grad(fg)), pFg) +
    keff * Integral(tauFgFn * thCur * fg, pFg)

    + (keff / cfg.dt) * Integral(tauFgFn * fg, thCur * vfg) -
    (keff / cfg.dt) * Integral(tauFgFn * fgCur, thCur * vfg) +
    keff * Integral(tauFgFn * Dot(uOld, Grad(fg)), thCur * vfg) +
    (keff * keff) * Integral(tauFgFn * thCur * fg, thCur * vfg)

    // ---- Inflow conditions. THE reason thrombin, fibrinogen and fibrin were
    //      all piling up in a cone at the inlet.
    //
    // These are advection problems at cell Peclet 1.9e6 -- effectively pure
    // transport. A pure transport problem REQUIRES a Dirichlet condition on the
    // inflow boundary; without one the problem is ill posed there, and the
    // discrete symptom is precisely a spurious layer growing off the inlet
    // plane. It was also wrong physically: with a natural condition on every
    // boundary the domain is a closed box for the species, so wall thrombin can
    // never wash out and fibrinogen is never replenished once consumed.
    //
    // Fresh blood enters the segment, so: no thrombin, no fibrin, and
    // fibrinogen at its plasma level. The outlet keeps its natural condition,
    // which is the correct outflow condition for advection -- nothing is
    // imposed on what leaves.
    //
    // Note this is absent from the protein block of
    // CoronaryArtery_FSI_Explicit_P1P1_PETSc_Seq.cpp as well, but that block is
    // never called there (assembleProtein is discarded via (void)), so it had
    // never run and the omission had never shown up.
    // ---- Codina crosswind, one term pair per species --------------------
    //   k_dc [ grad c . grad v - (u.grad c)(u.grad v)/|u|^2 ]
    + Integral(kdcThFn * Grad(th), Grad(vth)) -
    Integral(kdcThFn * invSpeedSqFn * Dot(uOld, Grad(th)), Dot(uOld, Grad(vth)))

    + Integral(kdcFgFn * Grad(fg), Grad(vfg)) -
    Integral(kdcFgFn * invSpeedSqFn * Dot(uOld, Grad(fg)), Dot(uOld, Grad(vfg)))

    + Integral(kdcFnFn * Grad(fn), Grad(vfn)) -
    Integral(kdcFnFn * invSpeedSqFn * Dot(uOld, Grad(fn)), Dot(uOld, Grad(vfn)))

    + DirichletBC(th, zeroFunction).on(INLET) + DirichletBC(fn, zeroFunction).on(INLET) +
    DirichletBC(fg, fibrinogenInlet).on(INLET)

    + (1.0 / cfg.dt) * Integral(tauFnFn * fn, pFn) -
    (1.0 / cfg.dt) * Integral(tauFnFn * fnCur, pFn) +
    Integral(tauFnFn * Dot(uOld, Grad(fn)), pFn) -
    keff * Integral(tauFnFn * thCur * fg, pFn);

  // ---- Wall shear recovery, assigned once -----------------------------------
  {
    const auto& uSol = u.getSolution();
    const auto jacRow0 = VectorFunction(Component(Jacobian(uSol), 0, 0),
      Component(Jacobian(uSol), 0, 1), Component(Jacobian(uSol), 0, 2));
    const auto jacRow1 = VectorFunction(Component(Jacobian(uSol), 1, 0),
      Component(Jacobian(uSol), 1, 1), Component(Jacobian(uSol), 1, 2));
    const auto jacRow2 = VectorFunction(Component(Jacobian(uSol), 2, 0),
      Component(Jacobian(uSol), 2, 1), Component(Jacobian(uSol), 2, 2));

    gradRecProj0 = Integral(gradRecTrial0, gradRecTest) - Integral(jacRow0, gradRecTest);
    gradRecProj1 = Integral(gradRecTrial1, gradRecTest) - Integral(jacRow1, gradRecTest);
    gradRecProj2 = Integral(gradRecTrial2, gradRecTest) - Integral(jacRow2, gradRecTest);
  }

  {
    const auto symUw =
      0.5 * (Jacobian(u.getSolution()) + Transpose(Jacobian(u.getSolution())));
    const auto shearW =
      Sqrt(cy.gammaRegularization * cy.gammaRegularization + 2.0 * Dot(symUw, symUw));
    const auto muW = cy.muInf +
      deltaMu * Pow(1.0 + Pow(cy.lambda * shearW, cy.yasuda), (cy.n - 1.0) / cy.yasuda);

    const auto tractionVec =
      VectorFunction(muW * Dot(gradRecTrial0.getSolution(), normal),
        muW * Dot(gradRecTrial1.getSolution(), normal),
        muW * Dot(gradRecTrial2.getSolution(), normal));

    const auto wallStress = tractionVec - Dot(tractionVec, normal) * normal;
    const Real wssReg = 1.0e-3;

    wssProj = BoundaryIntegral(Dot(wssTrial, wssTest)).over(WALL) +
      wssReg * Integral(Dot(wssTrial, wssTest)) -
      BoundaryIntegral(Dot(wallStress, wssTest)).over(WALL);
  }

  const Real PI = std::numbers::pi_v<Real>;

  const int stepsPerCycle = static_cast<int>(cfg.period / cfg.dt + 0.5);
  const int totalCycles = cfg.flowCycles + cfg.speciesCycles;
  const int totalSteps = totalCycles * stepsPerCycle;
  // Total volume, computed once with the same contraction trick.
  Real domainVolume = 1.0;
  {
    washIntegral = Integral(oneGf, qWash);
    washIntegral.assemble();
    domainVolume = washIntegral(oneGf);
    Alert::Info() << "[washout] domain volume = " << domainVolume << " m^3"
                  << Alert::Raise;
  }
  const Real fg0 =
    cfg.thrombosis.fibrinogenSinusRhythm / cfg.thrombosis.fibrinogenMolarMass;

  const auto wallClockStart = std::chrono::steady_clock::now();
  Real costFlow = 0.0, costWss = 0.0, costRes = 0.0, costKin = 0.0;

  // ===========================================================================
  // One loop. The flow is solved every step, from the first to the last, and
  // the species switch on once the flow has had cfg.flowCycles to become
  // periodic.
  //
  // This replaces a two-phase scheme that solved the flow for a few cycles,
  // stored one cycle of u(t) in an array of PETSc Vecs, and then replayed it
  // while advancing only the species. That was cheaper -- the flow is about
  // three quarters of a step -- but it bought the speed with a storage layer
  // (VecDuplicate/VecCopy/VecDestroy over stepsPerCycle vectors) that appears
  // in no other example in this tree, and it made the velocity a recording
  // rather than a solution. Solving every step costs
  // (flowCycles + speciesCycles)/flowCycles times more and holds one velocity
  // field instead of stepsPerCycle of them, so it is also the smaller memory
  // footprint. Use -pt_mesh with the coarse mesh while iterating.
  //
  // The wall-shear indices are closed at every cycle boundary rather than once:
  // closeCycle() resets its own accumulators, so TAWSS/OSI/ECAP always describe
  // the cycle just finished, and the activation field that drives the wall
  // thrombin flux is refreshed with them.
  // ===========================================================================
  Alert::Info() << "[run] " << totalCycles << " cycles of " << stepsPerCycle << " steps ("
                << totalSteps << " total); flow every step, "
                << "species from cycle " << (cfg.flowCycles + 1) << " on" << Alert::Raise;
  if (cfg.flowCycles < 2)
    Alert::Warning() << "[run] fewer than two warm-up cycles: the wall-shear "
                     << "indices that arm the source carry the start-up "
                     << "transient" << Alert::Raise;

  Real t = 0.0;
  Real uSpeed = 0.0;      // max|u| of the current step: guard and progress line
  Real residual = 1.0;    // fraccion del bolo original que queda
  Real clearance = std::numeric_limits<Real>::infinity();
  bool armed = false;

  for (int step = 0; step < totalSteps; ++step)
  {
    t += cfg.dt;
    const int cycle = step / stepsPerCycle;
    const int k = step % stepsPerCycle;
    const bool endOfCycle = (k == stepsPerCycle - 1);
    const bool species = (cycle >= cfg.flowCycles);

    // ---- momentum, every step ---------------------------------------------
    {
      const auto t0 = std::chrono::steady_clock::now();

      pInValue = cfg.inletPressureMean +
        cfg.inletPressureAmplitude * std::sin(2.0 * PI * t / cfg.period);

      vmsL2Conv.assemble();
      vmsL2Conv.solve(vmsL2ConvKSP);
      vmsTauProj.assemble();
      vmsTauProj.solve(vmsTauKSP);
      vmsSubProj.assemble();
      vmsSubProj.solve(vmsSubKSP);
      vmsSqrtTauCProj.assemble();
      vmsSqrtTauCProj.solve(vmsSqrtTauCKSP);

      // tau_C as the exact pointwise square of the projected sqrt(tau_C),
      // following the P1/P1 coronary example.
      VecPointwiseMult(vmsTauC.getSolution().getData(),
        vmsSqrtTauC.getSolution().getData(), vmsSqrtTauC.getSolution().getData());

      vmsPiTildeProj.assemble();
      vmsPiTildeProj.solve(vmsPiTildeKSP);
      vmsTauPProj.assemble();
      vmsTauPProj.solve(vmsTauPKSP);

      flow.assemble();
      if (!flowSplitsSet)
      {
        flow.setFieldSplits();
        flowSplitsSet = true;
      }
      flow.solve(flowKSP);

      {
        ::KSPConvergedReason reason;
        PetscInt its = 0;
        KSPGetConvergedReason(flowKSP.getHandle(), &reason);
        KSPGetIterationNumber(flowKSP.getHandle(), &its);
        if (reason < 0)
          Alert::Warning() << "[flow] step " << step << " KSP DIVERGED ("
                           << static_cast<int>(reason) << ") after " << its << " its"
                           << Alert::Raise;
        else if (step == 0)
          Alert::Info() << "[chk] first flow solve ok, KSP its=" << its << Alert::Raise;
      }

      uOld.setData(u.getSolution().getData());
      vmsSubOld.setData(vmsSub.getSolution().getData());
      vmsSqrtTauCOld.setData(vmsSqrtTauC.getSolution().getData());

      // A direct solve always "succeeds", so a diverging *simulation* is
      // silent: MUMPS reports one iteration, the KSP reason is CONVERGED, and
      // the field grows without bound anyway. That is how the 11 kPa run
      // reached TAWSS = 1e79 before anyone noticed. Check the physics, not the
      // solver. Both signs, because max() returns the largest signed DOF, not
      // the largest magnitude, and a blow-up need not be positive.
      uSpeed = std::max(std::abs(uOld.max()), std::abs(uOld.min()));
      if (!std::isfinite(uSpeed) || uSpeed > cfg.maxVelocity)
      {
        Alert::Exception()
          << "[flow] diverged at step " << step << " (cycle " << (cycle + 1)
          << "): max|u| = " << uSpeed << " m/s exceeds maxVelocity = " << cfg.maxVelocity
          << " m/s at inletPressureMean = " << cfg.inletPressureMean
          << " Pa. Poiseuille for this geometry gives "
          << "v ~ 0.2 m/s at 140 Pa and scales linearly, so lower -pt_pmean "
          << "(or -pt_dt)." << Alert::Raise;
      }

      costFlow +=
        std::chrono::duration<Real>(std::chrono::steady_clock::now() - t0).count();
    }

    // ---- wall shear, every step; its cycle integrals close on the boundary --
    {
      const auto t0 = std::chrono::steady_clock::now();
      gradRecProj0.assemble();
      gradRecProj0.solve(gradRecKSP0);
      gradRecProj1.assemble();
      gradRecProj1.solve(gradRecKSP1);
      gradRecProj2.assemble();
      gradRecProj2.solve(gradRecKSP2);
      wssProj.assemble();
      wssProj.solve(wssKSP);
      wss.setData(wssTrial.getSolution().getData());
      indices.accumulate(wss, cfg.dt);
      costWss +=
        std::chrono::duration<Real>(std::chrono::steady_clock::now() - t0).count();
    }

    if (endOfCycle)
    {
      indices.closeCycle(cfg.thrombosis);
      activationWeight(indices, cfg.thrombosis, activation);
      armed = true;
      Alert::Info() << "[cycle " << (cycle + 1) << "/" << totalCycles
                    << "] maxTAWSS=" << indices.tawss().max()
                    << " Pa  maxOSI=" << indices.osi().max()
                    << "  maxECAP=" << indices.maxECAP() << Alert::Raise;
    }

    // ---- species, once the flow has had its warm-up ------------------------
    if (species && armed)
    {
      if (cfg.solveWashout)
      {
        const auto t0 = std::chrono::steady_clock::now();
        washout.assemble();
        washout.solve(washoutKSP);
        washPrev.setData(washCur.getData());
        washCur.setData(wash.getSolution().getData());
        costRes +=
          std::chrono::duration<Real>(std::chrono::steady_clock::now() - t0).count();
      }

      if (cfg.solveKinetics)
      {
        const auto t0 = std::chrono::steady_clock::now();
        protein.assemble();
        protein.solve(proteinKSP);
        // History rotates BEFORE the current level is overwritten: the
        // crosswind residual needs both c^n and c^{n-1}.
        thPrev.setData(thCur.getData());
        fgPrev.setData(fgCur.getData());
        fnPrev.setData(fnCur.getData());
        thCur.setData(th.getSolution().getData());
        fgCur.setData(fg.getSolution().getData());
        fnCur.setData(fn.getSolution().getData());
        costKin +=
          std::chrono::duration<Real>(std::chrono::steady_clock::now() - t0).count();
      }

      // Residual fraction R = (1/V) int c dV: the share of the original bolus
      // still in the domain. Volume weighted, not a DOF average, so it is not
      // biased by where the mesh happens to be fine.
      const Real prevResidual = residual;
      washIntegral = Integral(washCur, qWash);
      washIntegral.assemble();
      residual = washIntegral(oneGf) / domainVolume;

      // Instantaneous clearance constant tau = -R / (dR/dt). For a well mixed
      // volume R decays exponentially and tau is its time constant; a trapped
      // pocket shows up as tau growing without bound as R stops falling.
      const Real drdt = (residual - prevResidual) / cfg.dt;
      clearance =
        (drdt < -1e-12) ? -residual / drdt : std::numeric_limits<Real>::infinity();
    }

    csv << t << ',' << cycle << ',' << pInValue << ',' << residual << ',' << clearance
        << ',' << indices.tawss().max() << ',' << indices.osi().max() << ','
        << indices.ecap().max() << ',' << thCur.max() << ',' << fgCur.min() << ','
        << fnCur.max() << ',' << (fnCur.max() / fg0) << '\n';
    csv.flush();

    if (endOfCycle)
      xdmf.write(t).flush();

    if (step < 3 || (step + 1) % 10 == 0)
    {
      const Real el =
        std::chrono::duration<Real>(std::chrono::steady_clock::now() - wallClockStart)
          .count();
      const Real per = el / static_cast<Real>(step + 1);

      // One Alert, one Raise. Each Alert::Info() is a distinct object, so
      // chaining several does not concatenate -- build the variable tail first.
      std::ostringstream tail;
      if (species)
        tail << "  |  washout R=" << residual << " tau=" << clearance
             << " s  Fn/Fg0=" << (fnCur.max() / fg0);
      else
        tail << "  |  (warm-up)";

      Alert::Info() << "[step " << (step + 1) << "/" << totalSteps << "] cycle "
                    << (cycle + 1) << "/" << totalCycles << "  t=" << t << " s"
                    << "  max|u|=" << uSpeed << " m/s"
                    << "  " << per << " s/step"
                    << "  ETA " << (per * (totalSteps - step - 1) / 60.0) << " min"
                    << tail.str() << Alert::Raise;
      std::cout.flush();
    }
  }

  Alert::Info() << "[run] done.  flow=" << costFlow << " s  wss=" << costWss
                << " s  washout=" << costRes << " s  kinetics=" << costKin << " s"
                << Alert::Raise;

  csv.close();
  xdmf.close();

  PetscFinalize();
  return 0;
}
