/*
 *          Copyright Carlos BRITO PACHECO 2021 - 2025.
 * Distributed under the Boost Software License, Version 1.0.
 *       (See accompanying file LICENSE or copy at
 *          https://www.boost.org/LICENSE_1_0.txt)
 */
/**
 * @file Flow.h
 * @brief Flow map operators for shape functions and grid functions.
 *
 * This file defines the Flow class, which implements the flow map (push-forward)
 * of functions along a vector field. Flow maps are used in advection problems,
 * level set methods, and semi-Lagrangian time integration schemes.
 *
 * ## Mathematical Foundation
 * Given a velocity field @f$ \mathbf{v}(x,t) @f$, the flow map @f$ \Phi_t @f$
 * satisfies:
 * @f[
 *   \frac{d\Phi}{dt}(x,t) = \mathbf{v}(\Phi(x,t), t), \quad \Phi(x,0) = x
 * @f]
 *
 * The flow operator computes @f$ u(\Phi(x,t)) @f$, which represents the value
 * of function @f$ u @f$ advected along the flow.
 *
 * ## Applications
 * - **Advection-diffusion**: @f$ \frac{\partial u}{\partial t} + \mathbf{v} \cdot \nabla u = f @f$
 * - **Semi-Lagrangian methods**: Characteristic tracking for transport equations
 * - **Level set methods**: Interface evolution and tracking
 * - **ALE formulations**: Arbitrary Lagrangian-Eulerian methods
 */
#ifndef RODIN_VARIATIONAL_FLOW_H
#define RODIN_VARIATIONAL_FLOW_H

#include "ForwardDecls.h"

#include "Rodin/FormLanguage/Traits.h"
#include "Rodin/Geometry/Mesh.h"
#include "Rodin/Geometry/Point.h"
#include "Rodin/Geometry/Region.h"

#include "Rodin/Math/SpatialVector.h"
#include "Rodin/Math/Vector.h"
#include "Rodin/Math/RungeKutta/RK4.h"

#include "Rodin/QF/GenericPolytopeQuadrature.h"
#include "Rodin/Variational/ShapeFunction.h"

#include "Rodin/QF/QuadratureFormula.h"

namespace Rodin::FormLanguage
{
  template <
    class Derived,
    class FES,
    class VectorField,
    class Step,
    class BoundaryPolicy,
    class TangentPolicy
  >
  struct Traits<
    Variational::Flow<
      Variational::ShapeFunctionBase<Derived, FES, Variational::TestSpace>,
      VectorField, Step, BoundaryPolicy, TangentPolicy>>
  {
    using FESType = FES;
    static constexpr Variational::ShapeFunctionSpaceType SpaceType = Variational::TestSpace;

    using OperandType =
      Variational::ShapeFunctionBase<Derived, FES, Variational::TestSpace>;
  };
}

namespace Rodin::Variational
{
  struct BoundaryHit
  {
    Real& tau; ///< Time remaining until end of step
    Index& cell; ///< Cell index where boundary was hit
    Math::SpatialPoint& rref; ///< Reference coordinates where boundary was hit
    size_t face; ///< Local face index where boundary was hit
  };

  /**
   * @brief Default boundary policy for flow maps.
   *
   * This policy does not enforce any special treatment at domain boundaries.
   * Flow integration continues unmodified when approaching boundaries.
   */
  class DefaultBoundaryPolicy
  {
    public:
      /**
       * @brief Called when flow reaches a boundary.
       * @returns false (no special boundary treatment)
       */
      constexpr
      bool operator()(const BoundaryHit&) const
      {
        return false;
      }
  };

  /**
   * @brief Default tangent policy for flow maps.
   *
   * This policy allows tangent vectors to be computed at all points.
   */
  class DefaultTangentPolicy
  {
    public:
      /**
       * @brief Called to determine if tangent computation is allowed.
       * @returns true (always allow tangent computation)
       */
      constexpr
      bool operator()(const BoundaryHit&) const
      {
        return true;
      }
  };

  /**
   * @ingroup RodinVariational
   * @brief Flow map operator for functions.
   *
   * Computes the composition of a function with the flow map generated by a
   * vector field. Given a function @f$ u @f$ and velocity field @f$ \mathbf{v} @f$,
   * this computes @f$ u \circ \Phi @f$ where @f$ \Phi @f$ is the flow map.
   *
   * @tparam Derived Type of the function being advected
   * @tparam VectorField Type of the velocity field
   * @tparam Step Time step for flow integration
   * @tparam BoundaryPolicy Policy for handling domain boundaries
   * @tparam TangentPolicy Policy for tangent vector computation
   */
  template <
    class Derived,
    class VectorField,
    class Step,
    class BoundaryPolicy,
    class TangentPolicy>
  class Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy, TangentPolicy>
    : public FunctionBase<Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy, TangentPolicy>>
  {
    public:
      /// @brief Type of the operand function
      using Operand =
        FunctionBase<Derived>;

      using VectorFieldType =
        VectorField;

      using StepType =
        Step;

      using BoundaryPolicyType =
        BoundaryPolicy;

      using TangentPolicyType =
        TangentPolicy;

      using Parent =
        FunctionBase<Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy, TangentPolicy>>;

      class Trace
      {
        public:
          Trace(bool exited, Real time, const Geometry::Point& p)
            : m_exited(exited), m_time(time), m_point(p)
          {}

          Real getTime() const
          {
            return m_time;
          }

          const Geometry::Point& getPoint() const
          {
            return m_point;
          }

          bool exited() const
          {
            return m_exited;
          }

        private:
          bool m_exited;
          Real m_time;
          Geometry::Point m_point;
      };

      template <
        class VVel,
        class S = StepType,
        class B = BoundaryPolicy, class T = TangentPolicy>
      Flow(const Real& t,
           const Operand& u,
           VVel&& vel,
           S&& st=S{}, B&& bp=B{}, T&& tp=T{})
        : m_maxZeroHops(128),
          m_maxBisectionIterations(16),
          m_maxSubdivisionIterations(8),
          m_t(t),
          m_operand(u.copy()),
          m_velocity(std::forward<VVel>(vel)),
          m_step(std::forward<S>(st)),
          m_bp(std::forward<B>(bp)),
          m_tp(std::forward<T>(tp)),
          m_p(nullptr)
      {}

      Flow(const Flow& other)
        : Parent(other),
          m_maxZeroHops(other.m_maxZeroHops),
          m_maxBisectionIterations(other.m_maxBisectionIterations),
          m_maxSubdivisionIterations(other.m_maxSubdivisionIterations),
          m_t(other.m_t),
          m_operand(other.m_operand->copy()),
          m_velocity(other.m_velocity),
          m_step(other.m_step),
          m_bp(other.m_bp),
          m_tp(other.m_tp),
          m_p(other.m_p)
      {}

      Flow(Flow&& other)
        : Parent(std::move(other)),
          m_maxZeroHops(std::move(other.m_maxZeroHops)),
          m_maxBisectionIterations(std::move(other.m_maxBisectionIterations)),
          m_maxSubdivisionIterations(std::move(other.m_maxSubdivisionIterations)),
          m_t(std::move(other.m_t)),
          m_operand(std::move(other.m_operand)),
          m_velocity(std::move(other.m_velocity)),
          m_step(std::move(other.m_step)),
          m_bp(std::move(other.m_bp)),
          m_tp(std::move(other.m_tp)),
          m_p(std::exchange(other.m_p, nullptr))
      {}

      Trace trace(const Geometry::Point& p) const
      {
        // Robust affine/P1 tracer (production-oriented):
        // - physical oriented face planes per cell (built from fixed anchor + fixed face points)
        // - event bracketing on "reached band" (sd <= eps_hit)
        // - deterministic active-set selection with SOFT hysteresis
        // - chained zero-hop across edges/vertices with same rule
        //
        // Assumptions:
        // - cell maps are affine (P1 geometry) so J^{-1} is constant per cell.
        // - face ordering contract: hs.row(j) corresponds to faces[j] (per getSubPolytopes order).

        struct Plane
        {
          Math::SpatialVector<Real> n_u;   // unnormalized physical normal (J^{-T} nref_col)
          Math::SpatialVector<Real> nref;  // PATCH: store as COLUMN reference normal (consistent dot(vref,nref))
          Real c_u;                        // plane constant: sd_u(x) = c_u - n_u·x
          Real nn;                         // ||n_u||
          Index fid;                       // global face id
          bool ok;                         // nn finite and >0
        };

        struct Cand
        {
          size_t j;        // local face index
          Real   sd;       // signed distance (physical) to oriented plane
          Real   ndv;      // vref · nref (reference space)
          Index  fid;      // global face id
          bool   is_last;  // whether j == last_face
        };

        enum class PickMode { Strict, NdvPos, Overshot };

        const size_t ZERO_HOPS_MAX = m_maxZeroHops;
        const int    MAX_BISECT    = static_cast<int>(m_maxBisectionIterations);
        const int    MAX_SUBDIV    = static_cast<int>(m_maxSubdivisionIterations);

        const auto& poly0 = p.getPolytope();
        const auto& mesh  = poly0.getMesh();
        const size_t cd   = mesh.getDimension();
        const auto& conn  = mesh.getConnectivity();

        Real tau = std::abs(m_t);
        const Real sgn = Math::sgn(m_t);

        // Scratch
        Index s_cell = Index(-1);

        Math::SpatialPoint s_rc{{}}, s_rc1{{}}, s_rc_tmp{{}}, s_r_eval{{}}, s_r_in{{}};
        Math::SpatialPoint s_pc{{}}, s_x{{}}, s_x_eval{{}}, s_x_in{{}}, s_x_face{{}};

        std::vector<Plane> planes; planes.reserve(16);
        std::vector<Cand>  cand;   cand.reserve(16);

        const Real eps_machine = std::numeric_limits<Real>::epsilon();
        const Real sqrt_eps    = std::sqrt(eps_machine);
        const Real v_floor     = std::numeric_limits<Real>::min();

        auto dot = [](const auto& a, const auto& b) -> Real { return a.dot(b); };
        auto is_finite = [](Real v) -> bool { return std::isfinite(v); };

        // PATCH: single, consistent norm2 helper to avoid type/shape drift.
        auto norm2 = [&](const auto& v) -> Real
        {
          const Real v2 = dot(v, v);
          return std::max<Real>(Real(0), v2);
        };

        // PATCH: normalize “velocity type” once.
        // If m_velocity(qp) already returns a vector-like type, keep this.
        // If it returns a (dim x 1) matrix, use .col(0) here and nowhere else.
        auto vphys_of = [&](const Geometry::Point& qp) -> Math::SpatialVector<Real>
        {
          // ----- choose ONE, matching your m_velocity return type -----
          // return m_velocity(qp);          // vector-like
          return m_velocity(qp).col(0);      // matrix-like (dim x 1)
        };

        // ---------------------------------------------------------------------------
        // Locate starting cell / reference coords (handles starting on a face)
        // ---------------------------------------------------------------------------
        if (poly0.getDimension() == cd)
        {
          s_cell = poly0.getIndex();
          s_rc   = p.getReferenceCoordinates();
        }
        else if (poly0.getDimension() == cd - 1)
        {
          const Index f = poly0.getIndex();
          const auto& adj = conn.getIncidence(cd - 1, cd).at(f);

          if (mesh.isBoundary(f))
          {
            assert(!adj.empty());
            const Index c = adj[0];
            mesh.getPolytopeTransformation(cd, c).inverse(s_rc_tmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c)).cell(s_rc, s_rc_tmp);
            s_cell = c;
          }
          else
          {
            assert(adj.size() >= 2);
            const Index c0 = adj[0];
            const Index c1 = adj[1];

            // Project into both adjacent cells (affine => robust)
            mesh.getPolytopeTransformation(cd, c0).inverse(s_rc_tmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c0)).cell(s_rc1, s_rc_tmp);
            const Math::SpatialPoint rc0 = s_rc1;

            mesh.getPolytopeTransformation(cd, c1).inverse(s_rc_tmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c1)).cell(s_rc1, s_rc_tmp);
            const Math::SpatialPoint rc1 = s_rc1;

            // Identify local face index of f in c0
            const auto& faces0 = conn.getIncidence(cd, cd - 1).at(c0);
            size_t j0 = faces0.size();
            for (size_t k = 0; k < faces0.size(); ++k)
              if (faces0[k] == f) { j0 = k; break; }
            assert(j0 < faces0.size());

            // Outward reference normal for that face in ref(c0)
            const auto g0 = mesh.getGeometry(cd, c0);
            const auto& hs0 = Geometry::Polytope::Traits(g0).getHalfSpace();
            // PATCH: column normal (consistent with later code)
            const Math::SpatialVector<Real> nref0 = hs0.matrix.row(j0).transpose();

            const auto it0 = mesh.getPolytope(cd, c0);
            const auto& cell0 = *it0;
            const Geometry::Point q0(cell0, rc0, p.getPhysicalCoordinates());
            const auto vref0 = (sgn * q0.getJacobianInverse() * vphys_of(q0));

            // Fallback: if ambiguous, pick side where projected point is "more interior"
            auto interior_score = [&](Index c, const Math::SpatialPoint& rproj) -> Real
            {
              const auto gc = mesh.getGeometry(cd, c);
              const auto& hsc = Geometry::Polytope::Traits(gc).getHalfSpace();
              Real s = std::numeric_limits<Real>::infinity();
              for (int j = 0; j < hsc.vector.size(); ++j)
              {
                const auto n = hsc.matrix.row(j);
                const Real b = hsc.vector[j];
                s = std::min(s, b - rproj.dot(n));
              }
              return s;
            };

            const Real ndv = dot(nref0, vref0);
            if (std::abs(ndv) <= Real(10) * sqrt_eps)
            {
              const Real s0 = interior_score(c0, rc0);
              const Real s1 = interior_score(c1, rc1);
              if (s1 > s0) { s_cell = c1; s_rc = rc1; }
              else         { s_cell = c0; s_rc = rc0; }
            }
            else if (ndv > 0)
            {
              s_cell = c1;
              s_rc   = rc1;
            }
            else
            {
              s_cell = c0;
              s_rc   = rc0;
            }
          }
        }
        else
        {
          assert(false);
          return Trace{ true, 0, p };
        }

        // Resize buffers once (invariants)
        s_rc1.resize(s_rc.size());
        s_rc_tmp.resize(s_rc.size());
        s_r_eval.resize(s_rc.size());
        s_r_in.resize(s_rc.size());

        s_pc.resize(p.getPhysicalCoordinates().size());
        s_x.resize(s_pc.size());
        s_x_eval.resize(s_pc.size());
        s_x_in.resize(s_pc.size());
        s_x_face.resize(s_pc.size());

        Optional<size_t> last_face;

        // ---------------------------------------------------------------------------
        // Main tracing loop
        // ---------------------------------------------------------------------------
        while (tau > 0)
        {
          const auto itc = mesh.getPolytope(cd, s_cell);
          const auto& cell = *itc;

          const auto g = mesh.getGeometry(cd, s_cell);
          const auto& faces = conn.getIncidence(cd, cd - 1).at(s_cell);
          const auto& hs = Geometry::Polytope::Traits(g).getHalfSpace();

          // Hard invariants
          assert(static_cast<size_t>(hs.matrix.rows()) == faces.size());
          assert(static_cast<size_t>(hs.vector.size()) == faces.size());

          auto phi_face = [&](size_t j, const Math::SpatialPoint& r) -> Real
          {
            const auto n = hs.matrix.row(j);
            const Real b = hs.vector[j];
            return b - r.dot(n); // interior => > 0
          };

          auto vref = [&](const Math::SpatialPoint& r) -> Math::SpatialVector<Real>
          {
            const Geometry::Point qp(cell, r);
            return (sgn * qp.getJacobianInverse() * vphys_of(qp));
          };

          auto advance = [&](Math::SpatialPoint& rout, Real dt, const Math::SpatialPoint& rin)
          {
            m_step.step(rout, dt, rin,
              [&](const Math::SpatialPoint& rr) -> Math::SpatialVector<Real>
              {
                return vref(rr);
              });
          };

          auto x_of = [&](Math::SpatialPoint& xout, const Math::SpatialPoint& r)
          {
            mesh.getPolytopeTransformation(cd, s_cell).transform(xout, r);
          };

          // Interior anchor in reference (Traits uses [0,1]^d conventions)
          {
            const auto rcent = Geometry::Polytope::Traits(g).getCentroid();
            assert(static_cast<size_t>(rcent.size()) == cd);
            s_r_in = rcent;
            x_of(s_x_in, s_r_in);
          }

          // Current physical point
          x_of(s_x, s_rc);

          // Build oriented physical planes, indexed EXACTLY by local face index j.
          planes.clear();
          planes.resize(faces.size());

          const Geometry::Point qJ(cell, s_r_in, s_x_in);
          const auto Jinv  = qJ.getJacobianInverse();
          const auto JinvT = Jinv.transpose();

          for (size_t j = 0; j < faces.size(); ++j)
          {
            Plane pl;
            pl.fid  = faces[j];

            // PATCH: column reference normal (no row-expression ambiguity / transpose gymnastics).
            pl.nref = hs.matrix.row(j).transpose();

            pl.n_u = JinvT * pl.nref;

            const Real nn2 = norm2(pl.n_u);
            pl.nn = std::sqrt(nn2);
            pl.ok = (pl.nn > Real(0)) && is_finite(pl.nn);

            // Define c_u from a fixed point on the face: Project(face)(anchor).
            Geometry::Polytope::Project(g).face(j, s_rc_tmp, s_r_in);

#ifndef NDEBUG
            // Scale-aware smoke test: phi(face_j) ~ 0 at projected point.
            const Real ph = phi_face(j, s_rc_tmp);
            const auto nrow = hs.matrix.row(j);
            const Real nrm  = std::sqrt(std::max<Real>(0, dot(nrow, nrow)));
            const Real rrm  = std::sqrt(std::max<Real>(0, dot(s_rc_tmp, s_rc_tmp)));
            const Real scale = Real(1) + std::abs(hs.vector[j]) + nrm * rrm;
            const Real tol = Real(1e3) * sqrt_eps * scale;
            assert(std::abs(ph) <= tol);
#endif

            x_of(s_x_face, s_rc_tmp);
            pl.c_u = dot(pl.n_u, s_x_face);

            // PATCH: robust orientation (only flip when clearly negative).
            // Avoid arbitrary flips when sd_in ~ 0 due to noise/slivers/tangency.
            const Real sd_in  = pl.c_u - dot(pl.n_u, s_x_in);
            const Real tol_in = Real(10) * sqrt_eps * std::max<Real>(Real(1), std::abs(pl.c_u));
            if (sd_in < -tol_in)
            {
              pl.n_u = -pl.n_u;
              pl.c_u = -pl.c_u;
            }
            // else keep as-is

            planes[j] = pl;
          }

          auto sd_u_at = [&](const Plane& pl, const Math::SpatialPoint& x) -> Real
          {
            return pl.c_u - dot(pl.n_u, x);
          };

          auto sd_at = [&](const Plane& pl, const Math::SpatialPoint& x) -> Real
          {
            if (!pl.ok) return std::numeric_limits<Real>::infinity();
            return sd_u_at(pl, x) / pl.nn; // signed distance in physical units
          };

          // Geometry scale from interior anchor distances (stable near boundaries)
          Real h_scale = Real(0);
          for (size_t j = 0; j < planes.size(); ++j)
          {
            const Plane& pl = planes[j];
            if (!pl.ok) continue;
            const Real d = sd_at(pl, s_x_in);
            if (is_finite(d)) h_scale = std::max(h_scale, d);
          }
          if (!(h_scale > Real(0)) || !is_finite(h_scale))
          {
            // Degenerate geometry: stop safely
            return Trace{ false, tau, Geometry::Point(*itc, s_rc) };
          }

          // Tolerances
          constexpr Real C_HIT = Real(100);
          constexpr Real C_NDV = Real(50);
          constexpr Real C_SUB = Real(0.25); // dt_stop <= C_SUB * tau

          const Real eps_hit_phys = C_HIT * sqrt_eps * h_scale;

          const auto v0 = vref(s_rc);
          const Real vref_mag = std::sqrt(norm2(v0));
          const Real eps_ndv = C_NDV * sqrt_eps * (Real(1) + vref_mag);

          // PATCH: dt_stop sanitization against NaN/Inf (and >0 guarantee)
          Real vphys_mag = Real(0);
          {
            const Geometry::Point qp(cell, s_rc, s_x);
            const auto vphys = vphys_of(qp);
            vphys_mag = std::sqrt(norm2(vphys));
            if (!is_finite(vphys_mag)) vphys_mag = Real(0);
          }

          Real dt_geom = eps_hit_phys / std::max<Real>(vphys_mag, v_floor);
          if (!is_finite(dt_geom) || !(dt_geom > Real(0)))
            dt_geom = C_SUB * tau;

          Real dt_stop = std::min(C_SUB * tau, dt_geom);
          if (!is_finite(dt_stop) || !(dt_stop > Real(0)))
            dt_stop = C_SUB * tau;

          // Predicate: reached band (or overshot) at time dt
          auto reached = [&](Real dt) -> bool
          {
            advance(s_r_eval, dt, s_rc);
            x_of(s_x_eval, s_r_eval);

            for (size_t j = 0; j < planes.size(); ++j)
            {
              const Plane& pl = planes[j];
              if (!pl.ok) continue;
              const Real d = sd_at(pl, s_x_eval);
              if (!is_finite(d)) continue;
              if (d <= eps_hit_phys) return true;
            }
            return false;
          };

          // Build candidates at (r_hit, x_hit) using signed distance band + SOFT hysteresis
          auto build_candidates_at = [&](const Math::SpatialPoint& r_hit,
                                         const Math::SpatialPoint& x_hit,
                                         std::vector<Cand>& out)
          {
            out.clear();
            out.reserve(planes.size());

            const auto vr = vref(r_hit);

            bool have_non_last = false;
            for (size_t j = 0; j < planes.size(); ++j)
            {
              const Plane& pl = planes[j];
              if (!pl.ok) continue;

              const Real sd = sd_at(pl, x_hit);
              if (!is_finite(sd)) continue;
              if (!(sd <= eps_hit_phys)) continue;  // active band, signed

              const Real ndv = dot(vr, pl.nref);
              const bool is_last = (last_face && j == *last_face);
              if (!is_last) have_non_last = true;

              out.push_back(Cand{ j, sd, ndv, pl.fid, is_last });
            }

            // PATCH (soft hysteresis): drop last-face only if there is an alternative
            if (have_non_last)
            {
              size_t w = 0;
              for (size_t k = 0; k < out.size(); ++k)
                if (!out[k].is_last) out[w++] = out[k];
              out.resize(w);
            }
          };

          // Deterministic selection with fallbacks + mode
          auto pick_best_exit = [&](const std::vector<Cand>& in, size_t& jhit, PickMode& mode) -> bool
          {
            auto key = [](const Cand& c)
            {
              return std::tuple<Real, Real, Index>(c.sd, -c.ndv, c.fid);
            };

            bool have = false;
            Cand best{0,0,0,0,false};

            // Strict: ndv > eps_ndv
            for (const auto& c : in)
            {
              if (!(c.ndv > eps_ndv)) continue;
              if (!have) { best = c; have = true; continue; }
              if (key(c) < key(best)) best = c;
            }
            if (have) { jhit = best.j; mode = PickMode::Strict; return true; }

            // Fallback 1: ndv > 0
            have = false;
            for (const auto& c : in)
            {
              if (!(c.ndv > Real(0))) continue;
              if (!have) { best = c; have = true; continue; }
              if (key(c) < key(best)) best = c;
            }
            if (have) { jhit = best.j; mode = PickMode::NdvPos; return true; }

            // Fallback 2: overshot (sd < 0), choose most negative sd then fid
            have = false;
            for (const auto& c : in)
            {
              if (!(c.sd < Real(0))) continue;
              if (!have) { best = c; have = true; continue; }
              if (std::tuple<Real,Index>(c.sd,c.fid) < std::tuple<Real,Index>(best.sd,best.fid))
                best = c;
            }
            if (have) { jhit = best.j; mode = PickMode::Overshot; return true; }

            return false;
          };

          // Event finder: bracket earliest dt where reached(dt) becomes true
          auto find_event = [&](Real dt_max, Real& thit, size_t& jhit, PickMode& mode) -> bool
          {
            if (!(dt_max > Real(0))) return false;
            if (!reached(dt_max))    return false;

            Real lo = Real(0);
            Real hi = dt_max;

            for (int s = 0; s < MAX_SUBDIV; ++s)
            {
              if (hi - lo <= dt_stop) break;
              const Real mid = Real(0.5) * (lo + hi);
              if (reached(mid)) hi = mid;
              else             lo = mid;
            }

            for (int it = 0; it < MAX_BISECT; ++it)
            {
              if (hi - lo <= dt_stop) break;
              const Real mid = Real(0.5) * (lo + hi);
              if (reached(mid)) hi = mid;
              else             lo = mid;
            }

            // PATCH: non-monotone reached guard.
            // If reached(lo) became true due to noise, do NOT abort hard; be conservative:
            // use thit = lo (or 0) and try to select a face at that state.
            if (lo > Real(0) && reached(lo))
              thit = lo;
            else
              thit = hi;

            // Recompute state at thit (reached() overwrote scratch)
            advance(s_r_eval, thit, s_rc);
            x_of(s_x_eval, s_r_eval);

            // PATCH: defensive “reached(thit)” check on the recomputed state
            bool ok_reach = false;
            for (size_t j = 0; j < planes.size(); ++j)
            {
              const Plane& pl = planes[j];
              if (!pl.ok) continue;
              const Real d = sd_at(pl, s_x_eval);
              if (is_finite(d) && d <= eps_hit_phys) { ok_reach = true; break; }
            }
            if (!ok_reach) return false;

            build_candidates_at(s_r_eval, s_x_eval, cand);
            if (cand.empty()) return false;
            if (!pick_best_exit(cand, jhit, mode)) return false;

            // PATCH: mode-aware validation (selection/validation must agree)
            {
              const Plane& pl = planes[jhit];
              if (!pl.ok) return false;

              const Real d = sd_at(pl, s_x_eval);
              if (!is_finite(d) || !(d <= eps_hit_phys)) return false;

              const auto vr = vref(s_r_eval);
              const Real ndv = dot(vr, pl.nref);
              if (!is_finite(ndv)) return false;

              switch (mode)
              {
                case PickMode::Strict:
                  if (!(ndv > eps_ndv)) return false;
                  break;
                case PickMode::NdvPos:
                  if (!(ndv > Real(0))) return false;
                  break;
                case PickMode::Overshot:
                  // accept only if “meaningfully overshot”, and allow slight negative ndv
                  if (!(d < -Real(0.1) * eps_hit_phys)) return false;
                  if (!(ndv >= -eps_ndv)) return false;
                  break;
              }
            }

            return true;
          };

          // -------------------------------------------------------------------------
          // One step: event or no-event
          // -------------------------------------------------------------------------
          Real thit = 0;
          size_t jhit = 0;
          PickMode mode = PickMode::Strict;

          const bool have_event = find_event(tau, thit, jhit, mode);

          if (!have_event)
          {
            // Advance full tau
            advance(s_rc1, tau, s_rc);
            s_rc = s_rc1;

            // Drift clamp only if slightly outside (physical)
            x_of(s_x, s_rc);
            bool outside = false;
            for (size_t j = 0; j < planes.size(); ++j)
            {
              const Plane& pl = planes[j];
              if (!pl.ok) continue;
              const Real d = sd_at(pl, s_x);
              if (is_finite(d) && d < Real(0)) { outside = true; break; }
            }
            if (outside)
            {
              Geometry::Polytope::Project(g).cell(s_rc1, s_rc);
              s_rc = s_rc1;
            }

            tau = Real(0);
            break;
          }

          // Advance to event and project onto hit face (reference)
          if (!(thit >= Real(0)) || !(thit <= tau) || !is_finite(thit))
          {
            Geometry::Polytope::Project(g).cell(s_rc1, s_rc);
            s_rc = s_rc1;
            break;
          }

          advance(s_rc1, thit, s_rc);
          Geometry::Polytope::Project(g).face(jhit, s_rc, s_rc1);
          s_rc = s_rc1;
          tau -= thit;

          // Micro inside clamp to kill jitter
          Geometry::Polytope::Project(g).cell(s_rc1, s_rc);
          s_rc = s_rc1;

          const Index face_hit = faces[jhit];

          // Physical point at face
          x_of(s_pc, s_rc);

          // -------------------------------------------------------------------------
          // Boundary vs interior hop
          // -------------------------------------------------------------------------
          if (mesh.isBoundary(face_hit))
          {
            if (!m_bp(BoundaryHit{tau, s_cell, s_rc, jhit}))
              return Trace{ true, tau, Geometry::Point(*itc, s_rc) };

            last_face.reset();
            continue;
          }

          // Interior hop across face_hit
          {
            const auto& nbrs = conn.getIncidence(cd - 1, cd).at(face_hit);
            assert(nbrs.size() == 2);
            s_cell = (nbrs[0] == s_cell) ? nbrs[1] : nbrs[0];
          }

          // Map same physical point into new cell and clamp
          mesh.getPolytopeTransformation(cd, s_cell).inverse(s_rc, s_pc);
          Geometry::Polytope::Project(mesh.getGeometry(cd, s_cell)).cell(s_rc1, s_rc);
          s_rc = s_rc1;

          // Update hysteresis local face index in new cell
          {
            const auto& faces_new = conn.getIncidence(cd, cd - 1).at(s_cell);
            last_face.reset();
            for (size_t j = 0; j < faces_new.size(); ++j)
              if (faces_new[j] == face_hit) { last_face = j; break; }
          }

          // -------------------------------------------------------------------------
          // Zero-hop chain (edge/vertex): repeat face selection at dt=0
          // -------------------------------------------------------------------------
          size_t zero_hops = 0;
          while (zero_hops++ < ZERO_HOPS_MAX)
          {
            const auto itz = mesh.getPolytope(cd, s_cell);
            const auto& cellz = *itz;

            const auto gz = mesh.getGeometry(cd, s_cell);
            const auto& facesz = conn.getIncidence(cd, cd - 1).at(s_cell);
            const auto& hsz = Geometry::Polytope::Traits(gz).getHalfSpace();

            assert(static_cast<size_t>(hsz.matrix.rows()) == facesz.size());
            assert(static_cast<size_t>(hsz.vector.size()) == facesz.size());

            auto phi_face_z = [&](size_t j, const Math::SpatialPoint& r) -> Real
            {
              const auto n = hsz.matrix.row(j);
              const Real b = hsz.vector[j];
              return b - r.dot(n);
            };

            auto vrefz = [&](const Math::SpatialPoint& r) -> Math::SpatialVector<Real>
            {
              const Geometry::Point qp(cellz, r);
              return (sgn * qp.getJacobianInverse() * vphys_of(qp));
            };

            auto x_of_z = [&](Math::SpatialPoint& xout, const Math::SpatialPoint& r)
            {
              mesh.getPolytopeTransformation(cd, s_cell).transform(xout, r);
            };

            // Build planes for this cell (same indexing)
            x_of_z(s_x, s_rc);

            const auto rcent = Geometry::Polytope::Traits(gz).getCentroid();
            assert(static_cast<size_t>(rcent.size()) == cd);
            s_r_in = rcent;
            x_of_z(s_x_in, s_r_in);

            planes.clear();
            planes.resize(facesz.size());

            const Geometry::Point qJz(cellz, s_r_in, s_x_in);
            const auto Jinvz  = qJz.getJacobianInverse();
            const auto JinvTz = Jinvz.transpose();

            for (size_t j = 0; j < facesz.size(); ++j)
            {
              Plane pl;
              pl.fid  = facesz[j];
              pl.nref = hsz.matrix.row(j).transpose(); // PATCH: column
              pl.n_u  = JinvTz * pl.nref;

              const Real nn2 = norm2(pl.n_u);
              pl.nn = std::sqrt(nn2);
              pl.ok = (pl.nn > Real(0)) && is_finite(pl.nn);

              Geometry::Polytope::Project(gz).face(j, s_rc_tmp, s_r_in);

#ifndef NDEBUG
              const Real ph = phi_face_z(j, s_rc_tmp);
              const auto nrow = hsz.matrix.row(j);
              const Real nrm  = std::sqrt(std::max<Real>(0, dot(nrow, nrow)));
              const Real rrm  = std::sqrt(std::max<Real>(0, dot(s_rc_tmp, s_rc_tmp)));
              const Real scale = Real(1) + std::abs(hsz.vector[j]) + nrm * rrm;
              const Real tol = Real(1e3) * sqrt_eps * scale;
              assert(std::abs(ph) <= tol);
#endif

              x_of_z(s_x_face, s_rc_tmp);
              pl.c_u = dot(pl.n_u, s_x_face);

              // PATCH: robust orientation
              const Real sd_in  = pl.c_u - dot(pl.n_u, s_x_in);
              const Real tol_in = Real(10) * sqrt_eps * std::max<Real>(Real(1), std::abs(pl.c_u));
              if (sd_in < -tol_in)
              {
                pl.n_u = -pl.n_u;
                pl.c_u = -pl.c_u;
              }

              planes[j] = pl;
            }

            // eps_hit_phys for this cell
            Real h_scale_z = Real(0);
            for (size_t j = 0; j < planes.size(); ++j)
            {
              const Plane& pl = planes[j];
              if (!pl.ok) continue;
              const Real d = (pl.c_u - dot(pl.n_u, s_x_in)) / pl.nn;
              if (is_finite(d)) h_scale_z = std::max(h_scale_z, d);
            }
            if (!(h_scale_z > Real(0)) || !is_finite(h_scale_z))
              break;

            const Real eps_hit_phys_z = C_HIT * sqrt_eps * h_scale_z;

            // candidates at t=0
            cand.clear();
            cand.reserve(planes.size());

            const auto vz = vrefz(s_rc);
            const Real vrefz_mag = std::sqrt(norm2(vz));
            const Real eps_ndv_z = C_NDV * sqrt_eps * (Real(1) + vrefz_mag);

            bool have_non_last = false;
            for (size_t j = 0; j < planes.size(); ++j)
            {
              const Plane& pl = planes[j];
              if (!pl.ok) continue;

              const Real sd = (pl.c_u - dot(pl.n_u, s_x)) / pl.nn;
              if (!is_finite(sd)) continue;
              if (!(sd <= eps_hit_phys_z)) continue;

              const Real ndv = dot(vz, pl.nref);
              const bool is_last = (last_face && j == *last_face);
              if (!is_last) have_non_last = true;

              cand.push_back(Cand{ j, sd, ndv, pl.fid, is_last });
            }

            // PATCH: soft hysteresis in zero-hop too
            if (have_non_last)
            {
              size_t w = 0;
              for (size_t k = 0; k < cand.size(); ++k)
                if (!cand[k].is_last) cand[w++] = cand[k];
              cand.resize(w);
            }

            if (cand.empty())
              break;

            // deterministic pick (same policy, but using eps_ndv_z)
            auto pick_best_zero = [&](size_t& jhit0, PickMode& mode0) -> bool
            {
              auto key = [](const Cand& c)
              {
                return std::tuple<Real, Real, Index>(c.sd, -c.ndv, c.fid);
              };

              bool have = false;
              Cand best = cand.front();

              for (const auto& c : cand)
              {
                if (!(c.ndv > eps_ndv_z)) continue;
                if (!have) { best = c; have = true; continue; }
                if (key(c) < key(best)) best = c;
              }
              if (have) { jhit0 = best.j; mode0 = PickMode::Strict; return true; }

              have = false;
              for (const auto& c : cand)
              {
                if (!(c.ndv > Real(0))) continue;
                if (!have) { best = c; have = true; continue; }
                if (key(c) < key(best)) best = c;
              }
              if (have) { jhit0 = best.j; mode0 = PickMode::NdvPos; return true; }

              have = false;
              for (const auto& c : cand)
              {
                if (!(c.sd < Real(0))) continue;
                if (!have) { best = c; have = true; continue; }
                if (std::tuple<Real,Index>(c.sd,c.fid) < std::tuple<Real,Index>(best.sd,best.fid))
                  best = c;
              }
              if (have) { jhit0 = best.j; mode0 = PickMode::Overshot; return true; }

              return false;
            };

            size_t jbest = 0;
            PickMode m = PickMode::Strict;
            if (!pick_best_zero(jbest, m))
              break;

            const Index f2 = facesz[jbest];

            // boundary?
            if (mesh.isBoundary(f2))
            {
              if (!m_bp(BoundaryHit{tau, s_cell, s_rc, jbest}))
                return Trace{ true, tau, Geometry::Point(*itz, s_rc) };

              last_face.reset();
              break;
            }

            // hop across f2 at t=0
            x_of_z(s_pc, s_rc);

            const auto& nbr2 = conn.getIncidence(cd - 1, cd).at(f2);
            assert(nbr2.size() == 2);
            s_cell = (nbr2[0] == s_cell) ? nbr2[1] : nbr2[0];

            mesh.getPolytopeTransformation(cd, s_cell).inverse(s_rc, s_pc);
            Geometry::Polytope::Project(mesh.getGeometry(cd, s_cell)).cell(s_rc1, s_rc);
            s_rc = s_rc1;

            // update hysteresis in new cell
            const auto& faces_next = conn.getIncidence(cd, cd - 1).at(s_cell);
            last_face.reset();
            for (size_t j = 0; j < faces_next.size(); ++j)
              if (faces_next[j] == f2) { last_face = j; break; }
          }
        }

        const auto itf = mesh.getPolytope(cd, s_cell);
        return Trace{ false, tau, Geometry::Point(*itf, s_rc) };
      }

      constexpr
      auto getValue(const Geometry::Point& p) const
      {
        const auto& trace = this->trace(p);
        const bool b = !trace.exited();
        return b * m_operand->getValue(trace.getPoint());
      }

      constexpr
      const auto& getLeaf() const
      {
        return m_operand->getLeaf();
      }

      const auto& getOperand() const
      {
        assert(m_operand);
        return *m_operand;
      }

      const auto& getVelocity() const
      {
        return m_velocity;
      }

      const auto& getStep() const
      {
        return m_step;
      }

      const auto& getBoundaryPolicy() const
      {
        return m_bp;
      }

      const auto& getTangentPolicy() const
      {
        return m_tp;
      }

      Flow& setMaximumZeroHops(size_t maxHops)
      {
        m_maxZeroHops = maxHops;
        return *this;
      }

      Flow& setMaximumBisections(size_t maxIters)
      {
        m_maxBisectionIterations = maxIters;
        return *this;
      }

      Flow& setMaximumSubdivisions(size_t maxIters)
      {
        m_maxSubdivisionIterations = maxIters;
        return *this;
      }

      virtual Flow* copy() const noexcept override
      {
        return new Flow(*this);
      }

    private:
      size_t m_maxZeroHops;
      size_t m_maxBisectionIterations;
      size_t m_maxSubdivisionIterations;

      const Real m_t;
      std::unique_ptr<Operand> m_operand;
      VectorFieldType m_velocity;
      Step m_step;
      BoundaryPolicy m_bp;
      TangentPolicy m_tp;
      const Geometry::Point* m_p;
  };

  template <class Derived, class Velocity>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&)
    -> Flow<
         FunctionBase<Derived>,
         Velocity,                       // keep T or T&
         Math::RungeKutta::RK4,      // value default
         DefaultBoundaryPolicy,
         DefaultTangentPolicy>;

  template <class Derived, class Velocity, class Step>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&, Step&&)
    -> Flow<
         FunctionBase<Derived>,
         Velocity,
         Step,
         DefaultBoundaryPolicy,
         DefaultTangentPolicy>;

  template <
    class Derived,
    class Velocity, class Step, class BBP, class TTP>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&, Step&&, BBP&&, TTP&&)
    -> Flow<FunctionBase<Derived>, Velocity, Step, BBP, TTP>;
}

#endif
