/*
 *          Copyright Carlos BRITO PACHECO 2021 - 2025.
 * Distributed under the Boost Software License, Version 1.0.
 *       (See accompanying file LICENSE or copy at
 *          https://www.boost.org/LICENSE_1_0.txt)
 */
/**
 * @file Flow.h
 * @brief Flow map operators for shape functions and grid functions.
 *
 * This file defines the Flow class, which implements the flow map (push-forward)
 * of functions along a vector field. Flow maps are used in advection problems,
 * level set methods, and semi-Lagrangian time integration schemes.
 *
 * ## Mathematical Foundation
 * Given a velocity field @f$ \mathbf{v}(x,t) @f$, the flow map @f$ \Phi_t @f$
 * satisfies:
 * @f[
 *   \frac{d\Phi}{dt}(x,t) = \mathbf{v}(\Phi(x,t), t), \quad \Phi(x,0) = x
 * @f]
 *
 * The flow operator computes @f$ u(\Phi(x,t)) @f$, which represents the value
 * of function @f$ u @f$ advected along the flow.
 *
 * ## Applications
 * - **Advection-diffusion**: @f$ \frac{\partial u}{\partial t} + \mathbf{v} \cdot \nabla u = f @f$
 * - **Semi-Lagrangian methods**: Characteristic tracking for transport equations
 * - **Level set methods**: Interface evolution and tracking
 * - **ALE formulations**: Arbitrary Lagrangian-Eulerian methods
 */
#ifndef RODIN_VARIATIONAL_FLOW_H
#define RODIN_VARIATIONAL_FLOW_H

#include "ForwardDecls.h"

#include "Rodin/FormLanguage/Traits.h"
#include "Rodin/Geometry/Mesh.h"
#include "Rodin/Geometry/Point.h"
#include "Rodin/Geometry/Polytope.h"
#include "Rodin/Geometry/Region.h"

#include "Rodin/Math/SpatialVector.h"
#include "Rodin/Math/Vector.h"
#include "Rodin/Math/RungeKutta/RK4.h"

#include "Rodin/QF/GenericPolytopeQuadrature.h"
#include "Rodin/Variational/ShapeFunction.h"

#include "Rodin/QF/QuadratureFormula.h"

namespace Rodin::FormLanguage
{
  template <
    class Derived,
    class FES,
    class VectorField,
    class Step,
    class BoundaryPolicy
  >
  struct Traits<
    Variational::Flow<
      Variational::ShapeFunctionBase<Derived, FES, Variational::TestSpace>,
      VectorField, Step, BoundaryPolicy>>
  {
    using FESType = FES;
    static constexpr Variational::ShapeFunctionSpaceType SpaceType = Variational::TestSpace;

    using OperandType =
      Variational::ShapeFunctionBase<Derived, FES, Variational::TestSpace>;
  };
}

namespace Rodin::Variational
{
  struct BoundaryHit
  {
    Real& tau; ///< Time remaining until end of step
    Index& cell; ///< Cell index where boundary was hit
    Math::SpatialPoint& rref; ///< Reference coordinates where boundary was hit
    size_t face; ///< Local face index where boundary was hit
    Real& correction;
  };

  /**
   * @brief Default boundary policy for flow maps.
   *
   * This policy does not enforce any special treatment at domain boundaries.
   * Flow integration continues unmodified when approaching boundaries.
   */
  class DefaultBoundaryPolicy
  {
    public:
      /**
       * @brief Called when flow reaches a boundary.
       * @returns false (no special boundary treatment)
       */
      constexpr
      bool operator()(const BoundaryHit&) const
      {
        return false;
      }
  };

  /**
   * @ingroup RodinVariational
   * @brief Flow map operator for functions.
   *
   * Computes the composition of a function with the flow map generated by a
   * vector field. Given a function @f$ u @f$ and velocity field @f$ \mathbf{v} @f$,
   * this computes @f$ u \circ \Phi @f$ where @f$ \Phi @f$ is the flow map.
   *
   * @tparam Derived Type of the function being advected
   * @tparam VectorField Type of the velocity field
   * @tparam Step Time step for flow integration
   * @tparam BoundaryPolicy Policy for handling domain boundaries
   * @tparam TangentPolicy Policy for tangent vector computation
   */
  template <
    class Derived,
    class VectorField,
    class Step,
    class BoundaryPolicy>
  class Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy>
    : public FunctionBase<Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy>>
  {
    public:
      /// @brief Type of the operand function
      using Operand =
        FunctionBase<Derived>;

      using VectorFieldType =
        VectorField;

      using StepType =
        Step;

      using BoundaryPolicyType =
        BoundaryPolicy;

      using Parent =
        FunctionBase<Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy>>;

      class Trace
      {
        public:
          Trace(bool exited, Real time, const Geometry::Point& p, Real correction)
            : m_exited(exited), m_time(time), m_point(p), m_correction(correction)
          {}

          Real getTime() const
          {
            return m_time;
          }

          const Geometry::Point& getPoint() const
          {
            return m_point;
          }

          bool exited() const
          {
            return m_exited;
          }

          Real getCorrection() const
          {
            return m_correction;
          }

        private:
          bool m_exited;
          Real m_time;
          Geometry::Point m_point;
          Real m_correction;
      };

      template <
        class VVel,
        class S = StepType,
        class B = BoundaryPolicy>
      Flow(const Real& t,
           const Operand& u,
           VVel&& vel,
           S&& st=S{}, B&& bp=B{})
        : m_maxZeroHops(128),
          m_maxBisectionIterations(16),
          m_maxSubdivisionIterations(8),
          m_t(t),
          m_operand(u.copy()),
          m_velocity(std::forward<VVel>(vel)),
          m_step(std::forward<S>(st)),
          m_bp(std::forward<B>(bp)),
          m_p(nullptr)
      {}

      Flow(const Flow& other)
        : Parent(other),
          m_maxZeroHops(other.m_maxZeroHops),
          m_maxBisectionIterations(other.m_maxBisectionIterations),
          m_maxSubdivisionIterations(other.m_maxSubdivisionIterations),
          m_t(other.m_t),
          m_operand(other.m_operand->copy()),
          m_velocity(other.m_velocity),
          m_step(other.m_step),
          m_bp(other.m_bp),
          m_p(other.m_p)
      {}

      Flow(Flow&& other)
        : Parent(std::move(other)),
          m_maxZeroHops(std::move(other.m_maxZeroHops)),
          m_maxBisectionIterations(std::move(other.m_maxBisectionIterations)),
          m_maxSubdivisionIterations(std::move(other.m_maxSubdivisionIterations)),
          m_t(std::move(other.m_t)),
          m_operand(std::move(other.m_operand)),
          m_velocity(std::move(other.m_velocity)),
          m_step(std::move(other.m_step)),
          m_bp(std::move(other.m_bp)),
          m_p(std::exchange(other.m_p, nullptr))
      {}

      Trace trace(const Geometry::Point& p) const
      {
        //  - deterministically handles many crossings per step (repeat: find earliest face-crossing, hop, continue)
        //  - robust on bad/sliver elements via per-cell dt cap + adaptive substepping on bracketing failure
        //  - never bisects a non-monotone predicate: always bisects a single face function phi_j(t)
        //  - deterministic zero-hop chaining (edge/vertex) with soft hysteresis
        //  - invariant “inside” clamp after every integrate step (only if violated)
        //
        // Requirements (must hold for ALL polytope types):
        //   * hs: phi_j(r)=b_j - n_j·r, interior iff phi_j(r) >= 0 for all j
        //   * faces[j] corresponds to hs.row(j)
        //   * Project(g).face(j, out, r) puts out on face j and inside other faces (up to tol)
        //   * Project(g).cell(out, r) clamps inside (up to tol)
        //
        // NOTE about velocity return type:
        //   If m_velocity(qp) returns a vector, use "return m_velocity(qp);"
        //   If it returns a (dim x 1) matrix/expression, use "return m_velocity(qp).col(0);"
        //
        // This code assumes affine cell maps (J^{-1} constant per cell). It still works if you evaluate
        // J^{-1} at qp each time (you already do), but guarantees are best for P1 geometry.

        struct Candidate
        {
          Real   tlin;   // linear predictor time
          size_t j;      // local face index
          Real   ndv;    // nref · vref at start
          Real   phi0;   // phi_j(r0)
          Index  fid;    // global face id
        };

        const size_t ZERO_HOPS_MAX = m_maxZeroHops;
        const int    MAX_BISECT    = static_cast<int>(m_maxBisectionIterations);
        const int    MAX_SUBDIV    = static_cast<int>(m_maxSubdivisionIterations);

        // Bracketing knobs (safe defaults)
        const int   K_TRY     = 6;          // how many smallest-tlin faces to try first
        const Real  GAMMA     = Real(2.0);  // bracket expansion factor
        const int   EXPANDS   = 3;          // #expansions per face
        const Real  ETA_CAP   = Real(0.5);  // dt cap factor based on cell size (sliver robustness)
        const Real  C_EPS     = Real(50);   // sqrt(eps) multiplier for reference tolerances
        const Real  C_VIOL    = Real(10);   // “outside” margin before clamping
        const Real  C_DTMIN   = Real(10);   // dt_min scaling

        const auto& poly0 = p.getPolytope();
        const auto& mesh  = poly0.getMesh();
        const size_t cd   = mesh.getDimension();
        const auto& conn  = mesh.getConnectivity();

        Real correction = Real(0);

        Real tau = std::abs(m_t);
        const Real sgn = Math::sgn(m_t);

        const Real eps_machine = std::numeric_limits<Real>::epsilon();
        const Real sqrt_eps    = std::sqrt(eps_machine);
        const Real v_floor     = std::numeric_limits<Real>::min();

        auto is_finite = [](Real v) -> bool { return std::isfinite(v); };

        auto dot = [](const auto& a, const auto& b) -> Real { return b.dot(a); };

        auto norm2 = [&](const auto& v) -> Real
        {
          const Real v2 = dot(v, v);
          return std::max<Real>(Real(0), v2);
        };

        // Normalize velocity return type in ONE place.
        auto vphys_of = [&](const Geometry::Point& qp) -> Math::SpatialVector<Real>
        {
          // ---- choose ONE ----
          // return m_velocity(qp);          // if vector-like
          return m_velocity(qp).col(0);      // if (dim x 1) matrix-like
        };

        // -------------------- scratch (thread-local to reduce allocations) --------------------
        static thread_local Index s_cell;
        static thread_local Math::SpatialPoint s_rc{{}}, s_rc1{{}}, s_rc_tmp{{}}, s_r_eval{{}}, s_r_in{{}};
        static thread_local Math::SpatialPoint s_pc{{}}, s_x{{}}, s_x_in{{}}, s_x_face{{}};
        static thread_local std::vector<Candidate> s_cand;
        static thread_local std::vector<size_t> s_faceset;

        // -------------------- locate starting cell / reference coords --------------------
        s_cell = Index(-1);

        if (poly0.getDimension() == cd)
        {
          s_cell = poly0.getIndex();
          s_rc   = p.getReferenceCoordinates();
        }
        else if (poly0.getDimension() == cd - 1)
        {
          const Index f = poly0.getIndex();
          const auto& adj = conn.getIncidence(cd - 1, cd).at(f);

          if (mesh.isBoundary(f))
          {
            const Index c = adj[0];
            mesh.getPolytopeTransformation(cd, c).inverse(s_rc_tmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c)).cell(s_rc, s_rc_tmp);
            s_cell = c;
          }
          else
          {
            // Project into both adjacent cells; decide by flow direction; fallback by interior score.
            const Index c0 = adj[0];
            const Index c1 = adj[1];

            mesh.getPolytopeTransformation(cd, c0).inverse(s_rc_tmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c0)).cell(s_rc1, s_rc_tmp);
            const Math::SpatialPoint rc0 = s_rc1;

            mesh.getPolytopeTransformation(cd, c1).inverse(s_rc_tmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c1)).cell(s_rc1, s_rc_tmp);
            const Math::SpatialPoint rc1 = s_rc1;

            const auto& faces0 = conn.getIncidence(cd, cd - 1).at(c0);
            size_t j0 = faces0.size();
            for (size_t k = 0; k < faces0.size(); ++k)
              if (faces0[k] == f) { j0 = k; break; }

            const auto g0 = mesh.getGeometry(cd, c0);
            const Geometry::Polytope::Traits ts0(g0);
            const auto& hs0 = ts0.getHalfSpace();
            const Math::SpatialVector<Real> nref0 = hs0.matrix.row(j0).transpose();

            const auto it0 = mesh.getPolytope(cd, c0);
            const auto& cell0 = *it0;
            const Geometry::Point q0(cell0, rc0, p.getPhysicalCoordinates());
            const auto vref0 = (sgn * q0.getJacobianInverse() * vphys_of(q0));
            const Real ndv0 = dot(nref0, vref0);

            auto interior_score = [&](Index c, const Math::SpatialPoint& rproj) -> Real
            {
              const auto gc = mesh.getGeometry(cd, c);
              const Geometry::Polytope::Traits tsc(gc);
              const auto& hsc = tsc.getHalfSpace();
              Real s = std::numeric_limits<Real>::infinity();
              for (int j = 0; j < hsc.vector.size(); ++j)
              {
                const auto n = hsc.matrix.row(j);
                const Real b = hsc.vector[j];
                s = std::min(s, b - rproj.dot(n));
              }
              return s;
            };

            const Real eps_ndv0 = Real(10) * sqrt_eps;
            if (std::abs(ndv0) <= eps_ndv0)
            {
              const Real s0 = interior_score(c0, rc0);
              const Real s1 = interior_score(c1, rc1);
              if (s1 > s0) { s_cell = c1; s_rc = rc1; }
              else         { s_cell = c0; s_rc = rc0; }
            }
            else if (ndv0 > 0)
            {
              // moving out of c0 through face f -> start in c1
              s_cell = c1;
              s_rc   = rc1;
            }
            else
            {
              s_cell = c0;
              s_rc   = rc0;
            }
          }
        }
        else
        {
          return Trace{ true, Real(0), p, correction };
        }

        // Resize buffers
        s_rc1.resize(s_rc.size());
        s_rc_tmp.resize(s_rc.size());
        s_r_eval.resize(s_rc.size());
        s_r_in.resize(s_rc.size());

        s_pc.resize(p.getPhysicalCoordinates().size());
        s_x.resize(s_pc.size());
        s_x_in.resize(s_pc.size());
        s_x_face.resize(s_pc.size());

        // Soft hysteresis: avoid immediate backtracking if alternatives exist.
        std::optional<size_t> last_face;

        // -------------------- helpers --------------------
        auto phi_face = [&](const auto& hs, size_t j, const Math::SpatialPoint& r) -> Real
        {
          const auto n = hs.matrix.row(j);
          const Real b = hs.vector[j];
          return b - r.dot(n); // interior => >= 0
        };

        auto clamp_if_outside = [&](const auto& hs, const auto& g, Math::SpatialPoint& r, Real eps_phi) -> void
        {
          bool violated = false;
          for (int j = 0; j < hs.vector.size(); ++j)
          {
            if (phi_face(hs, static_cast<size_t>(j), r) < -C_VIOL * eps_phi)
            {
              violated = true;
              break;
            }
          }
          if (violated)
          {
            Geometry::Polytope::Project(g).cell(s_rc1, r);
            r = s_rc1;
          }
        };

        // -------------------- main loop: keep consuming tau --------------------
        while (tau > 0)
        {
          const auto itc = mesh.getPolytope(cd, s_cell);
          const auto& cell = *itc;

          const auto g = mesh.getGeometry(cd, s_cell);
          const Geometry::Polytope::Traits ts(g);
          const auto& faces = conn.getIncidence(cd, cd - 1).at(s_cell);
          const auto& hs = ts.getHalfSpace();

          // Reference velocity vref(r) = sgn * J^{-1}(r) * vphys(r)
          auto vref = [&](const Math::SpatialPoint& r) -> Math::SpatialVector<Real>
          {
            const Geometry::Point qp(cell, r);
            return (sgn * qp.getJacobianInverse() * vphys_of(qp));
          };

          // Integrate in reference
          auto advance = [&](Math::SpatialPoint& rout, Real dt, const Math::SpatialPoint& rin)
          {
            m_step.step(rout, dt, rin,
              [&](const Math::SpatialPoint& rr) -> Math::SpatialVector<Real>
              {
                return vref(rr);
              });
          };

          // Current physical point
          mesh.getPolytopeTransformation(cd, s_cell).transform(s_x, s_rc);

          // Reference eps model (scale-aware)
          const Real rnorm = std::sqrt(norm2(s_rc));
          const auto v0 = vref(s_rc);
          const Real vref_mag = std::sqrt(norm2(v0));

          const Real eps_phi = C_EPS * sqrt_eps * (Real(1) + rnorm);
          const Real eps_ndv = C_EPS * sqrt_eps * (Real(1) + vref_mag);

          // Per-cell dt cap based on physical size (robust on slivers)
          Real dt_cap = tau;
          {
            const auto rcent = ts.getCentroid();
            s_r_in = rcent;
            mesh.getPolytopeTransformation(cd, s_cell).transform(s_x_in, s_r_in);

            const Geometry::Point qJ(cell, s_r_in, s_x_in);
            const auto JinvT = qJ.getJacobianInverse().transpose();

            Real h_scale = Real(0);

            for (size_t j = 0; j < faces.size(); ++j)
            {
              const Math::SpatialVector<Real> nref = hs.matrix.row(j).transpose();
              auto n_u = JinvT * nref;
              const Real nn = std::sqrt(std::max<Real>(Real(0), dot(n_u, n_u)));
              if (!(nn > Real(0)) || !is_finite(nn)) continue;

              // anchor point on face: project centroid to face in reference, then map to x
              Geometry::Polytope::Project(g).face(j, s_rc_tmp, s_r_in);
              mesh.getPolytopeTransformation(cd, s_cell).transform(s_x_face, s_rc_tmp);

              Real c_u = dot(n_u, s_x_face);
              const Real sd_in = c_u - dot(n_u, s_x_in);
              if (sd_in < 0) { n_u = -n_u; c_u = -c_u; }

              const Real d = (c_u - dot(n_u, s_x_in)) / nn;
              if (is_finite(d)) h_scale = std::max(h_scale, d);
            }

            Real vphys_mag = Real(0);
            {
              const Geometry::Point qp(cell, s_rc, s_x);
              const auto vphys = vphys_of(qp);
              vphys_mag = std::sqrt(norm2(vphys));
              if (!is_finite(vphys_mag)) vphys_mag = Real(0);
            }

            if (h_scale > Real(0) && is_finite(h_scale))
            {
              dt_cap = std::min(dt_cap, ETA_CAP * h_scale / std::max<Real>(vphys_mag, v_floor));
            }
            if (!(dt_cap > Real(0)) || !is_finite(dt_cap))
              dt_cap = tau;
          }

          // Minimum dt to prevent infinite substepping near tangency/noise
          const Real dt_min = C_DTMIN * sqrt_eps * (Real(1) + rnorm) / std::max<Real>(Real(1), vref_mag);

          std::optional<Trace> exit_trace;

          // ------------------------------------------------------------
          // Zero-hop / on-edge cleanup (dt = 0) BEFORE searching events.
          // Deterministic selection among active faces with soft hysteresis.
          // ------------------------------------------------------------
          auto do_zero_hops = [&]() -> bool
          {
            size_t hops = 0;
            while (hops++ < ZERO_HOPS_MAX)
            {
              const auto vz = vref(s_rc);

              // Find all faces with |phi| small AND exiting (ndv > eps_ndv)
              s_faceset.clear();
              s_faceset.reserve(faces.size());

              bool have_non_last = false;
              for (size_t j = 0; j < faces.size(); ++j)
              {
                const Real ph = phi_face(hs, j, s_rc);
                if (std::abs(ph) > eps_phi) continue;

                const Math::SpatialVector<Real> nref = hs.matrix.row(j).transpose();
                const Real ndv = dot(nref, vz);
                if (!(ndv > eps_ndv)) continue;

                const bool is_last = (last_face && j == *last_face);
                if (!is_last) have_non_last = true;

                s_faceset.push_back(j);
              }

              if (s_faceset.empty())
                break;

              auto key = [&](size_t j) -> std::tuple<Real, Real, Index>
              {
                const Real ph = phi_face(hs, j, s_rc);
                const auto vz2 = vref(s_rc);
                const Real ndv = vz2.dot(hs.matrix.row(j).transpose());
                const Index fid = faces[j];
                return { std::abs(ph), -ndv, fid };
              };

              // Soft hysteresis: if alternatives exist, drop last_face
              size_t best = size_t(-1);
              bool have = false;
              for (size_t jj : s_faceset)
              {
                if (have_non_last && last_face && jj == *last_face) continue;
                if (!have) { best = jj; have = true; }
                else if (key(jj) < key(best)) { best = jj; }
              }
              if (!have)
                break;

              const Index f = faces[best];

              // boundary?
              if (mesh.isBoundary(f))
              {
                BoundaryHit bh{tau, s_cell, s_rc, best, correction};
                if (!m_bp(bh))
                {
                  exit_trace.emplace(true, tau, Geometry::Point(cell, s_rc), correction);
                  return false; // no cell change, but we want to abort
                }
                last_face.reset();
                break;
              }

              // hop across face at t=0
              mesh.getPolytopeTransformation(cd, s_cell).transform(s_pc, s_rc);
              const auto& nbrs = conn.getIncidence(cd - 1, cd).at(f);
              if (nbrs.size() != 2) // defensive
                return false;
              s_cell = (nbrs[0] == s_cell) ? nbrs[1] : nbrs[0];

              mesh.getPolytopeTransformation(cd, s_cell).inverse(s_rc, s_pc);
              Geometry::Polytope::Project(mesh.getGeometry(cd, s_cell)).cell(s_rc1, s_rc);
              s_rc = s_rc1;

              // update last_face in new cell
              const auto& faces_new = conn.getIncidence(cd, cd - 1).at(s_cell);
              last_face.reset();
              for (size_t j = 0; j < faces_new.size(); ++j)
                if (faces_new[j] == f) { last_face = j; break; }

              // We changed cell: caller must restart outer iteration
              return true;
            }
            return false; // no cell change
          };

          // If zero-hops moved us, restart with refreshed hs/faces/g for new cell
          if (do_zero_hops())
            continue;

          if (exit_trace)
            return *exit_trace;

          // ------------------------------------------------------------
          // Attempt to find an event within tau_cell using bracketing+bisection.
          // If bracketing fails, adaptive substep: tau_cell *= 0.5 and retry.
          // ------------------------------------------------------------
          Real tau_cell = std::min(tau, dt_cap);

          bool found_event = false;
          size_t j_star = 0;
          Real hi_star = Real(0);

          auto phi_at_time = [&](size_t j, Real t, Math::SpatialPoint& r_out) -> Real
          {
            advance(r_out, t, s_rc);
            return phi_face(hs, j, r_out);
          };

          auto try_bracket_face = [&](size_t j, Real t0, Real& hi_out) -> bool
          {
            Real t = std::min(t0, tau_cell);
            if (!(t > Real(0)) || !is_finite(t)) return false;

            Real ph = phi_at_time(j, t, s_r_eval);
            if (!is_finite(ph)) return false;

            if (ph <= Real(0)) { hi_out = t; return true; }

            Real texp = t;
            for (int k = 0; k < EXPANDS; ++k)
            {
              const Real tnext = std::min(tau_cell, GAMMA * texp);
              if (!(tnext > texp)) break;

              texp = tnext;
              ph = phi_at_time(j, texp, s_r_eval);
              if (!is_finite(ph)) return false;

              if (ph <= Real(0)) { hi_out = texp; return true; }
            }

            // last chance: tau_cell
            if (texp < tau_cell)
            {
              ph = phi_at_time(j, tau_cell, s_r_eval);
              if (is_finite(ph) && ph <= Real(0)) { hi_out = tau_cell; return true; }
            }

            return false;
          };

          for (int subdiv = 0; subdiv <= MAX_SUBDIV; ++subdiv)
          {
            // Build linear candidates within tau_cell
            s_cand.clear();
            s_cand.reserve(faces.size());

            for (size_t j = 0; j < faces.size(); ++j)
            {
              const Real phi0 = phi_face(hs, j, s_rc);

              // If on/outside, zero-hop should have handled it; don't use as forward event.
              if (!(phi0 > eps_phi)) continue;

              const Math::SpatialVector<Real> nref = hs.matrix.row(j).transpose();
              const Real ndv = dot(nref, v0);
              if (!(ndv > eps_ndv)) continue;

              const Real tlin = phi0 / ndv;
              if (!(tlin > Real(0)) || !is_finite(tlin)) continue;
              if (tlin > tau_cell) continue;

              s_cand.push_back(Candidate{ tlin, j, ndv, phi0, faces[j] });
            }

            if (s_cand.empty())
            {
              found_event = false;
              break;
            }

            std::sort(s_cand.begin(), s_cand.end(),
              [](const Candidate& a, const Candidate& b)
              {
                if (a.tlin != b.tlin) return a.tlin < b.tlin;
                if (a.ndv  != b.ndv ) return a.ndv  > b.ndv;
                return a.fid < b.fid;
              });

            // Scan some best candidates first, then all if needed.
            const int ntry = std::min<int>(K_TRY, static_cast<int>(s_cand.size()));

            auto consider = [&](int begin, int end)
            {
              for (int k = begin; k < end; ++k)
              {
                const auto& c = s_cand[static_cast<size_t>(k)];

                // soft hysteresis: skip last_face only if there are other faces to try
                if (last_face && c.j == *last_face && s_cand.size() > 1)
                  continue;

                Real hi = Real(0);
                if (!try_bracket_face(c.j, c.tlin, hi)) continue;

                if (!found_event || hi < hi_star)
                {
                  found_event = true;
                  j_star = c.j;
                  hi_star = hi;
                }
              }
            };

            found_event = false;
            consider(0, ntry);
            if (!found_event)
              consider(ntry, static_cast<int>(s_cand.size()));

            if (found_event)
              break;

            // Adaptive substep if bracketing failed
            tau_cell *= Real(0.5);
            if (tau_cell <= dt_min || !is_finite(tau_cell))
              break;
          }

          if (!found_event)
          {
            // No event found robustly within tau_cell: advance tau_cell and clamp if needed.
            // This is safe and stable; accuracy depends on dt_cap and mesh quality.
            advance(s_rc1, tau_cell, s_rc);
            s_rc = s_rc1;

            clamp_if_outside(hs, g, s_rc, eps_phi);

            tau -= tau_cell;
            continue;
          }

          // ------------------------------------------------------------
          // Bisection on single face j_star: phi_j(t)=0 with bracket [0, hi_star]
          // ------------------------------------------------------------
          const Real phi0_star = phi_face(hs, j_star, s_rc);
          if (!(phi0_star > Real(0)))
          {
            // Degenerate start; clamp and restart
            Geometry::Polytope::Project(g).cell(s_rc1, s_rc);
            s_rc = s_rc1;
            continue;
          }

          // dt tolerance scaled by "speed toward face"
          const Real ndv0 = dot(hs.matrix.row(j_star).transpose(), v0);
          const Real dt_tol = std::max<Real>(Real(1e-12), eps_phi / std::max<Real>(ndv0, v_floor));

          Real lo = Real(0);
          Real hi = hi_star;

          for (int it = 0; it < MAX_BISECT; ++it)
          {
            if (hi - lo <= dt_tol) break;

            const Real mid = Real(0.5) * (lo + hi);
            const Real phm = phi_at_time(j_star, mid, s_r_eval);

            if (!is_finite(phm))
            {
              // shrink conservatively
              hi = mid;
              continue;
            }

            if (phm > Real(0))
              lo = mid;
            else
              hi = mid;
          }

          const Real thit = hi;

          // Advance to thit, then project onto hit face, then clamp inside
          advance(s_rc1, thit, s_rc);
          Geometry::Polytope::Project(g).face(j_star, s_rc, s_rc1);
          s_rc = s_rc1;

          Geometry::Polytope::Project(g).cell(s_rc1, s_rc);
          s_rc = s_rc1;

          tau -= thit;

          const Index face_hit = faces[j_star];

          // physical point at face for mapping
          mesh.getPolytopeTransformation(cd, s_cell).transform(s_pc, s_rc);

          // ------------------------------------------------------------
          // Boundary vs interior hop
          // ------------------------------------------------------------
          if (mesh.isBoundary(face_hit))
          {
            BoundaryHit bh{tau, s_cell, s_rc, j_star, correction};
            if (!m_bp(bh))
              return Trace{ true, tau, Geometry::Point(*itc, s_rc), correction };

            last_face.reset();
            continue;
          }

          // Hop across face_hit
          {
            const auto& nbrs = conn.getIncidence(cd - 1, cd).at(face_hit);
            if (nbrs.size() != 2)
              return Trace{ true, tau, Geometry::Point(*itc, s_rc), correction };
            s_cell = (nbrs[0] == s_cell) ? nbrs[1] : nbrs[0];
          }

          // Map same physical point into new cell and clamp
          mesh.getPolytopeTransformation(cd, s_cell).inverse(s_rc, s_pc);
          Geometry::Polytope::Project(mesh.getGeometry(cd, s_cell)).cell(s_rc1, s_rc);
          s_rc = s_rc1;

          // Update hysteresis in new cell: mark the face we just crossed
          {
            const auto& faces_new = conn.getIncidence(cd, cd - 1).at(s_cell);
            last_face.reset();
            for (size_t j = 0; j < faces_new.size(); ++j)
              if (faces_new[j] == face_hit) { last_face = j; break; }
          }

          // Loop continues; next iteration will zero-hop if we landed on an edge/vertex
        }

        const auto itf = mesh.getPolytope(cd, s_cell);
        return Trace{ false, tau, Geometry::Point(*itf, s_rc), correction };
      }

      constexpr
      auto getValue(const Geometry::Point& p) const
      {
        const auto tr = this->trace(p);
        if (tr.exited())
          return Real(0);
        return m_operand->getValue(tr.getPoint()) + tr.getCorrection();
      }

      constexpr
      const auto& getLeaf() const
      {
        return m_operand->getLeaf();
      }

      const auto& getOperand() const
      {
        assert(m_operand);
        return *m_operand;
      }

      const auto& getVelocity() const
      {
        return m_velocity;
      }

      const auto& getStep() const
      {
        return m_step;
      }

      const auto& getBoundaryPolicy() const
      {
        return m_bp;
      }

      Flow& setMaximumZeroHops(size_t maxHops)
      {
        m_maxZeroHops = maxHops;
        return *this;
      }

      Flow& setMaximumBisections(size_t maxIters)
      {
        m_maxBisectionIterations = maxIters;
        return *this;
      }

      Flow& setMaximumSubdivisions(size_t maxIters)
      {
        m_maxSubdivisionIterations = maxIters;
        return *this;
      }

      Optional<size_t> getOrder(const Geometry::Polytope&) const
      {
        return {};
      }

      virtual Flow* copy() const noexcept override
      {
        return new Flow(*this);
      }

    private:
      size_t m_maxZeroHops;
      size_t m_maxBisectionIterations;
      size_t m_maxSubdivisionIterations;

      const Real m_t;
      std::unique_ptr<Operand> m_operand;
      VectorFieldType m_velocity;
      Step m_step;
      BoundaryPolicy m_bp;
      const Geometry::Point* m_p;
  };

  template <class Derived, class Velocity>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&)
    -> Flow<
         FunctionBase<Derived>,
         Velocity,                       // keep T or T&
         Math::RungeKutta::RK4,      // value default
         DefaultBoundaryPolicy>;

  template <class Derived, class Velocity, class Step>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&, Step&&)
    -> Flow<
         FunctionBase<Derived>,
         Velocity,
         Step,
         DefaultBoundaryPolicy>;

  template <
    class Derived,
    class Velocity, class Step, class BBP>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&, Step&&, BBP&&)
    -> Flow<FunctionBase<Derived>, Velocity, Step, BBP>;
}

#endif
