/*
 *          Copyright Carlos BRITO PACHECO 2021 - 2025.
 * Distributed under the Boost Software License, Version 1.0.
 *       (See accompanying file LICENSE or copy at
 *          https://www.boost.org/LICENSE_1_0.txt)
 */
/**
 * @file Flow.h
 * @brief Flow map operators for shape functions and grid functions.
 *
 * This file defines the @ref Rodin::Variational::Flow class, which implements
 * the flow map (push-forward) of functions along a vector field. Flow maps are
 * used in advection problems, level set methods, and semi-Lagrangian time
 * integration schemes.
 *
 * ## Mathematical foundation
 * Given a velocity field @f$ \mathbf{v}(x,t) @f$, the flow map @f$ \Phi_t @f$
 * satisfies:
 * @f[
 *   \frac{d\Phi}{dt}(x,t) = \mathbf{v}(\Phi(x,t), t), \qquad \Phi(x,0) = x.
 * @f]
 *
 * The flow operator computes @f$ u(\Phi(x,t)) @f$, which represents the value
 * of function @f$ u @f$ advected along the flow.
 *
 * ## Applications
 * - **Advection-diffusion**:
 *   @f$ \partial_t u + \mathbf{v}\cdot\nabla u = f @f$
 * - **Semi-Lagrangian methods**: characteristic tracking for transport
 *   equations
 * - **Level set methods**: interface evolution and tracking
 * - **ALE formulations**: arbitrary Lagrangian-Eulerian methods
 */
#ifndef RODIN_VARIATIONAL_FLOW_H
#define RODIN_VARIATIONAL_FLOW_H

#include <algorithm>
#include <cassert>
#include <cmath>
#include <limits>
#include <memory>
#include <optional>
#include <tuple>
#include <utility>
#include <vector>

#include "ForwardDecls.h"

#include "Rodin/FormLanguage/Traits.h"
#include "Rodin/Geometry/Mesh.h"
#include "Rodin/Geometry/Point.h"
#include "Rodin/Geometry/Polytope.h"
#include "Rodin/Geometry/Region.h"

#include "Rodin/Math/SpatialVector.h"
#include "Rodin/Math/Vector.h"
#include "Rodin/Math/RungeKutta/RK4.h"

#include "Rodin/QF/GenericPolytopeQuadrature.h"
#include "Rodin/QF/QuadratureFormula.h"
#include "Rodin/Variational/ShapeFunction.h"

namespace Rodin::FormLanguage
{
  template <
    class Derived,
    class FES,
    class VectorField,
    class Step,
    class BoundaryPolicy
  >
  struct Traits<
    Variational::Flow<
      Variational::ShapeFunctionBase<Derived, FES, Variational::TestSpace>,
      VectorField, Step, BoundaryPolicy>>
  {
    using FESType = FES;

    static constexpr Variational::ShapeFunctionSpaceType SpaceType =
      Variational::TestSpace;

    using OperandType =
      Variational::ShapeFunctionBase<Derived, FES, Variational::TestSpace>;
  };
}

namespace Rodin::Variational
{
  /**
   * @brief Information passed to a boundary policy when a trajectory reaches
   *        the domain boundary.
   */
  struct BoundaryHit
  {
    Real& tau;                 ///< Remaining time after the hit.
    Index& cell;               ///< Current cell index.
    Math::SpatialPoint& rref;  ///< Reference coordinates of the hit point.
    size_t face;               ///< Local face index in the current cell.
    Real& correction;          ///< Additive correction to the traced value.
  };

  /**
   * @brief Default boundary policy for flow maps.
   *
   * This policy does not enforce any special treatment at domain boundaries.
   * Flow integration stops when the traced trajectory reaches the boundary.
   */
  class DefaultBoundaryPolicy
  {
    public:
      /**
       * @brief Called when a traced trajectory reaches a boundary.
       * @returns false, indicating that the trace should stop.
       */
      constexpr
      bool operator()(const BoundaryHit&) const
      {
        return false;
      }
  };

  /**
   * @ingroup RodinVariational
   * @brief Flow map operator for functions.
   *
   * Computes the composition of a function with the flow map generated by a
   * vector field. Given a function @f$ u @f$ and a velocity field
   * @f$ \mathbf{v} @f$, this class computes @f$ u \circ \Phi @f$, where
   * @f$ \Phi @f$ is the flow map associated with @f$ \mathbf{v} @f$.
   *
   * The implementation performs robust cell-by-cell tracing with explicit face
   * crossing detection, adaptive substepping, and optional boundary handling.
   *
   * @tparam Derived Type of the advected function.
   * @tparam VectorField Type of the velocity field.
   * @tparam Step Time integrator used to advance characteristics.
   * @tparam BoundaryPolicy Policy used when a trajectory reaches the boundary.
   */
  template <class Derived, class VectorField, class Step, class BoundaryPolicy>
  class Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy>
    : public FunctionBase<Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy>>
  {
    public:
      /// @brief Operand function type.
      using Operand = FunctionBase<Derived>;

      /// @brief Velocity field type.
      using VectorFieldType = VectorField;

      /// @brief Time integration scheme type.
      using StepType = Step;

      /// @brief Boundary policy type.
      using BoundaryPolicyType = BoundaryPolicy;

      using Parent =
        FunctionBase<Flow<FunctionBase<Derived>, VectorField, Step, BoundaryPolicy>>;

      /**
       * @brief Result of a characteristic trace.
       */
      class Trace
      {
        public:
          /**
           * @param exited     Whether the trace exited or aborted before
           *                   completing the full time step.
           * @param time       Remaining time.
           * @param p          Final traced point.
           * @param correction Additive correction returned by the boundary policy.
           */
          Trace(bool exited, Real time, const Geometry::Point& p, Real correction)
            : m_exited(exited),
              m_time(time),
              m_point(p),
              m_correction(correction)
          {}

          /**
           * @brief Returns the remaining unconsumed time.
           */
          Real getTime() const
          {
            return m_time;
          }

          /**
           * @brief Returns the traced point.
           */
          const Geometry::Point& getPoint() const
          {
            return m_point;
          }

          /**
           * @brief Indicates whether the trace exited or aborted.
           */
          bool exited() const
          {
            return m_exited;
          }

          /**
           * @brief Returns the additive correction accumulated during tracing.
           */
          Real getCorrection() const
          {
            return m_correction;
          }

        private:
          bool m_exited;
          Real m_time;
          Geometry::Point m_point;
          Real m_correction;
      };

      /**
       * @brief Constructs a flow operator.
       *
       * Default tracing parameters:
       * - max zero hops: 128
       * - max bisections: 16
       * - max subdivisions: 8
       * - max outer iterations: 100000
       * - max stagnations: 512
       * - face trials: 6
       * - bracket growth: 2.0
       * - max bracket expansions: 3
       * - step safety: 0.5
       * - min step factor: 10
       * - tolerance factor: 50
       * - clamp factor: 10
       *
       * @param t   Signed tracing time.
       * @param u   Operand function.
       * @param vel Velocity field.
       * @param st  Time integrator.
       * @param bp  Boundary policy.
       */
      template <class VVel, class S = StepType, class B = BoundaryPolicy>
      Flow(const Real& t,
           const Operand& u,
           VVel&& vel,
           S&& st = S{},
           B&& bp = B{})
        : m_maxZeroHops(128),
          m_maxBisections(16),
          m_maxSubdivisions(8),
          m_maxOuterIterations(100000),
          m_maxStagnations(512),
          m_faceTrials(6),
          m_bracketGrowth(Real(2.0)),
          m_maxBracketExpansions(3),
          m_stepSafety(Real(0.5)),
          m_minStepFactor(Real(10)),
          m_tolFactor(Real(50)),
          m_clampFactor(Real(10)),
          m_t(t),
          m_operand(u.copy()),
          m_velocity(std::forward<VVel>(vel)),
          m_step(std::forward<S>(st)),
          m_bp(std::forward<B>(bp)),
          m_p(nullptr)
      {}

      Flow(const Flow& other)
        : Parent(other),
          m_maxZeroHops(other.m_maxZeroHops),
          m_maxBisections(other.m_maxBisections),
          m_maxSubdivisions(other.m_maxSubdivisions),
          m_maxOuterIterations(other.m_maxOuterIterations),
          m_maxStagnations(other.m_maxStagnations),
          m_faceTrials(other.m_faceTrials),
          m_bracketGrowth(other.m_bracketGrowth),
          m_maxBracketExpansions(other.m_maxBracketExpansions),
          m_stepSafety(other.m_stepSafety),
          m_minStepFactor(other.m_minStepFactor),
          m_tolFactor(other.m_tolFactor),
          m_clampFactor(other.m_clampFactor),
          m_t(other.m_t),
          m_operand(other.m_operand->copy()),
          m_velocity(other.m_velocity),
          m_step(other.m_step),
          m_bp(other.m_bp),
          m_p(other.m_p)
      {}

      Flow(Flow&& other)
        : Parent(std::move(other)),
          m_maxZeroHops(std::move(other.m_maxZeroHops)),
          m_maxBisections(std::move(other.m_maxBisections)),
          m_maxSubdivisions(std::move(other.m_maxSubdivisions)),
          m_maxOuterIterations(std::move(other.m_maxOuterIterations)),
          m_maxStagnations(std::move(other.m_maxStagnations)),
          m_faceTrials(std::move(other.m_faceTrials)),
          m_bracketGrowth(std::move(other.m_bracketGrowth)),
          m_maxBracketExpansions(std::move(other.m_maxBracketExpansions)),
          m_stepSafety(std::move(other.m_stepSafety)),
          m_minStepFactor(std::move(other.m_minStepFactor)),
          m_tolFactor(std::move(other.m_tolFactor)),
          m_clampFactor(std::move(other.m_clampFactor)),
          m_t(std::move(other.m_t)),
          m_operand(std::move(other.m_operand)),
          m_velocity(std::move(other.m_velocity)),
          m_step(std::move(other.m_step)),
          m_bp(std::move(other.m_bp)),
          m_p(std::exchange(other.m_p, nullptr))
      {}

      /**
       * @brief Traces the characteristic starting at @p p.
       *
       * The tracing algorithm:
       * - consumes the remaining time by repeated cell-local advances,
       * - detects the earliest face crossing when needed,
       * - hops across interior faces,
       * - delegates boundary handling to the boundary policy,
       * - aborts safely if it detects non-progress.
       *
       * @param p Starting point.
       * @returns Trace result.
       */
      Trace trace(const Geometry::Point& p) const
      {
        struct Candidate
        {
          Real tlin;   ///< Linearized face hit time.
          size_t j;    ///< Local face index.
          Real ndv;    ///< @f$ n_{\text{ref}}\cdot v_{\text{ref}} @f$ at the start.
          Real phi0;   ///< Initial face function value.
          Index fid;   ///< Global face index.
        };

        size_t outerIterations = 0;
        size_t stagnantIterations = 0;

        const size_t maxZeroHops = m_maxZeroHops;
        const size_t maxBisections = m_maxBisections;
        const size_t maxSubdivisions = m_maxSubdivisions;
        const size_t maxOuterIterations = m_maxOuterIterations;
        const size_t maxStagnations = m_maxStagnations;
        const size_t faceTrials = m_faceTrials;
        const Real bracketGrowth = m_bracketGrowth;
        const size_t maxBracketExpansions = m_maxBracketExpansions;
        const Real stepSafety = m_stepSafety;
        const Real minStepFactor = m_minStepFactor;
        const Real tolFactor = m_tolFactor;
        const Real clampFactor = m_clampFactor;

        const auto& poly0 = p.getPolytope();
        const auto& mesh = poly0.getMesh();
        const size_t cd = mesh.getDimension();
        const auto& conn = mesh.getConnectivity();

        Real correction = Real(0);

        Real tau = std::abs(m_t);
        const Real sgn = Math::sgn(m_t);

        const Real epsMachine = std::numeric_limits<Real>::epsilon();
        const Real sqrtEps = std::sqrt(epsMachine);
        const Real vFloor = std::numeric_limits<Real>::min();

        auto isFinite = [](Real v) -> bool
        {
          return std::isfinite(v);
        };

        auto dot = [](const auto& a, const auto& b) -> Real
        {
          return b.dot(a);
        };

        auto norm2 = [&](const auto& v) -> Real
        {
          const Real v2 = dot(v, v);
          return std::max<Real>(Real(0), v2);
        };

        // Normalize the velocity return type in one place.
        auto vphysOf = [&](const Geometry::Point& qp) -> Math::SpatialVector<Real>
        {
          // If m_velocity(qp) is already vector-like, replace the next line by:
          // return m_velocity(qp);
          return m_velocity(qp).col(0);
        };

        // Thread-local scratch buffers to reduce temporary allocations.
        static thread_local Index s_cell;
        static thread_local Math::SpatialPoint s_rc{{}}, s_rc1{{}}, s_rcTmp{{}},
                                              s_rEval{{}}, s_rIn{{}};
        static thread_local Math::SpatialPoint s_pc{{}}, s_x{{}}, s_xIn{{}}, s_xFace{{}};
        static thread_local std::vector<Candidate> s_candidates;
        static thread_local std::vector<size_t> s_faceSet;

        // Locate the starting cell and reference coordinates.
        s_cell = Index(-1);

        if (poly0.getDimension() == cd)
        {
          s_cell = poly0.getIndex();
          s_rc = p.getReferenceCoordinates();
        }
        else if (poly0.getDimension() == cd - 1)
        {
          const Index f = poly0.getIndex();
          const auto& adj = conn.getIncidence(cd - 1, cd).at(f);

          if (mesh.isBoundary(f))
          {
            const Index c = adj[0];
            mesh.getPolytopeTransformation(cd, c).inverse(s_rcTmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c)).cell(s_rc, s_rcTmp);
            s_cell = c;
          }
          else
          {
            const Index c0 = adj[0];
            const Index c1 = adj[1];

            mesh.getPolytopeTransformation(cd, c0).inverse(s_rcTmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c0)).cell(s_rc1, s_rcTmp);
            const Math::SpatialPoint rc0 = s_rc1;

            mesh.getPolytopeTransformation(cd, c1).inverse(s_rcTmp, p.getPhysicalCoordinates());
            Geometry::Polytope::Project(mesh.getGeometry(cd, c1)).cell(s_rc1, s_rcTmp);
            const Math::SpatialPoint rc1 = s_rc1;

            const auto& faces0 = conn.getIncidence(cd, cd - 1).at(c0);
            size_t j0 = faces0.size();
            for (size_t k = 0; k < faces0.size(); ++k)
            {
              if (faces0[k] == f)
              {
                j0 = k;
                break;
              }
            }

            const auto g0 = mesh.getGeometry(cd, c0);
            const Geometry::Polytope::Traits ts0(g0);
            const auto& hs0 = ts0.getHalfSpace();
            const Math::SpatialVector<Real> nref0 = hs0.matrix.row(j0).transpose();

            const auto it0 = mesh.getPolytope(cd, c0);
            const auto& cell0 = *it0;
            const Geometry::Point q0(cell0, rc0, p.getPhysicalCoordinates());
            const auto vref0 = (sgn * q0.getJacobianInverse() * vphysOf(q0));
            const Real ndv0 = dot(nref0, vref0);

            auto interiorScore = [&](Index c, const Math::SpatialPoint& rproj) -> Real
            {
              const auto gc = mesh.getGeometry(cd, c);
              const Geometry::Polytope::Traits tsc(gc);
              const auto& hsc = tsc.getHalfSpace();

              Real s = std::numeric_limits<Real>::infinity();
              for (size_t j = 0; j < static_cast<size_t>(hsc.vector.size()); ++j)
              {
                const auto n = hsc.matrix.row(j);
                const Real b = hsc.vector[j];
                s = std::min(s, b - rproj.dot(n));
              }
              return s;
            };

            const Real epsNdv0 = Real(10) * sqrtEps;
            if (std::abs(ndv0) <= epsNdv0)
            {
              const Real s0 = interiorScore(c0, rc0);
              const Real s1 = interiorScore(c1, rc1);
              if (s1 > s0)
              {
                s_cell = c1;
                s_rc = rc1;
              }
              else
              {
                s_cell = c0;
                s_rc = rc0;
              }
            }
            else if (ndv0 > 0)
            {
              s_cell = c1;
              s_rc = rc1;
            }
            else
            {
              s_cell = c0;
              s_rc = rc0;
            }
          }
        }
        else
        {
          return Trace{ true, Real(0), p, correction };
        }

        // Resize scratch buffers.
        s_rc1.resize(s_rc.size());
        s_rcTmp.resize(s_rc.size());
        s_rEval.resize(s_rc.size());
        s_rIn.resize(s_rc.size());

        s_pc.resize(p.getPhysicalCoordinates().size());
        s_x.resize(s_pc.size());
        s_xIn.resize(s_pc.size());
        s_xFace.resize(s_pc.size());

        // Avoid immediate backtracking if there are alternatives.
        std::optional<size_t> lastFace;

        auto phiFace = [&](const auto& hs, size_t j, const Math::SpatialPoint& r) -> Real
        {
          const auto n = hs.matrix.row(j);
          const Real b = hs.vector[j];
          return b - r.dot(n);
        };

        auto clampIfOutside = [&](const auto& hs,
                                  const auto& g,
                                  Math::SpatialPoint& r,
                                  Real epsPhi) -> void
        {
          bool violated = false;
          for (size_t j = 0; j < static_cast<size_t>(hs.vector.size()); ++j)
          {
            if (phiFace(hs, j, r) < -clampFactor * epsPhi)
            {
              violated = true;
              break;
            }
          }

          if (violated)
          {
            Geometry::Polytope::Project(g).cell(s_rc1, r);
            r = s_rc1;
          }
        };

        while (tau > 0)
        {
          if (++outerIterations > maxOuterIterations)
          {
            const auto itf = mesh.getPolytope(cd, s_cell);
            return Trace{ true, tau, Geometry::Point(*itf, s_rc), correction };
          }

          const Real tauBeforeLoop = tau;
          const Index cellBeforeLoop = s_cell;
          const Math::SpatialPoint rcBeforeLoop = s_rc;

          const auto itc = mesh.getPolytope(cd, s_cell);
          const auto& cell = *itc;

          const auto g = mesh.getGeometry(cd, s_cell);
          const Geometry::Polytope::Traits ts(g);
          const auto& faces = conn.getIncidence(cd, cd - 1).at(s_cell);
          const auto& hs = ts.getHalfSpace();

          auto vref = [&](const Math::SpatialPoint& r) -> Math::SpatialVector<Real>
          {
            const Geometry::Point qp(cell, r);
            return (sgn * qp.getJacobianInverse() * vphysOf(qp));
          };

          auto advance = [&](Math::SpatialPoint& rout, Real dt, const Math::SpatialPoint& rin)
          {
            m_step.step(
              rout, dt, rin,
              [&](const Math::SpatialPoint& rr) -> Math::SpatialVector<Real>
              {
                return vref(rr);
              });
          };

          mesh.getPolytopeTransformation(cd, s_cell).transform(s_x, s_rc);

          const Real rnorm = std::sqrt(norm2(s_rc));
          const auto v0 = vref(s_rc);
          const Real vrefMag = std::sqrt(norm2(v0));

          const Real epsPhi = tolFactor * sqrtEps * (Real(1) + rnorm);
          const Real epsNdv = tolFactor * sqrtEps * (Real(1) + vrefMag);

          Real dtCap = tau;
          {
            const auto rcent = ts.getCentroid();
            s_rIn = rcent;
            mesh.getPolytopeTransformation(cd, s_cell).transform(s_xIn, s_rIn);

            const Geometry::Point qJ(cell, s_rIn, s_xIn);
            const auto JinvT = qJ.getJacobianInverse().transpose();

            Real hScale = Real(0);

            for (size_t j = 0; j < faces.size(); ++j)
            {
              const Math::SpatialVector<Real> nref = hs.matrix.row(j).transpose();
              auto n_u = JinvT * nref;
              const Real nn = std::sqrt(std::max<Real>(Real(0), dot(n_u, n_u)));
              if (!(nn > Real(0)) || !isFinite(nn))
                continue;

              Geometry::Polytope::Project(g).face(j, s_rcTmp, s_rIn);
              mesh.getPolytopeTransformation(cd, s_cell).transform(s_xFace, s_rcTmp);

              Real c_u = dot(n_u, s_xFace);
              const Real sdIn = c_u - dot(n_u, s_xIn);
              if (sdIn < 0)
              {
                n_u = -n_u;
                c_u = -c_u;
              }

              const Real d = (c_u - dot(n_u, s_xIn)) / nn;
              if (isFinite(d))
                hScale = std::max(hScale, d);
            }

            Real vphysMag = Real(0);
            {
              const Geometry::Point qp(cell, s_rc, s_x);
              const auto vphys = vphysOf(qp);
              vphysMag = std::sqrt(norm2(vphys));
              if (!isFinite(vphysMag))
                vphysMag = Real(0);
            }

            if (hScale > Real(0) && isFinite(hScale))
            {
              dtCap = std::min(dtCap, stepSafety * hScale / std::max<Real>(vphysMag, vFloor));
            }

            if (!(dtCap > Real(0)) || !isFinite(dtCap))
              dtCap = tau;
          }

          const Real dtMin =
            minStepFactor * sqrtEps * (Real(1) + rnorm) / std::max<Real>(Real(1), vrefMag);

          std::optional<Trace> exitTrace;

          auto doZeroHops = [&]() -> bool
          {
            size_t hops = 0;
            while (hops++ < maxZeroHops)
            {
              const auto vz = vref(s_rc);

              s_faceSet.clear();
              s_faceSet.reserve(faces.size());

              bool haveNonLast = false;
              for (size_t j = 0; j < faces.size(); ++j)
              {
                const Real ph = phiFace(hs, j, s_rc);
                if (std::abs(ph) > epsPhi)
                  continue;

                const Math::SpatialVector<Real> nref = hs.matrix.row(j).transpose();
                const Real ndv = dot(nref, vz);
                if (!(ndv > epsNdv))
                  continue;

                const bool isLast = (lastFace && j == *lastFace);
                if (!isLast)
                  haveNonLast = true;

                s_faceSet.push_back(j);
              }

              if (s_faceSet.empty())
                break;

              auto key = [&](size_t j) -> std::tuple<Real, Real, Index>
              {
                const Real ph = phiFace(hs, j, s_rc);
                const auto vz2 = vref(s_rc);
                const Real ndv = vz2.dot(hs.matrix.row(j).transpose());
                const Index fid = faces[j];
                return { std::abs(ph), -ndv, fid };
              };

              size_t best = size_t(-1);
              bool have = false;
              for (size_t jj : s_faceSet)
              {
                if (haveNonLast && lastFace && jj == *lastFace)
                  continue;

                if (!have)
                {
                  best = jj;
                  have = true;
                }
                else if (key(jj) < key(best))
                {
                  best = jj;
                }
              }

              if (!have)
                break;

              const Index f = faces[best];

              if (mesh.isBoundary(f))
              {
                BoundaryHit bh{ tau, s_cell, s_rc, best, correction };
                if (!m_bp(bh))
                {
                  exitTrace.emplace(true, tau, Geometry::Point(cell, s_rc), correction);
                  return false;
                }
                lastFace.reset();
                break;
              }

              mesh.getPolytopeTransformation(cd, s_cell).transform(s_pc, s_rc);
              const auto& nbrs = conn.getIncidence(cd - 1, cd).at(f);
              if (nbrs.size() != 2)
                return false;

              s_cell = (nbrs[0] == s_cell) ? nbrs[1] : nbrs[0];

              mesh.getPolytopeTransformation(cd, s_cell).inverse(s_rc, s_pc);
              Geometry::Polytope::Project(mesh.getGeometry(cd, s_cell)).cell(s_rc1, s_rc);
              s_rc = s_rc1;

              const auto& facesNew = conn.getIncidence(cd, cd - 1).at(s_cell);
              lastFace.reset();
              for (size_t j = 0; j < facesNew.size(); ++j)
              {
                if (facesNew[j] == f)
                {
                  lastFace = j;
                  break;
                }
              }

              return true;
            }

            return false;
          };

          if (doZeroHops())
          {
            const Real rcMove2 = (s_rc - rcBeforeLoop).squaredNorm();
            const bool sameTau = !(tau < tauBeforeLoop);
            const bool sameCell = (s_cell == cellBeforeLoop);
            const bool sameRc = rcMove2 <= Real(100) * epsMachine;

            if (sameTau && sameCell && sameRc)
            {
              const auto itf = mesh.getPolytope(cd, s_cell);
              return Trace{ true, tau, Geometry::Point(*itf, s_rc), correction };
            }

            if (sameTau)
            {
              if (++stagnantIterations > maxStagnations)
              {
                const auto itf = mesh.getPolytope(cd, s_cell);
                return Trace{ true, tau, Geometry::Point(*itf, s_rc), correction };
              }
            }
            else
            {
              stagnantIterations = 0;
            }

            continue;
          }

          if (exitTrace)
            return *exitTrace;

          Real tauCell = std::min(tau, dtCap);

          bool foundEvent = false;
          size_t jStar = 0;
          Real hiStar = Real(0);

          auto phiAtTime = [&](size_t j, Real t, Math::SpatialPoint& rOut) -> Real
          {
            advance(rOut, t, s_rc);
            return phiFace(hs, j, rOut);
          };

          auto tryBracketFace = [&](size_t j, Real t0, Real& hiOut) -> bool
          {
            Real t = std::min(t0, tauCell);
            if (!(t > Real(0)) || !isFinite(t))
              return false;

            Real ph = phiAtTime(j, t, s_rEval);
            if (!isFinite(ph))
              return false;

            if (ph <= Real(0))
            {
              hiOut = t;
              return true;
            }

            Real texp = t;
            for (size_t k = 0; k < maxBracketExpansions; ++k)
            {
              const Real tnext = std::min(tauCell, bracketGrowth * texp);
              if (!(tnext > texp))
                break;

              texp = tnext;
              ph = phiAtTime(j, texp, s_rEval);
              if (!isFinite(ph))
                return false;

              if (ph <= Real(0))
              {
                hiOut = texp;
                return true;
              }
            }

            if (texp < tauCell)
            {
              ph = phiAtTime(j, tauCell, s_rEval);
              if (isFinite(ph) && ph <= Real(0))
              {
                hiOut = tauCell;
                return true;
              }
            }

            return false;
          };

          for (size_t subdiv = 0; subdiv <= maxSubdivisions; ++subdiv)
          {
            s_candidates.clear();
            s_candidates.reserve(faces.size());

            for (size_t j = 0; j < faces.size(); ++j)
            {
              const Real phi0 = phiFace(hs, j, s_rc);

              if (!(phi0 > epsPhi))
                continue;

              const Math::SpatialVector<Real> nref = hs.matrix.row(j).transpose();
              const Real ndv = dot(nref, v0);
              if (!(ndv > epsNdv))
                continue;

              const Real tlin = phi0 / ndv;
              if (!(tlin > Real(0)) || !isFinite(tlin))
                continue;
              if (tlin > tauCell)
                continue;

              s_candidates.push_back(Candidate{ tlin, j, ndv, phi0, faces[j] });
            }

            if (s_candidates.empty())
            {
              foundEvent = false;
              break;
            }

            std::sort(
              s_candidates.begin(),
              s_candidates.end(),
              [](const Candidate& a, const Candidate& b)
              {
                if (a.tlin != b.tlin)
                  return a.tlin < b.tlin;
                if (a.ndv != b.ndv)
                  return a.ndv > b.ndv;
                return a.fid < b.fid;
              });

            const size_t ntry = std::min(faceTrials, s_candidates.size());

            auto consider = [&](size_t begin, size_t end)
            {
              for (size_t k = begin; k < end; ++k)
              {
                const auto& c = s_candidates[k];

                if (lastFace && c.j == *lastFace && s_candidates.size() > 1)
                  continue;

                Real hi = Real(0);
                if (!tryBracketFace(c.j, c.tlin, hi))
                  continue;

                if (!foundEvent || hi < hiStar)
                {
                  foundEvent = true;
                  jStar = c.j;
                  hiStar = hi;
                }
              }
            };

            foundEvent = false;
            consider(0, ntry);
            if (!foundEvent)
              consider(ntry, s_candidates.size());

            if (foundEvent)
              break;

            tauCell *= Real(0.5);
            if (tauCell <= dtMin || !isFinite(tauCell))
              break;
          }

          if (!foundEvent)
          {
            if (!isFinite(tauCell) || !(tauCell > Real(0)))
            {
              return Trace{ true, tau, Geometry::Point(cell, s_rc), correction };
            }

            const Real tauStep = tauCell;

            const Real tauBefore = tau;
            const Math::SpatialPoint rcBefore = s_rc;

            advance(s_rc1, tauStep, s_rc);
            s_rc = s_rc1;

            clampIfOutside(hs, g, s_rc, epsPhi);

            tau -= tauStep;

            const Real rcMove2 = (s_rc - rcBefore).squaredNorm();
            const bool timeProgress = (tau < tauBefore);
            const bool spaceProgress = rcMove2 > Real(100) * epsMachine;

            if (!timeProgress && !spaceProgress)
            {
              // Remaining step is numerically negligible: finish successfully at current point.
              tau = Real(0);
            }

            continue;
          }

          const Real phi0Star = phiFace(hs, jStar, s_rc);
          if (!(phi0Star > Real(0)))
          {
            Geometry::Polytope::Project(g).cell(s_rc1, s_rc);
            s_rc = s_rc1;
            continue;
          }

          const Real ndv0 = dot(hs.matrix.row(jStar).transpose(), v0);
          const Real dtTol =
            std::max<Real>(Real(1e-12), epsPhi / std::max<Real>(ndv0, vFloor));

          Real lo = Real(0);
          Real hi = hiStar;

          for (size_t it = 0; it < maxBisections; ++it)
          {
            if (hi - lo <= dtTol)
              break;

            const Real mid = Real(0.5) * (lo + hi);
            const Real phm = phiAtTime(jStar, mid, s_rEval);

            if (!isFinite(phm))
            {
              hi = mid;
              continue;
            }

            if (phm > Real(0))
              lo = mid;
            else
              hi = mid;
          }

          const Real thit = hi;

          advance(s_rc1, thit, s_rc);
          Geometry::Polytope::Project(g).face(jStar, s_rc, s_rc1);
          s_rc = s_rc1;

          Geometry::Polytope::Project(g).cell(s_rc1, s_rc);
          s_rc = s_rc1;

          tau -= thit;

          const Index faceHit = faces[jStar];

          mesh.getPolytopeTransformation(cd, s_cell).transform(s_pc, s_rc);

          if (mesh.isBoundary(faceHit))
          {
            const Real tauBeforeBp = tau;
            const Index cellBeforeBp = s_cell;
            const Math::SpatialPoint rcBeforeBp = s_rc;
            const Real correctionBeforeBp = correction;

            BoundaryHit bh{ tau, s_cell, s_rc, jStar, correction };
            if (!m_bp(bh))
              return Trace{ true, tau, Geometry::Point(*itc, s_rc), correction };

            const Real rcMove2 = (s_rc - rcBeforeBp).squaredNorm();
            const bool progressed =
                 (tau < tauBeforeBp)
              || (s_cell != cellBeforeBp)
              || (rcMove2 > Real(100) * epsMachine)
              || (correction != correctionBeforeBp);

            if (!progressed)
            {
              return Trace{ true, tau, Geometry::Point(*itc, s_rc), correction };
            }

            lastFace.reset();
            continue;
          }

          {
            const auto& nbrs = conn.getIncidence(cd - 1, cd).at(faceHit);
            if (nbrs.size() != 2)
              return Trace{ true, tau, Geometry::Point(*itc, s_rc), correction };
            s_cell = (nbrs[0] == s_cell) ? nbrs[1] : nbrs[0];
          }

          mesh.getPolytopeTransformation(cd, s_cell).inverse(s_rc, s_pc);
          Geometry::Polytope::Project(mesh.getGeometry(cd, s_cell)).cell(s_rc1, s_rc);
          s_rc = s_rc1;

          {
            const auto& facesNew = conn.getIncidence(cd, cd - 1).at(s_cell);
            lastFace.reset();
            for (size_t j = 0; j < facesNew.size(); ++j)
            {
              if (facesNew[j] == faceHit)
              {
                lastFace = j;
                break;
              }
            }
          }
        }

        const auto itf = mesh.getPolytope(cd, s_cell);
        return Trace{ false, tau, Geometry::Point(*itf, s_rc), correction };
      }

      /**
       * @brief Evaluates the flowed function at a point.
       *
       * If tracing exits or aborts before completion, this default implementation
       * returns zero.
       */
      constexpr
      auto getValue(const Geometry::Point& p) const
      {
        const auto tr = this->trace(p);
        if (tr.exited())
          return Real(0);
        return m_operand->getValue(tr.getPoint()) + tr.getCorrection();
      }

      constexpr
      const auto& getLeaf() const
      {
        return m_operand->getLeaf();
      }

      /**
       * @brief Returns the operand function.
       */
      const auto& getOperand() const
      {
        assert(m_operand);
        return *m_operand;
      }

      /**
       * @brief Returns the velocity field.
       */
      const auto& getVelocity() const
      {
        return m_velocity;
      }

      /**
       * @brief Returns the time integrator.
       */
      const auto& getStep() const
      {
        return m_step;
      }

      /**
       * @brief Returns the boundary policy.
       */
      const auto& getBoundaryPolicy() const
      {
        return m_bp;
      }

      /**
       * @brief Sets the maximum number of zero-time face hops.
       *
       * Default value: 128.
       */
      Flow& setMaxZeroHops(size_t value)
      {
        m_maxZeroHops = value;
        return *this;
      }

      /**
       * @brief Sets the maximum number of bisection iterations used to refine a
       *        face hit time.
       *
       * Default value: 16.
       */
      Flow& setMaxBisections(size_t value)
      {
        m_maxBisections = value;
        return *this;
      }

      /**
       * @brief Sets the maximum number of adaptive subdivisions used when
       *        bracketing fails.
       *
       * Default value: 8.
       */
      Flow& setMaxSubdivisions(size_t value)
      {
        m_maxSubdivisions = value;
        return *this;
      }

      /**
       * @brief Sets the maximum number of outer trace loop iterations.
       *
       * Default value: 100000.
       */
      Flow& setMaxOuterIterations(size_t value)
      {
        m_maxOuterIterations = value;
        return *this;
      }

      /**
       * @brief Sets the maximum number of consecutive stagnating iterations
       *        tolerated before aborting.
       *
       * Default value: 512.
       */
      Flow& setMaxStagnations(size_t value)
      {
        m_maxStagnations = value;
        return *this;
      }

      /**
       * @brief Sets how many candidate faces are tried first after sorting by
       *        predicted hit time.
       *
       * Default value: 6.
       */
      Flow& setFaceTrials(size_t value)
      {
        m_faceTrials = value;
        return *this;
      }

      /**
       * @brief Sets the multiplicative growth factor used when expanding a face
       *        hit bracket.
       *
       * Default value: 2.0.
       */
      Flow& setBracketGrowth(Real value)
      {
        m_bracketGrowth = value;
        return *this;
      }

      /**
       * @brief Sets the maximum number of bracket expansion attempts per face.
       *
       * Default value: 3.
       */
      Flow& setMaxBracketExpansions(size_t value)
      {
        m_maxBracketExpansions = value;
        return *this;
      }

      /**
       * @brief Sets the safety factor used in the local per-cell time-step cap.
       *
       * Smaller values are more conservative.
       *
       * Default value: 0.5.
       */
      Flow& setStepSafety(Real value)
      {
        m_stepSafety = value;
        return *this;
      }

      /**
       * @brief Sets the factor used to define the minimum admissible substep.
       *
       * Default value: 10.
       */
      Flow& setMinStepFactor(Real value)
      {
        m_minStepFactor = value;
        return *this;
      }

      /**
       * @brief Sets the factor multiplying @f$ \sqrt{\varepsilon} @f$ in the
       *        geometric and directional tolerances.
       *
       * Default value: 50.
       */
      Flow& setTolFactor(Real value)
      {
        m_tolFactor = value;
        return *this;
      }

      /**
       * @brief Sets the factor controlling when a point is considered far enough
       *        outside a cell to be clamped back inside.
       *
       * Default value: 10.
       */
      Flow& setClampFactor(Real value)
      {
        m_clampFactor = value;
        return *this;
      }

      Optional<size_t> getOrder(const Geometry::Polytope&) const
      {
        return {};
      }

      virtual Flow* copy() const noexcept override
      {
        return new Flow(*this);
      }

    private:
      size_t m_maxZeroHops;
      size_t m_maxBisections;
      size_t m_maxSubdivisions;
      size_t m_maxOuterIterations;
      size_t m_maxStagnations;
      size_t m_faceTrials;
      Real m_bracketGrowth;
      size_t m_maxBracketExpansions;
      Real m_stepSafety;
      Real m_minStepFactor;
      Real m_tolFactor;
      Real m_clampFactor;

      const Real m_t;
      std::unique_ptr<Operand> m_operand;
      VectorFieldType m_velocity;
      Step m_step;
      BoundaryPolicy m_bp;
      const Geometry::Point* m_p;
  };

  template <class Derived, class Velocity>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&)
    -> Flow<
         FunctionBase<Derived>,
         Velocity,
         Math::RungeKutta::RK4,
         DefaultBoundaryPolicy>;

  template <class Derived, class Velocity, class Step>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&, Step&&)
    -> Flow<
         FunctionBase<Derived>,
         Velocity,
         Step,
         DefaultBoundaryPolicy>;

  template <class Derived, class Velocity, class Step, class BBP>
  Flow(const Real&, const FunctionBase<Derived>&, Velocity&&, Step&&, BBP&&)
    -> Flow<FunctionBase<Derived>, Velocity, Step, BBP>;
}

#endif
