#ifndef RODIN_CONFIGURE_H
#define RODIN_CONFIGURE_H

/* #undef RODIN_WITH_PY */
/* #undef RODIN_WITH_PLOT */
/* #undef RODIN_USE_MPI */
/* #undef RODIN_USE_OPENMP */
#define RODIN_USE_SUITESPARSE
/* #undef RODIN_SILENCE_WARNINGS */

#define RODIN_MAXIMAL_SPACE_DIMENSION 3
#define RODIN_DEFAULT_SIMPLEX_ATTRIBUTE 1
#define RODIN_DEFAULT_GRIDFUNCTION_SAVE_PRECISION 8
#define RODIN_MAGIC_FUZZY_CONSTANT 0

#endif
