/*
 *          Copyright Carlos BRITO PACHECO 2021 - 2026.
 * Distributed under the Boost Software License, Version 1.0.
 *       (See accompanying file LICENSE or copy at
 *          https://www.boost.org/LICENSE_1_0.txt)
 */
/**
 * @file
 * @brief Shared plumbing for the coefficient generation drivers.
 *
 * The two families are generated by two drivers, one each, so that the binary
 * says which table it writes. What they share is the checking and the
 * printing, which lives here rather than being written twice: a rule reaches a
 * table only after it has been measured, and it should be measured the same
 * way whichever construction produced it.
 */
#ifndef RODIN_TESTS_UNIT_QF_TABLEEMITTER_H
#define RODIN_TESTS_UNIT_QF_TABLEEMITTER_H

#include <cstdio>
#include <string>

#include "QuadratureInvariants.h"
#include "Rodin/Geometry/Polytope.h"

namespace Rodin::Tests::QF
{
  /// @brief The element a short name refers to, the triangle by default.
  inline Geometry::Polytope::Type elementOf(const std::string& name)
  {
    if (name == "tet")
      return Geometry::Polytope::Type::Tetrahedron;
    if (name == "wedge")
      return Geometry::Polytope::Type::Wedge;
    if (name == "pyr")
      return Geometry::Polytope::Type::Pyramid;
    if (name == "quad")
      return Geometry::Polytope::Type::Quadrilateral;
    if (name == "hex")
      return Geometry::Polytope::Type::Hexahedron;
    return Geometry::Polytope::Type::Triangle;
  }

  /**
   * @brief Measures a rule and prints it as a table entry, or says why not.
   *
   * A table is worth having only if what it holds is exact, so nothing is
   * printed that the moment oracle has not passed, and a rejection is printed
   * in its place rather than silently skipped.
   *
   * @returns Whether the rule was accepted.
   */
  template <class Rule>
  bool emitEntry(const Rule& rule, Geometry::Polytope::Type g, size_t degree)
  {
    const size_t d = Geometry::Polytope::Traits(g).getDimension();
    const auto report = exactnessSweep(rule, g, degree);
    if (report.worstRelativeError >= 1e-12 || !allWeightsPositive(rule) ||
      !allPointsInside(rule, g, 1e-12))
    {
      std::printf("    // degree %zu: REJECTED (oracle %.2e%s%s)\n", degree,
        report.worstRelativeError, allWeightsPositive(rule) ? "" : ", negative weight",
        allPointsInside(rule, g, 1e-12) ? "" : ", point outside");
      std::fflush(stdout);
      return false;
    }

    std::printf("    // degree %zu: %zu points, oracle %.2e\n", degree, rule.getSize(),
      report.worstRelativeError);
    std::printf("      {\n");
    for (size_t i = 0; i < rule.getSize(); ++i)
    {
      std::printf("        ");
      for (size_t k = 0; k < d; ++k)
        std::printf("%.17g, ", rule.getPoint(i)[static_cast<Eigen::Index>(k)]);
      std::printf("%.17g,\n", rule.getWeight(i));
    }
    std::printf("      },\n");
    std::fflush(stdout);
    return true;
  }
}

#endif
