add_subdirectory(P1)
add_subdirectory(H1)
add_subdirectory(P0)
add_subdirectory(P0_P1)
add_subdirectory(P1_H1)
add_subdirectory(Models)
add_subdirectory(Solver)
add_subdirectory(PreassembledMixed)
add_subdirectory(Assembly)
if (RODIN_USE_PETSC)
  add_subdirectory(PETSc)
endif()

if (RODIN_USE_MPI AND RODIN_USE_PETSC)
  add_subdirectory(MPI)
endif()
