import sympy as sp
x,y,X,Y,t = sp.symbols('x y X Y t', real=True)
A,B,P0,rf,muf,rs,lam,mus = sp.symbols('A B P0 rhoF muF rhoS lamS muS', real=True)
cy0,cyl,cyn,cya,cyr = sp.symbols('cyMu0 cyLambda cyN cyA cyReg', real=True, positive=True)
pi = sp.pi
# ---- manufactured fields ----
s  = sp.sin(pi*t)            # solid time profile, d(0)=0
c  = sp.cos(pi*t)            # fluid time profile
d  = sp.Matrix([A*s*sp.sin(pi*X)*Y, A*s*sp.sin(pi*X)*(1+Y**2)/2])
u  = sp.Matrix([B*c*sp.sin(pi*x)*sp.cos(pi*y), -B*c*sp.cos(pi*x)*sp.sin(pi*y)])
p  = P0*c*sp.sin(pi*x)*sp.sin(pi*y)
assert sp.simplify(sp.diff(u[0],x)+sp.diff(u[1],y))==0
# ---- fluid ----
gu = u.jacobian([x,y])
eps = gu + gu.T
D = eps/2
# Carreau-Yasuda: mu(gdot) = muInf + (mu0 - muInf) (1 + (lambda gdot)^a)^((n-1)/a),
# gdot = sqrt(gammaReg^2 + 2 D:D).  muInf = muF; cyMu0 = muF gives a Newtonian fluid.
gdot = sp.sqrt(cyr**2 + 2*sum(D[i,j]**2 for i in range(2) for j in range(2)))
mu = muf + (cy0 - muf)*(1 + (cyl*gdot)**cya)**((cyn - 1)/cya)
sig = -p*sp.eye(2) + 2*mu*D
divsig = sp.Matrix([sp.diff(sig[i,0],x)+sp.diff(sig[i,1],y) for i in range(2)])
ff = rf*(sp.diff(u,t) + gu*u) - divsig
# ---- solid (compressible neo-Hookean, Rodin convention) ----
F = sp.eye(2) + d.jacobian([X,Y])
J = F.det()
FiT = F.inv().T
P = mus*(F - FiT) + lam*sp.log(J)*FiT
divP = sp.Matrix([sp.diff(P[i,0],X)+sp.diff(P[i,1],Y) for i in range(2)])
fs = rs*sp.diff(d,t,2) - divP
vel = sp.diff(d,t); acc = sp.diff(d,t,2)
Ntop = sp.Matrix([0,1]); Ns = sp.Matrix([0,-1])   # solid outward normals (top, interface)
ttop = P*Ntop
# interface data on Y = 1 (functions of X,t)
phi = {x: X + d[0], y: Y + d[1]}
u_phi = u.subs(phi)
gU = (u_phi - vel)                         # kinematic mismatch u(phi(X)) - ddot(X)
sig_phi = sig.subs(phi)
h = P*Ns - J*sig_phi*FiT*Ns                # dynamic mismatch per reference length
wantX = lambda e: e.subs(Y,1)
out = []
def emit(name, args, exprs):
    reps, red = sp.cse([sp.expand_trig(e) if False else e for e in exprs], optimizations=None)
    body = [f"  inline void {name}({args}, const MMSParams& m, Real* o)", "  {",
            "    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;",
            "    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;",
            "    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;",
            "    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;"]
    for sym,e in reps:
        body.append(f"    const Real {sym} = {sp.cxxcode(e)};")
    for i,e in enumerate(red):
        body.append(f"    o[{i}] = {sp.cxxcode(e)};")
    body.append("  }")
    out.append("\n".join(body))
emit("fluidVelocity","Real x, Real y, Real t",list(u))
emit("fluidPressure","Real x, Real y, Real t",[p])
emit("fluidStress","Real x, Real y, Real t",[sig[0,0],sig[0,1],sig[1,0],sig[1,1]])
emit("fluidViscosity","Real x, Real y, Real t",[mu])
emit("fluidForce","Real x, Real y, Real t",list(ff))
emit("solidDisplacement","Real X, Real Y, Real t",list(d))
emit("solidVelocity","Real X, Real Y, Real t",list(vel))
emit("solidAcceleration","Real X, Real Y, Real t",list(acc))
emit("solidForce","Real X, Real Y, Real t",list(fs))
emit("solidTopTraction","Real X, Real Y, Real t",list(ttop))
emit("interfaceKinematicMismatch","Real X, Real Y, Real t",list(gU))
emit("interfaceDynamicMismatch","Real X, Real Y, Real t",list(h))
import sys, os
dst = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "ManufacturedSolution.h")
hdr = """/*
 * AUTO-GENERATED by generate_mms.py (sympy) -- do not edit by hand.
 *
 * Manufactured solution for the 2D Robin-Robin ALE FSI test (FSITest.cpp).
 *   Viscosity: Carreau-Yasuda, mu_inf = muF (cyMu0 = muF gives Newtonian).
 *   Fluid  (Eulerian x, y):  u = B cos(pi t) (sin(pi x) cos(pi y), -cos(pi x) sin(pi y)),
 *                            p = P0 cos(pi t) sin(pi x) sin(pi y),   div u = 0.
 *   Solid  (reference X, Y): d = A sin(pi t) sin(pi X) (Y, (1 + Y^2)/2).
 *   fluidStress returns sigma_f = -p I + mu (grad u + grad u^T), row-major.
 *   Neo-Hookean (Rodin):     P = mu (F - F^{-T}) + lambda ln(J) F^{-T}.
 *   Interface Sigma_0 = {Y = 1}; solid outward normal N_s = (0, -1).
 *   gU(X,t) = u(X + d(X,t), t) - d_t(X,t)                 (kinematic mismatch)
 *   h(X,t)  = P N_s - J sigma_f(X + d) F^{-T} N_s          (dynamic mismatch, per reference length)
 */
#pragma once
#include <cmath>
#include <numbers>
#include <Rodin/Types.h>

namespace Rodin::Examples::FSITest::MMS
{
  struct MMSParams
  {
      Real A = 0.05;     ///< solid displacement amplitude
      Real B = 0.1;      ///< fluid velocity amplitude
      Real P0 = 1.0;     ///< fluid pressure amplitude
      Real rhoF = 1.0;
      Real muF = 0.1;    ///< Carreau-Yasuda mu_inf
      Real cyMu0 = 0.1;  ///< Carreau-Yasuda mu_0 (= muF: Newtonian)
      Real cyLambda = 5.0;
      Real cyN = 0.3;
      Real cyA = 0.8;
      Real cyReg = 1.0e-3;
      Real rhoS = 1.0;
      Real lamS = 20.0;
      Real muS = 10.0;
  };

"""
open(dst,'w').write(hdr + "\n\n".join(out).replace("M_PI","std::numbers::pi") + "\n}\n")
print("wrote", dst)
# sanity: h vanishes? print magnitude at a point
vals={A:0.05,B:0.1,P0:1,rf:1,muf:0.1,rs:1,lam:20,mus:10,X:0.3,Y:1,t:0.25}
if False: print('h',[sp.N(e.subs(vals)) for e in h],'gU',[sp.N(e.subs(vals)) for e in gU])
