/*
 * AUTO-GENERATED by generate_mms.py (sympy) -- do not edit by hand.
 *
 * Manufactured solution for the 2D Robin-Robin ALE FSI test (FSITest.cpp).
 *   Viscosity: Carreau-Yasuda, mu_inf = muF (cyMu0 = muF gives Newtonian).
 *   Fluid  (Eulerian x, y):  u = B cos(pi t) (sin(pi x) cos(pi y), -cos(pi x) sin(pi y)),
 *                            p = P0 cos(pi t) sin(pi x) sin(pi y),   div u = 0.
 *   Solid  (reference X, Y): d = A sin(pi t) sin(pi X) (Y, (1 + Y^2)/2).
 *   fluidStress returns sigma_f = -p I + mu (grad u + grad u^T), row-major.
 *   Neo-Hookean (Rodin):     P = mu (F - F^{-T}) + lambda ln(J) F^{-T}.
 *   Interface Sigma_0 = {Y = 1}; solid outward normal N_s = (0, -1).
 *   gU(X,t) = u(X + d(X,t), t) - d_t(X,t)                 (kinematic mismatch)
 *   h(X,t)  = P N_s - J sigma_f(X + d) F^{-T} N_s          (dynamic mismatch, per reference length)
 */
#pragma once
#include <cmath>
#include <numbers>
#include <Rodin/Types.h>

namespace Rodin::Examples::FSITest::MMS
{
  struct MMSParams
  {
      Real A = 0.05;     ///< solid displacement amplitude
      Real B = 0.1;      ///< fluid velocity amplitude
      Real P0 = 1.0;     ///< fluid pressure amplitude
      Real rhoF = 1.0;
      Real muF = 0.1;    ///< Carreau-Yasuda mu_inf
      Real cyMu0 = 0.1;  ///< Carreau-Yasuda mu_0 (= muF: Newtonian)
      Real cyLambda = 5.0;
      Real cyN = 0.3;
      Real cyA = 0.8;
      Real cyReg = 1.0e-3;
      Real rhoS = 1.0;
      Real lamS = 20.0;
      Real muS = 10.0;
  };

  inline void fluidVelocity(Real x, Real y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::numbers::pi*y;
    const Real x1 = std::numbers::pi*x;
    const Real x2 = B*std::cos(std::numbers::pi*t);
    o[0] = x2*std::sin(x1)*std::cos(x0);
    o[1] = -x2*std::sin(x0)*std::cos(x1);
  }

  inline void fluidPressure(Real x, Real y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    o[0] = P0*std::sin(std::numbers::pi*x)*std::sin(std::numbers::pi*y)*std::cos(std::numbers::pi*t);
  }

  inline void fluidStress(Real x, Real y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::numbers::pi*x;
    const Real x1 = std::numbers::pi*y;
    const Real x2 = std::cos(std::numbers::pi*t);
    const Real x3 = P0*x2*std::sin(x0)*std::sin(x1);
    const Real x4 = std::cos(x0);
    const Real x5 = std::cos(x1);
    const Real x6 = std::numbers::pi*B*x2*x4*x5*(2*muF + 2*(cyMu0 - muF)*std::pow(std::pow(cyLambda*std::sqrt(4*std::pow(std::numbers::pi, 2)*std::pow(B, 2)*std::pow(x2, 2)*std::pow(x4, 2)*std::pow(x5, 2) + std::pow(cyReg, 2)), cyA) + 1, (cyN - 1)/cyA));
    o[0] = -x3 + x6;
    o[1] = 0;
    o[2] = 0;
    o[3] = -x3 - x6;
  }

  inline void fluidViscosity(Real x, Real y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    o[0] = muF + (cyMu0 - muF)*std::pow(std::pow(cyLambda*std::sqrt(4*std::pow(std::numbers::pi, 2)*std::pow(B, 2)*std::pow(std::cos(std::numbers::pi*t), 2)*std::pow(std::cos(std::numbers::pi*x), 2)*std::pow(std::cos(std::numbers::pi*y), 2) + std::pow(cyReg, 2)), cyA) + 1, (cyN - 1)/cyA);
  }

  inline void fluidForce(Real x, Real y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::numbers::pi*t;
    const Real x1 = std::cos(x0);
    const Real x2 = std::numbers::pi*x;
    const Real x3 = std::cos(x2);
    const Real x4 = std::numbers::pi*y;
    const Real x5 = std::sin(x4);
    const Real x6 = std::numbers::pi*x5;
    const Real x7 = x3*x6;
    const Real x8 = B*std::sin(x0);
    const Real x9 = std::cos(x4);
    const Real x10 = std::sin(x2);
    const Real x11 = std::numbers::pi*x10;
    const Real x12 = std::pow(B, 2)*std::pow(x1, 2);
    const Real x13 = x11*x3;
    const Real x14 = std::pow(x9, 2);
    const Real x15 = x12*x14;
    const Real x16 = std::pow(std::numbers::pi, 2);
    const Real x17 = std::pow(x3, 2);
    const Real x18 = std::pow(cyReg, 2) + 4*x15*x16*x17;
    const Real x19 = std::pow(cyLambda*std::sqrt(x18), cyA);
    const Real x20 = x19 + 1;
    const Real x21 = cyN - 1;
    const Real x22 = std::pow(x20, x21/cyA)*(cyMu0 - muF);
    const Real x23 = B*x1*x16*(2*muF + 2*x22);
    const Real x24 = 8*std::pow(std::numbers::pi, 4)*std::pow(B, 3)*std::pow(x1, 3)*x19*x21*x22/(x18*x20);
    const Real x25 = x12*x6*x9;
    o[0] = P0*x1*x7 + rhoF*(-x11*x8*x9 + x12*x13*std::pow(x5, 2) + x13*x15) + x10*x17*x24*std::pow(x9, 3) + x10*x23*x9;
    o[1] = std::numbers::pi*P0*x1*x10*x9 + rhoF*(std::pow(x10, 2)*x25 + x17*x25 + x7*x8) - x14*x24*std::pow(x3, 3)*x5 - x23*x3*x5;
  }

  inline void solidDisplacement(Real X, Real Y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = A*std::sin(std::numbers::pi*X)*std::sin(std::numbers::pi*t);
    o[0] = Y*x0;
    o[1] = (1.0/2.0)*x0*(std::pow(Y, 2) + 1);
  }

  inline void solidVelocity(Real X, Real Y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::numbers::pi*A*std::sin(std::numbers::pi*X)*std::cos(std::numbers::pi*t);
    o[0] = Y*x0;
    o[1] = (1.0/2.0)*x0*(std::pow(Y, 2) + 1);
  }

  inline void solidAcceleration(Real X, Real Y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::pow(std::numbers::pi, 2)*A*std::sin(std::numbers::pi*X)*std::sin(std::numbers::pi*t);
    o[0] = -Y*x0;
    o[1] = -1.0/2.0*x0*(std::pow(Y, 2) + 1);
  }

  inline void solidForce(Real X, Real Y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::pow(std::numbers::pi, 2);
    const Real x1 = std::numbers::pi*X;
    const Real x2 = std::sin(x1);
    const Real x3 = std::sin(std::numbers::pi*t);
    const Real x4 = A*x3;
    const Real x5 = x2*x4;
    const Real x6 = Y*x5;
    const Real x7 = x0*x6;
    const Real x8 = std::cos(x1);
    const Real x9 = std::numbers::pi*x8;
    const Real x10 = x4*x9;
    const Real x11 = std::pow(Y, 2);
    const Real x12 = -x10*x11 - x10;
    const Real x13 = std::pow(A, 2);
    const Real x14 = std::pow(x3, 2);
    const Real x15 = x13*x14;
    const Real x16 = x15*x2*x9;
    const Real x17 = Y*x16;
    const Real x18 = x11*x16;
    const Real x19 = Y*x10 - 1.0/2.0*x16 + (1.0/2.0)*x18 + x6 + 1;
    const Real x20 = 1.0/x19;
    const Real x21 = 2*x10;
    const Real x22 = Y*x21;
    const Real x23 = 2*x5;
    const Real x24 = Y*x23;
    const Real x25 = x24 + 2;
    const Real x26 = -x16 + x18 + x22 + x25;
    const Real x27 = 1.0/x26;
    const Real x28 = lamS*x20*x27;
    const Real x29 = x28*(x10 + x17 + x5);
    const Real x30 = std::pow(x26, -2);
    const Real x31 = x30*(-2*x17 - x21 - x23);
    const Real x32 = x12*x31;
    const Real x33 = std::log(x19);
    const Real x34 = lamS*x33;
    const Real x35 = x22*x27;
    const Real x36 = std::pow(x8, 2);
    const Real x37 = x0*x15;
    const Real x38 = x36*x37;
    const Real x39 = std::pow(x2, 2);
    const Real x40 = x37*x39;
    const Real x41 = x11*x40;
    const Real x42 = x0*x24 - x11*x38 - x22 + x38 - x40 + x41;
    const Real x43 = x30*x42;
    const Real x44 = x25*x43;
    const Real x45 = std::numbers::pi*A*Y*x3*x8 + (1.0/2.0)*x0*x11*x13*x14*x36 + (1.0/2.0)*x0*x13*x14*x39 - 1.0/2.0*x38 - 1.0/2.0*x41 - x7;
    const Real x46 = (1.0/2.0)*x0*x5*(x11 + 1);
    const Real x47 = x22 + 2;
    const Real x48 = x31*x47;
    const Real x49 = x21*x27;
    o[0] = -muS*(-x32 + x35) - muS*(-x35 - x44 - x7) - rhoS*x7 - x12*x29 - x25*x28*x45 - x32*x34 - x34*x44;
    o[1] = 2*A*lamS*x2*x20*x27*x3*x45 + 2*A*lamS*x2*x3*x30*x33*x42 - muS*(x23*x43 - x46 + x49) - muS*(A*x2*x3 - x48 - x49) - rhoS*x46 - x29*x47 - x34*x48;
  }

  inline void solidTopTraction(Real X, Real Y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::numbers::pi*X;
    const Real x1 = std::sin(x0);
    const Real x2 = std::sin(std::numbers::pi*t);
    const Real x3 = A*x2;
    const Real x4 = x1*x3;
    const Real x5 = std::numbers::pi*std::cos(x0);
    const Real x6 = x3*x5;
    const Real x7 = std::pow(Y, 2);
    const Real x8 = Y*x4;
    const Real x9 = std::pow(A, 2)*x1*std::pow(x2, 2)*x5;
    const Real x10 = x7*x9;
    const Real x11 = Y*x6;
    const Real x12 = 2*x11 + 2;
    const Real x13 = 1.0/(x10 + x12 + 2*x8 - x9);
    const Real x14 = x13*(-x6*x7 - x6);
    const Real x15 = x8 + 1;
    const Real x16 = lamS*std::log((1.0/2.0)*x10 + x11 + x15 - 1.0/2.0*x9);
    const Real x17 = x12*x13;
    o[0] = muS*(-x14 + x4) + x14*x16;
    o[1] = muS*(x15 - x17) + x16*x17;
  }

  inline void interfaceKinematicMismatch(Real X, Real Y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::numbers::pi*t;
    const Real x1 = std::cos(x0);
    const Real x2 = A*std::sin(std::numbers::pi*X);
    const Real x3 = std::numbers::pi*x1*x2;
    const Real x4 = x2*std::sin(x0);
    const Real x5 = std::numbers::pi*(X + Y*x4);
    const Real x6 = (1.0/2.0)*std::pow(Y, 2) + 1.0/2.0;
    const Real x7 = std::numbers::pi*(Y + x4*x6);
    o[0] = B*x1*std::sin(x5)*std::cos(x7) - Y*x3;
    o[1] = -B*x1*std::sin(x7)*std::cos(x5) - x3*x6;
  }

  inline void interfaceDynamicMismatch(Real X, Real Y, Real t, const MMSParams& m, Real* o)
  {
    const Real A=m.A, B=m.B, P0=m.P0, rhoF=m.rhoF, muF=m.muF, rhoS=m.rhoS, lamS=m.lamS, muS=m.muS;
    const Real cyMu0=m.cyMu0, cyLambda=m.cyLambda, cyN=m.cyN, cyA=m.cyA, cyReg=m.cyReg;
    (void)A;(void)B;(void)P0;(void)rhoF;(void)muF;(void)rhoS;(void)lamS;(void)muS;
    (void)cyMu0;(void)cyLambda;(void)cyN;(void)cyA;(void)cyReg;
    const Real x0 = std::numbers::pi*X;
    const Real x1 = std::sin(x0);
    const Real x2 = std::numbers::pi*t;
    const Real x3 = std::sin(x2);
    const Real x4 = A*x3;
    const Real x5 = x1*x4;
    const Real x6 = std::numbers::pi*std::cos(x0);
    const Real x7 = x4*x6;
    const Real x8 = std::pow(Y, 2);
    const Real x9 = -x7*x8 - x7;
    const Real x10 = Y*x5;
    const Real x11 = std::pow(A, 2)*x1*std::pow(x3, 2)*x6;
    const Real x12 = x11*x8;
    const Real x13 = Y*x7;
    const Real x14 = 2*x13 + 2;
    const Real x15 = 1.0/(2*x10 - x11 + x12 + x14);
    const Real x16 = x15*x9;
    const Real x17 = x10 + 1;
    const Real x18 = -1.0/2.0*x11 + (1.0/2.0)*x12 + x13 + x17;
    const Real x19 = lamS*std::log(x18);
    const Real x20 = std::cos(x2);
    const Real x21 = std::numbers::pi*(X + x10);
    const Real x22 = std::numbers::pi*(Y + (1.0/2.0)*x5*(x8 + 1));
    const Real x23 = P0*x20*std::sin(x21)*std::sin(x22);
    const Real x24 = std::cos(x21);
    const Real x25 = std::cos(x22);
    const Real x26 = std::numbers::pi*B*x20*x24*x25*(2*muF + 2*(cyMu0 - muF)*std::pow(std::pow(cyLambda*std::sqrt(4*std::pow(std::numbers::pi, 2)*std::pow(B, 2)*std::pow(x20, 2)*std::pow(x24, 2)*std::pow(x25, 2) + std::pow(cyReg, 2)), cyA) + 1, (cyN - 1)/cyA));
    const Real x27 = x14*x15;
    o[0] = -muS*(-x16 + x5) + x15*x18*x9*(-x23 + x26) - x16*x19;
    o[1] = -muS*(x17 - x27) + x14*x15*x18*(-x23 - x26) - x19*x27;
  }
}
