/*
 *          Copyright Carlos BRITO PACHECO 2021 - 2022.
 * Distributed under the Boost Software License, Version 1.0.
 *       (See accompanying file LICENSE or copy at
 *          https://www.boost.org/LICENSE_1_0.txt)
 */
/**
 * @file LevelSetDiscretizer.h
 * @brief Level-set based implicit-domain discretization utilities.
 */
#ifndef RODIN_EXTERNAL_MMG_IMPLICITDOMAINMESHER_H
#define RODIN_EXTERNAL_MMG_IMPLICITDOMAINMESHER_H

#include "Mesh.h"

#include "MMG5.h"
#include "Common.h"

namespace Rodin::MMG
{
  /**
   * @brief Discretizes implicit geometry defined by a nodal level-set field.
   *
   * Given a scalar function @f$\phi@f$ on a background mesh @f$D@f$, this class
   * drives MMG level-set mode to construct either:
   * - a boundary-fitted volume mesh for one side of @f$\phi = \mathrm{ls}@f$, or
   * - an explicit surface mesh of the isovalue when @ref surface is enabled.
   *
   * It also supports material-splitting policies (see @ref SplitMap) so
   * multi-material meshes can be split into interior/exterior regions with
   * user-defined labels.
   *
   * The canonical signed-distance interpretation is:
   * @f[
   *  \left\{
   *    \begin{aligned}
   *      \phi(x) < 0 && \text{if } \ x &\in \Omega\\
   *      \phi(x) = 0 && \text{if } \ x &\in \partial \Omega\\
   *      \phi(x) > 0 && \text{if } \ x &\in D \backslash \overline{\Omega}\\
   *    \end{aligned}
   *  \right.
   * @f]
   *
   * Inherits common remeshing controls from @ref MMG5 (hmin/hmax/hausdorff/
   * gradation/angle detection).
   */
  class LevelSetDiscretizer : public MMG5
  {
    public:
      /**
       * @brief Default constructor.
       */
      LevelSetDiscretizer()
        : m_ls(0.0),
          m_meshTheSurface(false)
      {}

      /**
       * @brief Selects whether to discretize the surface or a subdomain volume.
       * @param[in] meshTheSurface If `true`, extract/mesh the isosurface.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& surface(bool meshTheSurface = true);

      /**
       * @brief Specifies the level set to discretize.
       * @param[in] ls Isovalue to extract/discretize.
       *
       * The default value is `0`, corresponding to the zero-level set.
       *
       * @returns Reference to self (for method chaining)
       */
      LevelSetDiscretizer& setLevelSet(Real ls);

      /**
       * @brief Specifies the removal of small parasitic components.
       * @param[in] rmc Relative volume threshold used by MMG to remove tiny
       * connected components generated by cutting operations.
       * @returns Reference to self (for method chaining)
       */
      LevelSetDiscretizer& setRMC(Real rmc = 1e-5);

      /**
       * @brief Restricts level-set splitting to one base material.
       * @param[in] ref Attribute of the base material to split.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& setBaseReferences(Geometry::Attribute ref)
      {
        return setBaseReferences(FlatSet<Geometry::Attribute>{ref});
      }

      /**
       * @brief Restricts level-set splitting to a set of base materials.
       * @param[in] refs Attributes of base materials to split.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& setBaseReferences(const FlatSet<Geometry::Attribute>& refs);

      /**
       * @brief Sets the material reference for the discretized boundary
       * @f$ \partial \Omega @f$
       * @param[in] ref Boundary attribute assigned to newly created interface entities.
       *
       * Specifies what the label for the boundary @f$ \partial \Omega @f$ will
       * be. By default, the value is 10.
       *
       * @returns Reference to self (for method chaining)
       */
      LevelSetDiscretizer& setBoundaryReference(const Geometry::Attribute& ref);

      /**
       * @brief Specifies how to split the materials into an interior and
       * exterior domains.
       * @param[in] split Per-material split policy.
       *
       * This map specifies for each input material reference the values of the
       * 2 new domains created by the level-set splitting. By default, the
       * material references of the interior and exterior, are 2 and 3
       * respectively.
       *
       * @returns Reference to self (for method chaining)
       */
      LevelSetDiscretizer& setSplit(const SplitMap& split);

      /**
       * @brief Indicates that a material reference should be split.
       * @param[in] ref Material to split
       * @param[in] s Interior and exterior labels
       * @returns Reference to self (for method chaining)
       */
      LevelSetDiscretizer& split(const Geometry::Attribute& ref, const Split& s);

      /**
       * @brief Indicates that a material reference should not be split.
       * @param[in] ref Material reference that should not be split
       * @returns Reference to self (for method chaining)
       */
      LevelSetDiscretizer& noSplit(const Geometry::Attribute& ref);

      /**
       * @brief Discretizes and optimizes an implicitly defined surface defined
       * by a level set function.
       * @param[in] ls Scalar level-set field defined on a P1 local finite
       * element space over the input mesh.
       * @returns Output MMG mesh after cutting/remeshing.
       *
       * The material reference of the generated level-set boundary defaults to
       * `10` unless changed via @ref setBoundaryReference.
       */
      MMG::Mesh discretize(const MMG::RealGridFunction& ls);

      /**
       * @brief Enables/disables ridge angle detection.
       * @param[in] enable If `true`, enable angle detection.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& setAngleDetection(bool enable = true)
      {
        MMG5::setAngleDetection(enable);
        return *this;
      }

      /**
       * @brief Sets the minimum edge size constraint.
       * @param[in] hmin Minimum size.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& setHMin(Real hmin)
      {
        MMG5::setHMin(hmin);
        return *this;
      }

      /**
       * @brief Sets the maximum edge size constraint.
       * @param[in] hmax Maximum size.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& setHMax(Real hmax)
      {
        MMG5::setHMax(hmax);
        return *this;
      }

      /**
       * @brief Sets the Hausdorff tolerance controlling boundary approximation.
       * @param[in] hausd Hausdorff value.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& setHausdorff(Real hausd)
      {
        MMG5::setHausdorff(hausd);
        return *this;
      }

      /**
       * @brief Sets the allowed gradation between adjacent edge sizes.
       * @param[in] hgrad Gradation ratio.
       * @returns Reference to this object.
       */
      LevelSetDiscretizer& setGradation(Real hgrad)
      {
        MMG5::setGradation(hgrad);
        return *this;
      }

      /**
       * @brief Gets the configured material split map.
       * @returns Immutable split policy map.
       *
       * This is the user-provided map set by @ref setSplit/@ref split/@ref noSplit.
       * Internally, the implementation may derive temporary unique labels, but
       * those are not exposed here.
       */
      const SplitMap& getSplitMap() const
      {
        return m_split;
      }

    private:
      /**
       * @brief Runs MMG2D level-set discretization kernel.
       * @param[in, out] mesh MMG2D mesh.
       * @param[in, out] sol MMG level-set solution.
       * @returns MMG return code.
       */
      ReturnCode discretizeMMG2D(MMG5_pMesh mesh, MMG5_pSol sol);
      /**
       * @brief Runs MMG3D level-set discretization kernel.
       * @param[in, out] mesh MMG3D mesh.
       * @param[in, out] sol MMG level-set solution.
       * @returns MMG return code.
       */
      ReturnCode discretizeMMG3D(MMG5_pMesh mesh, MMG5_pSol sol);
      /**
       * @brief Runs MMGS level-set discretization kernel for surface meshes.
       * @param[in, out] mesh MMGS mesh.
       * @param[in, out] sol MMG level-set solution.
       * @returns MMG return code.
       */
      ReturnCode discretizeMMGS(MMG5_pMesh mesh, MMG5_pSol sol);

      /**
       * @brief Builds unique temporary split labels to avoid attribute collisions.
       * @param[in] attr Existing mesh attributes.
       */
      void generateUniqueSplit(const FlatSet<Geometry::Attribute>& attr);

      /**
       * @brief Removes boundary entities carrying a specific attribute.
       * @param[in, out] mesh MMG mesh to edit.
       * @param[in] ref Boundary attribute to remove.
       */
      void deleteBoundaryRef(MMG5_pMesh mesh, Geometry::Attribute ref);

      Real m_ls; ///< Target level-set value defining the interface.
      SplitMap m_split; ///< User-provided material split policy.
      bool m_meshTheSurface; ///< If true, extract/mesh the isosurface.
      Optional<Real> m_rmc; ///< Optional removal threshold for small components.
      FlatSet<Geometry::Attribute> m_lsBaseReferences; ///< Optional base references for LS mode.
      Optional<Geometry::Attribute> m_isoref; ///< Optional boundary attribute for extracted interface.

      SplitMap m_uniqueSplit; ///< Collision-free split policy passed to MMG.

      /**
       * @internal
       *
       * Generated attribute to original attribute map.
       */
      UnorderedMap<Geometry::Attribute, Geometry::Attribute> m_g2om;
  };
}
#endif
