add_subdirectory(Poisson)
add_subdirectory(Helmholtz)
add_subdirectory(Conductivity)
add_subdirectory(LinearElasticity)
add_subdirectory(ReactionDiffusion)
add_subdirectory(NonlinearPoisson)
if (RODIN_USE_PETSC AND NOT RODIN_CONVERGENCE_PETSC_COMPLEX)
  add_subdirectory(PETScNonlinearPoisson)
endif()
add_subdirectory(Stokes)
if (RODIN_USE_PETSC AND NOT RODIN_CONVERGENCE_PETSC_COMPLEX
    AND RODIN_CONVERGENCE_PETSC_MUMPS)
  add_subdirectory(PETScStokes)
endif()
