name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

concurrency:
  group: Build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc-12]
        build_type: ['Release', 'Debug']
        multithreaded: ['ON', 'OFF']
        mpi: ['ON']
        petsc: ['ON']
      fail-fast: false
    env:
      MAKEFLAGS: "-j2"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
      - name: Install dependencies
        run: >-
          sudo apt-get update && sudo apt-get install -y
          libboost1.74-all-dev
          libsuitesparse-dev
          libeigen3-dev
          libscotch-dev
          libmetis-dev
          libhdf5-dev
          libomp-dev
          petsc-dev
          mpich
          lcov
      - name: Configure CMake
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DRODIN_BUILD_DOC=OFF
          -DRODIN_USE_MCSS=OFF
          -DRODIN_BUILD_SRC=ON
          -DRODIN_BUILD_EXAMPLES=ON
          -DRODIN_MULTITHREADED=${{ matrix.multithreaded }}
          -DRODIN_USE_MPI=${{ matrix.mpi }}
          -DRODIN_USE_PETSC=${{ matrix.petsc }}
      - name: Build
        run: cmake --build ${{github.workspace}}/build
  MacOS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        build_type: ['Release', 'Debug']
        multithreaded: ['ON', 'OFF']
        mpi: ['ON']
        petsc: ['ON']
      fail-fast: false
    env:
      MAKEFLAGS: "-j2"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: actions/setup-python#577
        run: |
          brew list -1 | grep python | while read formula; do brew unlink $formula; brew link --overwrite $formula; done
      - name: Install dependencies
        run: |
          brew update
          brew install \
            boost boost-mpi \
            suitesparse \
            eigen \
            scotch \
            metis \
            hdf5-mpi \
            libomp \
            petsc \
            open-mpi \
            lcov
      - name: Configure CMake
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DRODIN_BUILD_DOC=OFF
          -DRODIN_USE_MCSS=OFF
          -DRODIN_BUILD_SRC=ON
          -DRODIN_BUILD_EXAMPLES=ON
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          -DRODIN_MULTITHREADED=${{ matrix.multithreaded }}
          -DRODIN_USE_MPI=${{ matrix.mpi }}
          -DRODIN_USE_PETSC=${{ matrix.petsc }}
          -DOpenMP_ROOT=/opt/homebrew/opt/libomp
      - name: Build
        run: cmake --build ${{github.workspace}}/build

